const V=require('../../utils/view'),M=require('../../utils/task-model'),S=require('../../utils/schedule-model');
Page(V.page({
 data:{filter:'active',groups:[],query:'',yearIndex:0,departmentIndex:0,completionIndex:0,seriesIndex:0},
 renderState(s){this.snapshot=s;const years=[...new Set(s.events.map(e=>S.academicYear(e.date)))].sort().reverse();this.setData({years:['全部学年',...years],departmentOptions:['全部部门',...V.depts],completionOptions:['全部归档','已全部完成','部分已归档'],seriesOptions:['全部系列',...(s.series||[]).map(item=>item.name)]});this.filterTasks()},
 filterTasks(){const s=this.snapshot;if(!s)return;const archive=this.data.filter==='archive',tasks=s.tasks.filter(t=>(t.status==='done')===archive).sort(M.compare),english=s.settings?.language==='en',query=this.data.query.trim().toLowerCase(),year=this.data.years[this.data.yearIndex],department=V.depts[this.data.departmentIndex-1],series=s.series?.[this.data.seriesIndex-1];let groups=M.groups(s.events,tasks).filter(g=>g.tasks.length||!archive&&!s.tasks.some(t=>t.event===g.id)).map(g=>{const all=s.tasks.filter(t=>t.event===g.id),done=all.filter(t=>t.status==='done').length;return {...g,open:this.expanded?.[g.id]!==false,allTaskCount:all.length,doneCount:done,allComplete:g.scheduleState?g.scheduleState==='archived':all.length>0&&done===all.length,seriesName:s.series?.find(item=>item.id===g.seriesId)?.name||'',academicYear:S.academicYear(g.date),tasks:g.tasks.filter(t=>!department||(t.depts||[t.dept]).includes(department))}}).filter(g=>(!this.data.yearIndex||g.academicYear===year)&&(!department||g.department===department||g.tasks.length>0)&&(!series||g.seriesId===series.id)&&(!archive||!this.data.completionIndex||(this.data.completionIndex===1?g.allComplete:!g.allComplete))&&(!query||[g.name,g.description,...g.tasks.flatMap(t=>[t.name,t.ownerName,t.submission])].filter(Boolean).join(' ').toLowerCase().includes(query)));
 if(archive)groups.sort((a,b)=>b.date.localeCompare(a.date)||a.name.localeCompare(b.name));this.setData({tabs:[{id:'active',label:english?'Current':'日程'},{id:'archive',label:english?'Archive':'归档'}],urgent:archive?[]:tasks.filter(t=>t.scheduleEnabled!==false&&['high','urgent'].includes(t.priority)),events:s.events,manager:s.manager,archive,groups,visibleTaskCount:groups.reduce((n,g)=>n+g.tasks.length,0),archiveEmpty:english?'No matching archived tasks':'没有符合条件的归档内容',childLabel:english?'tasks':'子任务'})},
 search(e){this.setData({query:e.detail.value});this.filterTasks()},
 selector(e){const key=e.currentTarget.dataset.key,index=Number(e.detail.value);if(!['yearIndex','departmentIndex','completionIndex','seriesIndex'].includes(key)||!Number.isInteger(index))return;this.setData({[key]:index});this.filterTasks()},
 resetFilters(){this.setData({query:'',yearIndex:0,departmentIndex:0,completionIndex:0,seriesIndex:0});this.filterTasks()},
 filter(e){this.setData({filter:e.currentTarget.dataset.id});this.filterTasks()},
 toggle(e){this.expanded||={};const id=e.currentTarget.dataset.id,g=this.data.groups.find(g=>g.id===id);if(!g)return;this.expanded[id]=!g.open;this.filterTasks()}
}));
