const V=require('../../utils/view'),UI=require('../../utils/interface'),M=require('../../utils/stats-model'),R=require('../../utils/recovery');
const zh={title:'访问统计',period:'最近 14 天',intro:'仅管理员可查看。位置为国家 / 地区的粗略示意，未知来源保留为未知。',forbidden:'此页面仅供管理员查看。',reload:'刷新统计',repair:'整理统计',clear:'清除访问与诊断统计',confirm:'清除访问与诊断统计？账号、活动和任务会保留。',done:'统计维护已完成',map:'全球访问分布',countries:'国家 / 地区',networks:'脱敏访问网段',risk:'风险与修复建议',logs:'网页请求与错误日志',empty:'暂无记录',unknown:'未知位置',requests:'请求',views:'页面访问',visitors:'访客日',failures:'处理异常',risks:'风险信号',rate:'异常比例',trend:'访问趋势',privacy:'保留 14 天，最多 1200 条请求日志。IPv4 按 /24、IPv6 按 /48 脱敏，不保存完整 IP、账号关联、请求正文、Cookie 或查询参数。访客按日去重，跨日相加为访客日。风险信号用于排查，并非攻击结论。',all:'全部',riskOnly:'风险',errorOnly:'异常',maintenance:'维护操作仅影响访问和诊断统计。'};
const en={title:'Access statistics',period:'Last 14 days',intro:'Administrators only. The map shows approximate country or region locations; unavailable sources remain unknown.',forbidden:'This page is available to administrators only.',reload:'Refresh',repair:'Organize statistics',clear:'Clear traffic & diagnostic statistics',confirm:'Clear traffic and diagnostic statistics? Accounts, events and tasks are retained.',done:'Statistics maintained',map:'Global traffic',countries:'Country / region',networks:'Masked visitor networks',risk:'Risk signals & remedies',logs:'Web request & error log',empty:'No records yet',unknown:'Unknown location',requests:'Requests',views:'Page views',visitors:'Visitor-days',failures:'Processing errors',risks:'Risk signals',rate:'Error rate',trend:'Traffic trend',privacy:'Retained for 14 days, with up to 1200 request logs. IPs are masked to IPv4 /24 or IPv6 /48. No raw IP, account mapping, bodies, cookies or query strings are stored. Visitors are deduplicated daily; totals are visitor-days. Signals support investigation, not an attack verdict.',all:'All',riskOnly:'Risks',errorOnly:'Errors',maintenance:'Maintenance affects traffic and diagnostic statistics only.'};
const knownCode=code=>Object.prototype.hasOwnProperty.call(M.codes,code);
const knownRoutes=new Set(['captcha','info','setup','register','login','recover','logout','password','state','members','members/update','invite','reset-link','events/create','events/update','events/delete','events/reschedule','tasks/create','tasks/action','templates/save','profile/request','profile/review','settings/save','account/request','account/cancel','account/review','stats','stats/maintenance','unknown']);
function network(raw){if(raw==='本机 / 内网'||raw==='未知来源')return UI.language()==='en'?(raw==='本机 / 内网'?'Local / private network':'Unknown source'):raw;if(typeof raw!=='string')return 'unknown';if(/^\d{1,3}\.\d{1,3}\.\d{1,3}\.0\/24$/.test(raw)&&raw.slice(0,-3).split('.').every(v=>Number(v)<=255))return raw;if(/^[a-f0-9]{1,4}:[a-f0-9]{1,4}:[a-f0-9]{1,4}::\/48$/i.test(raw))return raw.toLowerCase();return 'unknown'}
function safeEvents(rows,en){return(Array.isArray(rows)?rows:[]).slice(0,1200).filter(e=>e&&typeof e==='object').map(e=>{const code=knownCode(e.code)?e.code:'',country=typeof e.country==='string'&&(/^[A-Z]{2}$/.test(e.country)||e.country==='unknown')?e.country:'unknown',time=typeof e.time==='number'&&Number.isFinite(e.time)&&e.time>0&&e.time<8640000000000000?e.time:0,route=['page','mini','knowledge','asset','sensitive-probe','unknown'].includes(e.route)||typeof e.route==='string'&&e.route.startsWith('api:')&&knownRoutes.has(e.route.slice(4))?e.route:'unknown';return{time:time?new Date(time).toISOString().slice(0,16).replace('T',' '):'—',label:code?M.codes[code][en?1:0]:(en?'Request':'请求'),code,method:['GET','POST','HEAD','OPTIONS','PUT','DELETE','PATCH','OTHER'].includes(e.method)?e.method:'—',route,status:M.number(e.status),duration:Math.round(M.number(e.duration)),network:network(e.network),country:M.country(country,en),risk:e.risk===true||e.risk===1}})}
Page(V.page({
 data:{allowed:false,ready:false,countries:[],networks:[],signals:[],logs:[],visibleLogs:[],days:[],filter:'all'},
 onLoad(){this.statsUnsubscribe=V.api.subscribe?.(s=>{if(!s||s.user?.role!=='admin'||this.user&&s.user?.id!==this.user.id)this.clearStats()})},
 clearStats(){this.loadEpoch=(this.loadEpoch||0)+1;this.canvas=null;this.ctx=null;this.setData({ready:false,countries:[],networks:[],signals:[],logs:[],visibleLogs:[],days:[],cards:[]})},
 renderState(s){if(this.user&&this.user.id!==s.user?.id)this.clearStats();this.user=s.user;const allowed=s.user?.role==='admin',l=UI.language()==='en'?en:zh;this.setData({allowed,l});try{wx.setNavigationBarTitle?.({title:l.title})}catch{}if(!allowed){this.clearStats();return}this.load()},
 onShow(){if(this.data.allowed)this.load()},onHide(){this.canvas=null;this.ctx=null},onResize(){if(this.data.ready)this.drawMap()},
 onUnload(){this.destroyed=true;this.statsUnsubscribe?.();this.loadEpoch=(this.loadEpoch||0)+1;this.user=null;this.canvas=null;this.ctx=null;for(const k of ['countries','networks','signals','logs','visibleLogs','days','cards'])this.data[k]=[]},
 async load(){if(this.loading||this.destroyed||this.user?.role!=='admin')return;this.loading=true;this.setData({loading:true});const token=V.api.token(),owner=this.user.id,epoch=this.loadEpoch=(this.loadEpoch||0)+1;try{const stats=await V.api.call('stats');if(this.destroyed||epoch!==this.loadEpoch||token!==V.api.token()||this.user?.id!==owner||this.user.role!=='admin')return;this.publish(stats);this.setData({syncError:''})}catch(e){if(!this.destroyed&&token===V.api.token()&&this.user?.id===owner)this.setData({syncError:UI.t(e.message||'暂未完成操作')})}finally{this.loading=false;if(!this.destroyed)this.setData({loading:false})}},
 publish(s){const enMode=UI.language()==='en',l=enMode?en:zh,t=s?.summary||{},countries=M.countries(s?.countries,enMode),logs=safeEvents(s?.events,enMode),days=(Array.isArray(s?.days)?s.days:[]).slice(0,14).filter(d=>/^\d{4}-\d{2}-\d{2}$/.test(d.date||'')).reverse().map(d=>({date:d.date.slice(5),hits:M.number(d.hits)})),max=Math.max(1,...days.map(d=>d.hits));days.forEach(d=>d.height=Math.round(d.hits/max*100));const cards=[['views',t.pageviews],['visitors',t.visitorDays],['requests',t.requests],['risks',t.risks],['failures',t.failures],['rate',t.errorRate]].map(([k,v])=>({label:l[k],value:M.number(v)+(k==='rate'?'%':'')}));this.setData({l,ready:true,cards,countries,days,logs,visibleLogs:this.filtered(logs),networks:(Array.isArray(s?.networks)?s.networks:[]).slice(0,60).map(n=>({network:network(n?.network),requests:M.number(n?.requests),visitorDays:M.number(n?.visitorDays)})),signals:(Array.isArray(s?.codes)?s.codes:[]).filter(c=>c&&knownCode(c.code)).map(c=>({code:c.code,label:M.codes[c.code][enMode?1:0],advice:M.codes[c.code][enMode?3:2],count:M.number(c.count)}))},()=>this.drawMap())},
 filtered(logs){return(logs||[]).filter(e=>this.data.filter==='risk'?e.risk:this.data.filter==='error'?e.status>=500:true).slice(0,120)},
 filter(e){this.setData({filter:e.currentTarget.dataset.filter},()=>this.setData({visibleLogs:this.filtered(this.data.logs)}))},
 drawMap(){if(this.destroyed||!this.data.allowed||!this.data.ready)return;try{wx.createSelectorQuery().in(this).select('#stats-map').fields({node:true,size:true},r=>{if(this.destroyed||!this.data.allowed||!r?.node||!r.width||!r.height)return;try{const canvas=r.node,ctx=canvas.getContext('2d'),dpr=Math.min(wx.getSystemInfoSync?.().pixelRatio||1,2);canvas.width=Math.round(r.width*dpr);canvas.height=Math.round(r.height*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);const w=r.width,h=r.height;ctx.clearRect(0,0,w,h);ctx.fillStyle=this.data.dark?'#353535':'#e9ecef';for(const land of M.continents){ctx.beginPath();for(let i=0;i<land.length;i+=2){const p=M.project(land[i],land[i+1],w,h);i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y)}ctx.closePath();ctx.fill()}const max=Math.max(1,...this.data.countries.map(c=>c.requests));ctx.fillStyle=R.applySettings(V.api.getState()?.settings).themeColor;for(const c of this.data.countries){if(!c.point)continue;const x=c.point.x/720*w,y=c.point.y/360*h,radius=3+Math.sqrt(c.requests/max)*7;ctx.globalAlpha=.7;ctx.beginPath();ctx.arc(x,y,radius,0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1;this.canvas=canvas;this.ctx=ctx;R.markSuccess('canvas')}catch(error){R.capture(error,'canvas');this.setData({mapFallback:true})}}).exec()}catch(error){R.capture(error,'canvas');this.setData({mapFallback:true})}},
 reload(){return this.load()},async maintain(e){if(this.destroyed||this.user?.role!=='admin'||V.api.isReadOnly?.())return;const token=V.api.token(),owner=this.user.id,action=e.currentTarget.dataset.action;if(!['repair','clear'].includes(action))return;if(action==='clear'){const confirmed=await new Promise(resolve=>wx.showModal({title:this.data.l.clear,content:this.data.l.confirm,success:r=>resolve(r.confirm===true),fail:()=>resolve(false)}));if(!confirmed)return}if(this.destroyed||this.user?.role!=='admin'||this.user.id!==owner||V.api.token()!==token||V.api.getState()?.user?.id!==owner)return;await V.action(this,async()=>{await V.api.mutate('stats/maintenance',{action});await this.load();wx.showToast({title:this.data.l.done,icon:'success'})})}
}));
