const V=require('../../utils/view'),O=require('../../utils/organization'),M=require('../../utils/task-model'),T=require('../../utils/task-ui');
const F=(key,label,value='',type='text',options=[])=>({key,label,value:value??'',type,options:options.map(o=>typeof o==='string'?{label:o,value:o}:o)});
const fieldList=items=>items.map(f=>{if(f.type==='multiPerson'){f.containsNames=true;f.value=Array.isArray(f.value)?f.value:[];f.options=f.options.map(o=>({...o,checked:f.value.includes(o.value)}));f.groups=O.groups(f.options);f.selectedPeople=f.options.filter(o=>o.checked);f.display=f.selectedPeople.map(o=>o.name||o.label).join('、')||'请选择';f.open=!!f.open}if(f.type==='select'&&f.options.some(o=>o.kind==='personOption'))f.type='person';if(f.type==='person'){f.containsNames=true;f.groups=O.groups(f.options);f.display=f.options.find(o=>o.value===f.value)?.name||f.options.find(o=>o.value===f.value)?.label||'请选择';f.open=!!f.open}if(f.type==='select'){f.selected=Math.max(0,f.options.findIndex(o=>o.value===f.value));f.value=f.options[f.selected]?.value||'';f.display=f.options[f.selected]?.label||'请选择'}if(f.type==='checks')f.options=f.options.map(o=>({...o,checked:Array.isArray(f.value)&&f.value.includes(o.value)}));return f});
Page(V.page({data:{fields:[],title:'编辑',busy:false,resultToken:'',stepCount:0},renderState(s){this.setData({shareLabel:s.settings?.language==='en'?'Share mini program':'分享小程序'});this.snapshot=s;if(!this.initialized){this.initialized=true;this.initialize()}},
 initialize(){const o=this.options,s=this.snapshot,u=s.user,e=s.events.find(x=>x.id===o.id||x.id===o.event),t=s.tasks.find(x=>x.id===o.id);let fields=[],title='编辑';this.initialValues={};
  const eventDept=e?.department??s.events.find(ev=>ev.id===t?.event)?.department??s.settings?.workspace;const people=T.people(s.people,eventDept,true),reviewers=T.people(s.people,eventDept,false);
  const rewards=x=>[F('priority','任务优先级',x?.priority||'normal','select',[{value:'low',label:'低'},{value:'normal',label:'普通'},{value:'high',label:'高'},{value:'urgent',label:'紧急'}]),F('rewardPoints','任务总积分（共同执行人均分）',x?.rewardPoints||0,'number'),F('rewardNote','其他奖励备注',x?.rewardNote||'')];
  if(o.mode==='event-new'||o.mode==='event-edit'){
    const x=o.mode==='event-edit'?e:{};if(!x){this.setData({error:'活动不存在'});return}title=o.mode==='event-new'?'新建活动':'编辑活动';
    fields=[...(o.mode==='event-new'?[F('template','选择模板',o.template||'blank','select',[{value:'blank',label:'空白日程 · 自由创建'},...s.templates.map(t=>({value:t.id,label:t.name}))])]:[]),F('department','工作模式',x.department??s.settings?.workspace??'','select',[{value:'',label:'全体协作'},...(u.role==='admin'?V.depts:[u.dept]).map(value=>({value,label:value}))]),F('name','活动名称',x.name),F('allDay','全天',x.allDay!==false,'switch'),F('date','开始日期',x.date||V.day(),'date'),F('endDate','结束日期',x.endDate||x.date||V.day(),'date'),F('startTime','开始时间（非全天生效）',x.startTime||'09:00','time'),F('endTime','结束时间（非全天生效）',x.endTime||'10:00','time'),F('location','地点（可选）',x.location),F('source','需求来源',x.source||'学媒自有','select',['学媒自有','外派需求']),F('requester','需求方 / 对接人（可选）',x.requester,'person',[{value:'',label:'未指定'},...s.people.map(p=>({...T.person(p),value:p.name})),{value:'__other__',label:'其他 · 填写姓名'}]),F('requesterOther','其他对接人姓名',s.people.some(p=>p.name===x.requester)?'':x.requester||''),F('description','活动说明与交付目标',x.description,'textarea'),F('cloudUrl','活动云盘上传链接（可稍后填写）',x.cloudUrl),...rewards(x)];
  }else if(['task-new','task-edit','task-reassign'].includes(o.mode)){
    const x=o.mode==='task-new'?{}:t;if(!x){this.setData({error:'任务不存在'});return}const event=e||s.events.find(e=>e.id===t?.event)||{};this.taskEvent=event;
    if(o.mode==='task-reassign'){if(!M.permissions(t,u,s.people,event).canReassign){this.setData({error:'当前不能转派这个任务'});return}title='转派给本部门成员';const subordinates=T.people(s.people.filter(p=>p.role==='member'&&p.dept===u.dept),u.dept,true);fields=[F('owners','新的共同执行人',[],'multiPerson',subordinates)];this.setData({templateHint:s.settings?.language==='en'?'Replaces your assignment. Co-assignees, reviewers and total points remain unchanged.':'仅替换你自己的执行席位；其他共同执行人、验收人与任务总积分保持不变。'})}
    else {if(o.mode==='task-edit'&&!M.permissions(t,u,s.people,event).canEdit){this.setData({error:'当前不能编辑这个任务'});return}title=o.mode==='task-new'?'添加任务':'编辑任务';const ownerDefaults=M.owners(x).filter(id=>people.some(p=>p.value===id)),receiverDefaults=M.receivers(x).filter(id=>reviewers.some(p=>p.value===id));
    fields=[F('name','任务名称',x.name||''),F('owners','共同执行人（可多选）',ownerDefaults.length?ownerDefaults:people.some(p=>p.value===u.id)?[u.id]:people.length?[people[0].value]:[],'multiPerson',people),F('receivers','共同验收人（可多选）',receiverDefaults.length?receiverDefaults:reviewers.some(p=>p.value===u.id)?[u.id]:reviewers.length?[reviewers[0].value]:[],'multiPerson',reviewers),F('dueDate','截止日期',x.due?.slice(0,10)||event.date||V.day(),'date'),F('dueTime','截止时间',x.due?.slice(11,16)||event.endTime||'18:00','time'),F('requirements','交付要求',x.requirements||'','textarea'),F('depends','前序任务（全部验收后解锁）',x.depends||[],'checks',s.tasks.filter(task=>task.event===event.id&&task.id!==x.id).map(task=>({value:task.id,label:task.name}))),F('checksText','交付核对项（每行一项）',(x.checks||['核对活动信息与交付要求','确认成果已上传并可访问']).join('\n'),'textarea'),...rewards(o.mode==='task-new'?event:x)];}
  }else if(['template-new','template-edit','template-from'].includes(o.mode)){
    let x=s.templates.find(t=>t.id===o.id)||{name:'',steps:[]};
    if(o.mode==='template-from'){const tasks=s.tasks.filter(t=>t.event===e?.id);x={name:(e?.name||'活动')+'流程',description:e?.description||'',steps:tasks.map(t=>({name:t.name,dept:t.dept,offset:Math.round((Date.parse(t.due.slice(0,10))-Date.parse(e.date))/86400000),time:t.due.slice(11,16),depends:t.depends.map(id=>tasks.findIndex(t=>t.id===id)),requirements:t.requirements,rewardPoints:t.rewardPoints,rewardNote:t.rewardNote}))};}
    this.templateId=x.createdBy&&(u.role==='admin'||x.createdBy===u.id)?x.id:'';title=this.templateId?'编辑模板':'创建模板';
    fields=[F('name','模板名称',x.name),F('description','使用说明',x.description,'textarea')];this.setData({stepCount:x.steps.length});x.steps.forEach((step,i)=>fields.push(...this.stepFields(step,i)));
  }else if(o.mode==='member'){
    title='管理成员';const m=this.member;if(!m){this.loadMember();return}fields=[F('dept','部门',m.dept,'select',u.role==='admin'?V.depts:[u.dept]),F('role','角色',m.role,'select',(u.role==='admin'?['member','manager','admin']:['member']).map(value=>({value,label:V.roles[value]}))),F('status','账号状态',m.status==='disabled'?'disabled':'active','select',[{value:'active',label:'开通'},{value:'disabled',label:'停用 / 拒绝申请'}])];
  }else if(o.mode==='invite'){title='邀请成员';fields=[F('dept','部门',u.dept,'select',u.role==='admin'?V.depts:[u.dept]),F('role','角色','member','select',(u.role==='admin'?['member','manager']:['member']).map(value=>({value,label:V.roles[value]})))];
  }else if(o.mode==='password'){title='修改密码';fields=[F('oldPassword','当前密码','','password'),F('password','新密码（至少 10 个字符）','','password'),F('confirm','再次输入新密码','','password')];}
  fields=fields.map(f=>{if(f.key==='requester'){f.groups=O.groups(f.options);f.value=s.people.some(p=>p.name===f.value)?f.value:f.value?'__other__':'';f.display=f.options.find(o=>o.value===f.value)?.label||'未指定'}if(f.key==='requesterOther')f.hidden=!fields.some(x=>x.key==='requester'&&x.value==='__other__');return f});this.setData({title,fields:fieldList(fields),isTemplate:o.mode.startsWith('template-'),isMember:o.mode==='member'});if(o.mode==='event-new')this.assignments();
 },
 async loadMember(){try{const b=await V.api.call('members');this.member=b.members.find(m=>m.id===this.options.id);if(!this.member)throw Error('成员不存在');this.initialize()}catch(e){V.error(e)}},
 stepFields(s,i){const k='step'+i+'_';return [F(k+'name',`环节 ${i+1} · 名称`,s.name),F(k+'dept','建议部门',s.dept||this.snapshot.user.dept,'select',V.depts),F(k+'offset','相对开始日天数（可为负数）',s.offset??0,'signed'),F(k+'time','截止时间',s.time||'18:00','time'),F(k+'depends','前序环节编号（如 1,2；可空）',(s.depends||[]).map(j=>j+1).join(',')),F(k+'requirements','交付要求',s.requirements||'','textarea'),F(k+'rewardPoints','积分（空白沿用活动默认）',s.rewardPoints??'','number'),F(k+'rewardNote','其他奖励',s.rewardNote||'')];},
 togglePerson(e){const i=Number(e.currentTarget.dataset.index);this.setData({['fields['+i+'].open']:!this.data.fields[i].open})},personDept(e){const i=Number(e.currentTarget.dataset.index);this.setData({['fields['+i+'].department']:e.currentTarget.dataset.dept})},selectPerson(e){const i=Number(e.currentTarget.dataset.index),f=this.data.fields[i],value=e.currentTarget.dataset.value,option=f.options.find(o=>o.value===value);this.setData({['fields['+i+'].value']:value,['fields['+i+'].display']:option?.label||'请选择',['fields['+i+'].open']:false});if(f.key==='requester'){const j=this.data.fields.findIndex(x=>x.key==='requesterOther');this.setData({['fields['+j+'].hidden']:value!=='__other__'})}},
 togglePersonChoice(e){const i=Number(e.currentTarget.dataset.index),value=e.currentTarget.dataset.value,f=this.data.fields[i];if(f?.type!=='multiPerson'||!f.options.some(o=>o.value===value))return;const selected=f.value.includes(value)?f.value.filter(v=>v!==value):[...f.value,value];const fields=this.data.fields.map((v,j)=>j===i?{...v,value:selected}:v);this.setData({fields:fieldList(fields)})},
 values(){return Object.fromEntries(this.data.fields.map(f=>[f.key,f.value]))},
 change(e){const i=Number(e.currentTarget.dataset.index),f=this.data.fields[i];let value=e.detail.value;const fields=this.data.fields.slice();if(f.type==='select'){const n=Number(value);fields[i]={...f,selected:n,value:f.options[n].value,display:f.options[n].label}}else fields[i]={...f,value};this.setData({fields:fieldList(fields)});if(f.key==='template'||f.key==='department')this.assignments();if(f.key==='date'){const vals=this.values();if(vals.endDate<value){const j=fields.findIndex(x=>x.key==='endDate');this.setData({[`fields[${j}].value`]:value})}}},
 assignments(){const d=this.values(),template=this.snapshot.templates.find(t=>t.id===d.template),people=T.people(this.snapshot.people,d.department,true),reviewers=T.people(this.snapshot.people,d.department,false),fields=this.data.fields.filter(f=>!f.key.startsWith('assign'));if(template)template.steps.forEach((step,i)=>{const first=people.find(p=>p.dept===step.dept)||people[0],previousOwners=Array.isArray(d['assign'+i+'_owners'])?d['assign'+i+'_owners'].filter(id=>people.some(p=>p.value===id)):[],previousReviewers=Array.isArray(d['assign'+i+'_receivers'])?d['assign'+i+'_receivers'].filter(id=>reviewers.some(p=>p.value===id)):[];fields.push(F('assign'+i+'_owners',step.name+' · 共同执行人',previousOwners.length?previousOwners:first?[first.value]:[],'multiPerson',people),F('assign'+i+'_receivers','共同验收人',previousReviewers.length?previousReviewers:reviewers.some(p=>p.value===this.snapshot.user.id)?[this.snapshot.user.id]:reviewers.length?[reviewers[0].value]:[],'multiPerson',reviewers))});this.setData({fields:fieldList(fields),templateHint:template?template.steps.length+' 个环节，可为每个环节选择多位执行人与验收人。':'只创建日程，不自动分配任务。'})},
 addStep(){if(this.data.stepCount>=30){V.error(Error('最多 30 个环节'));return}this.setData({fields:fieldList([...this.data.fields,...this.stepFields({},this.data.stepCount)]),stepCount:this.data.stepCount+1})},
 removeStep(){if(!this.data.stepCount)return;const i=this.data.stepCount-1;this.setData({fields:this.data.fields.filter(f=>!f.key.startsWith('step'+i+'_')),stepCount:i})},
 async save(){await V.action(this,async()=>{const d=this.values(),o=this.options;for(const field of this.data.fields)if(field.type==='multiPerson'&&(!Array.isArray(field.value)||!field.value.length))throw Error('请至少选择一位'+(field.key.includes('receivers')?'验收人':'执行人'));if(d.requester!==undefined)d.requester=d.requester==='__other__'?d.requesterOther:d.requester;let path,data=d;
   if(o.mode==='event-new'){path='events/create';const t=this.snapshot.templates.find(t=>t.id===d.template);data={...d,assignments:(t?.steps||[]).map((_,i)=>({owners:d['assign'+i+'_owners'],receivers:d['assign'+i+'_receivers']}))}}
   else if(o.mode==='event-edit'){path='events/update';data={...d,id:o.id}}
   else if(o.mode==='task-new'||o.mode==='task-edit'){path=o.mode==='task-new'?'tasks/create':'tasks/action';data={...d,event:this.taskEvent.id||o.event,id:o.id,action:'assign',due:d.dueDate+'T'+d.dueTime,depends:d.depends||[],checks:d.checksText.split(/\r?\n/).map(x=>x.trim()).filter(Boolean)}}
   else if(o.mode==='task-reassign'){path='tasks/action';data={id:o.id,action:'reassign',owners:d.owners}}
   else if(o.mode.startsWith('template-')){path='templates/save';data={name:d.name,description:d.description,...(this.templateId?{id:this.templateId}:{}),steps:Array.from({length:this.data.stepCount},(_,i)=>{const k='step'+i+'_';return {name:d[k+'name'],dept:d[k+'dept'],offset:Number(d[k+'offset']),time:d[k+'time'],depends:d[k+'depends'].trim()?d[k+'depends'].split(/[,，]/).map(x=>Number(x.trim())-1):[],requirements:d[k+'requirements'],rewardPoints:d[k+'rewardPoints']===''?null:Number(d[k+'rewardPoints']),rewardNote:d[k+'rewardNote']}})}}
   else if(o.mode==='member'){path='members/update';data={...d,id:o.id}}
   else if(o.mode==='invite')path='invite';
   else if(o.mode==='password'){if(d.password!==d.confirm)throw Error('两次新密码不一致');path='password'}
   if(!path)throw Error('未知编辑模式');const result=await V.api.mutate(path,data);
   if(path==='invite'){this.setData({resultToken:result.token,tokenLabel:'邀请码（7 天内一次有效）'});return}
   wx.showToast({title:'已保存并同步'});wx.navigateBack();
 })},copy(){wx.setClipboardData({data:this.data.resultToken})},
 async resetMember(){await V.action(this,async()=>{const b=await V.api.call('reset-link',{id:this.options.id});this.setData({resultToken:b.token,tokenLabel:'密码重置码（24 小时内一次有效）'})})}
}));
