import {spawn} from 'node:child_process';
import {mkdir,writeFile} from 'node:fs/promises';
import {pathToFileURL} from 'node:url';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE?pathToFileURL(process.env.PLAYWRIGHT_MODULE).href:'playwright');
const port=8877,base=`http://127.0.0.1:${port}`;
const server=spawn(process.execPath,['scripts/dev.mjs'],{env:{...process.env,PORT:String(port),DB_PATH:':memory:',BOOTSTRAP_HASH:createHash('sha256').update('local-preview-only-setup').digest('hex')},windowsHide:true,stdio:['ignore','pipe','pipe']});
let browser;const errors=[];
try{
  await new Promise((resolve,reject)=>{server.stdout.on('data',b=>{if(b.toString().includes('Local:'))resolve()});server.stderr.on('data',b=>process.stderr.write(b));server.on('error',reject);server.on('exit',code=>reject(Error('Server exited '+code)))});
  browser=await chromium.launch({channel:'msedge',headless:true});
  const context=await browser.newContext({viewport:{width:1440,height:1080}});
  const page=await context.newPage();page.on('pageerror',e=>{errors.push(e.message);console.error('BROWSER ERROR',e.message)});page.on('console',m=>{if(m.type()==='error')console.error(m.text())});
  await page.goto(base+'/#setup=local-preview-only-setup');
  await page.locator('[name=username]').fill('qa_owner');await page.locator('[name=name]').fill('测试负责人');
  await page.locator('[name=password]').fill('Browser-test-2026!');await page.locator('[name=confirm]').fill('Browser-test-2026!');
  await page.getByRole('button',{name:'创建管理员账号',exact:true}).click();
  await page.getByRole('heading',{name:'测试负责人，欢迎回来。'}).waitFor();
  const initial=(await page.evaluate(()=>api('state'))).user;
  assert.equal(!!initial.owner,true);assert.equal(initial.dept,'','Initial administrator has no department.');
  const memberContext=await browser.newContext({viewport:{width:1440,height:1080}});
  const memberPage=await memberContext.newPage();memberPage.on('pageerror',e=>errors.push(e.message));
  const peerContext=await browser.newContext();const peerPage=await peerContext.newPage();peerPage.on('pageerror',e=>errors.push(e.message));
  for(const [target,username,name] of [[memberPage,'qa_member','测试执行成员'],[peerPage,'qa_peer','测试共同成员']]){
    const invitation=await page.evaluate(()=>api('invite',{dept:'办公室',role:'member'}));
    await target.goto(base);await target.locator('#auth-form').waitFor();
    await target.evaluate(({username,name,invite})=>api('register',{username,name,dept:'办公室',password:'Browser-member-test-2026!',invite}),{username,name,invite:invitation.token});
    await target.reload();await target.getByRole('heading',{name:name+'，欢迎回来。'}).waitFor();
  }
  await page.evaluate(()=>refresh());const current=await page.evaluate(()=>api('state'));
  const assignee=current.people.find(p=>p.name==='测试执行成员'),coAssignee=current.people.find(p=>p.name==='测试共同成员');
  assert.equal(assignee.role,'member');assert.equal(coAssignee.role,'member');assert.equal(assignee.dept,'办公室');assert.equal(coAssignee.dept,'办公室');
  const monthPrefix=new Date().getFullYear()+'-'+String(new Date().getMonth()+1).padStart(2,'0');
  await page.locator('[data-create]').first().click();
  assert.equal(await page.locator('[name=template]').inputValue(),'blank');
  await page.locator('[name=name]').fill('迎新宣传协作');
  await page.locator('[name=date]').fill(monthPrefix+'-20');await page.locator('[name=endDate]').fill(monthPrefix+'-23');await page.locator('[name=department]').selectOption('办公室');
  await page.locator('[name=allDay]').uncheck();
  await page.locator('[name=activation]').evaluate(el=>el.closest('details').open=true);await page.locator('[name=activation]').selectOption('active');
  await page.locator('[name=location]').fill('书院报告厅');await page.locator('textarea[name=description]').fill('活动前预写文案，素材精选后完成推送与归档。');
  await page.locator('[name=cloudUrl]').fill('https://example.com/drive');
  await page.locator('.form-section summary').filter({hasText:'积分与其他奖励'}).click();await page.locator('[name=rewardPoints]').fill('20');await page.locator('[name=rewardNote]').fill('优秀作品展示');
  await page.getByRole('button',{name:'创建活动',exact:true}).click();
  await page.locator('dialog').waitFor({state:'hidden'});await page.getByText('空白日程 · 尚未派单').waitFor();
  await page.getByRole('button',{name:'＋ 任务',exact:true}).click();await page.locator('[name=name]').fill('摄影与精选照片交付');await page.locator('[name=requirements]').fill('精选 10—15 张照片，注明人物与摄影者。');
  assert.equal(await page.locator('#task-config-form [name=owners][value="'+initial.id+'"]').count(),0,'Initial administrator cannot be selected as an assignee.');
  await page.locator('#task-config-form [name=owners][value="'+assignee.id+'"]').check();await page.locator('#task-config-form [name=owners][value="'+coAssignee.id+'"]').check();
  await page.locator('#task-config-form [name=receivers][value="'+coAssignee.id+'"]').check();
  assert.equal(await page.locator('#task-config-form [name=receivers][value="'+initial.id+'"]').isChecked(),false,'Initial administrator is not a default reviewer.');
  await page.locator('#task-config-form [name=receivers][value="'+initial.id+'"]').evaluate(el=>el.closest('details').open=true);await page.locator('#task-config-form [name=receivers][value="'+initial.id+'"]').check();
  assert.ok(await page.locator('.party-option small').first().evaluate(el=>getComputedStyle(el).color!==getComputedStyle(el.parentElement).color),'Roles remain secondary to names.');
  await page.getByRole('button',{name:'添加并派单'}).click();await page.locator('dialog').waitFor({state:'hidden'});
  const created=await page.evaluate(()=>api('state'));const task=created.tasks.find(t=>t.name==='摄影与精选照片交付');
  assert.deepEqual(task.owners,[assignee.id,coAssignee.id]);assert.deepEqual([...task.receivers].sort(),[initial.id,coAssignee.id].sort());
  await page.locator('[data-task="'+task.id+'"]').first().click();assert.equal(await page.locator('[data-action=accept]').count(),0);assert.equal(await page.locator('[data-submit]').count(),0);await page.locator('[data-close]').click();
  await memberPage.locator('nav [data-view=activities]').click();await memberPage.locator('[data-task="'+task.id+'"]').first().waitFor();
  await memberPage.locator('.flow-step').first().click();await memberPage.getByRole('button',{name:'时间冲突',exact:true}).click();await memberPage.locator('[name=feedback]').fill('课程冲突，稍后确认');await memberPage.getByRole('button',{name:'提交',exact:true}).click();await memberPage.locator('dialog').waitFor({state:'hidden'});
  await memberPage.locator('.flow-step').first().click();await memberPage.getByRole('button',{name:'恢复接活',exact:true}).click();await memberPage.locator('dialog').waitFor({state:'hidden'});
  await memberPage.locator('.flow-step').first().click();await memberPage.getByRole('button',{name:'提交成果',exact:true}).click();
  await memberPage.locator('.check-help summary').first().hover();assert.equal(await memberPage.locator('.check-popover').first().isVisible(),true);
  await memberPage.locator('.check-help summary').first().click();await memberPage.locator('[name=check0]').check();await memberPage.locator('[name=check1]').check();await memberPage.locator('[name=submission]').fill('精选照片已上传，已按日期及场景命名，摄影署名见文件说明。');
  assert.equal(await memberPage.locator('[name=uploadConfirmed]').isDisabled(),true);
  // Avoid requesting the sample cloud URL, while exercising the click and confirmation controls.
  await memberContext.route('https://example.com/**',route=>route.fulfill({status:200,body:'QA cloud placeholder'}));
  const popupWait=memberPage.waitForEvent('popup');await memberPage.locator('[data-open-upload]').click();const popup=await popupWait;await popup.close();
  await memberPage.locator('[name=uploadConfirmed]').check();await memberPage.locator('[name=link]').fill('https://example.com/results');await memberPage.locator('[name=linkConfirmed]').check();
  await mkdir('.local/qa',{recursive:true});await memberPage.screenshot({path:'.local/qa/desktop-submit.png',fullPage:true});
  await memberPage.getByRole('button',{name:'提交给验收人',exact:true}).click();await memberPage.locator('dialog').waitFor({state:'hidden'});
  await page.evaluate(()=>refresh());await page.locator('[data-task="'+task.id+'"]').first().click();await page.getByRole('button',{name:'验收通过',exact:true}).click();await page.locator('dialog').waitFor({state:'hidden'});
  const completed=await page.evaluate(()=>api('state'));assert.equal(completed.tasks.find(t=>t.id===task.id).status,'done');const rewards=completed.ledger.filter(x=>x.task===task.id);assert.equal(rewards.length,2);assert.deepEqual(rewards.map(x=>x.points),[10,10]);assert.equal(rewards.reduce((n,x)=>n+x.points,0),20);assert.ok(rewards.every(x=>x.user!==initial.id));
  await page.locator('[data-view=rewards]').first().click();await page.getByText('+10',{exact:true}).first().waitFor();assert.equal(await page.getByText('+10',{exact:true}).count(),2);
  await page.locator('nav [data-view=archive]').click();await page.locator('main .task-row[data-task="'+task.id+'"].task-archived').waitFor();await page.locator('nav [data-view=calendar]').click();await page.locator('.calendar [data-task="'+task.id+'"].task-archived').waitFor();await page.locator('.calendar [data-event="'+task.event+'"]').first().click();await page.getByRole('button',{name:'保存为模板'}).click();await page.getByRole('button',{name:'保存模板',exact:true}).click();await page.locator('dialog').waitFor({state:'hidden'});
  await page.locator('nav [data-view=templates]').click();await page.getByRole('heading',{name:'迎新宣传协作流程'}).waitFor();
  await page.getByRole('button',{name:'＋ 创建模板'}).click();await page.locator('[name=name]').fill('新建模板测试');await page.locator('[data-add-step]').click();await page.locator('[data-key=name]').fill('需求登记');await page.locator('[data-key=requirements]').fill('登记需求方与交付形式');await page.getByRole('button',{name:'保存模板',exact:true}).click();await page.locator('dialog').waitFor({state:'hidden'});
  await page.locator('.template-card').filter({has:page.getByRole('heading',{name:'新建模板测试'})}).getByRole('button',{name:'使用模板'}).click();
  await page.locator('[name=name]').fill('从模板创建的活动');const assigned=page.locator('[data-assignment="0"]');for(const input of await assigned.locator('[name=owners]:checked').all())await input.uncheck();await assigned.locator('[name=owners][value="'+assignee.id+'"]').evaluate(el=>el.closest('details').open=true);await assigned.locator('[name=owners][value="'+assignee.id+'"]').check();assert.equal(await assigned.locator('[name=owners][value="'+initial.id+'"]').count(),0);await assigned.locator('[name=receivers][value="'+initial.id+'"]').evaluate(el=>el.closest('details').open=true);await assigned.locator('[name=receivers][value="'+initial.id+'"]').check();await page.getByRole('button',{name:'创建活动',exact:true}).click();await page.locator('dialog').waitFor({state:'hidden'});
  await page.locator('[data-view=overview]').first().click();
  await page.locator('.time-scroll').evaluate(el=>el.scrollLeft=17*68);
  const handle=page.locator('[data-drag-event]').first();await handle.scrollIntoViewIfNeeded();const box=await handle.boundingBox();
  await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.down();await page.mouse.move(box.x+box.width/2+68,box.y+box.height/2,{steps:6});await page.mouse.up();
  await page.getByRole('heading',{name:'确认活动改期'}).waitFor();await page.getByRole('button',{name:'确认并同步日历'}).click();await page.locator('dialog').waitFor({state:'hidden'});
  await page.screenshot({path:'.local/qa/desktop-overview.png',fullPage:true});
  await page.locator('[data-view=calendar]').first().click();await page.screenshot({path:'.local/qa/desktop-calendar.png',fullPage:true});
  await page.locator('nav [data-view=sop]').click();await page.locator('.sop-document').first().waitFor();await page.locator('.sop-document').first().click();await page.locator('.sop-reader').waitFor();await page.locator('[data-close]').click();
  const mobile=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,storageState:await context.storageState()});
  const phone=await mobile.newPage();phone.on('pageerror',e=>errors.push(e.message));await phone.goto(base);await phone.getByRole('heading',{name:'测试负责人，欢迎回来。'}).waitFor();
  await phone.screenshot({path:'.local/qa/mobile-overview.png',fullPage:true});
  assert.ok(await phone.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Mobile viewport must not overflow');
  await phone.locator('[data-create]').click();await phone.screenshot({path:'.local/qa/mobile-event.png',fullPage:true});
  assert.ok(await phone.evaluate(()=>document.querySelector('dialog').scrollWidth<=document.querySelector('dialog').clientWidth+1),'Mobile dialog must not overflow');
  await phone.locator('[data-close]').click();
  await mobile.clearCookies();await mobile.addCookies(await memberContext.cookies());await phone.reload();assert.equal((await phone.evaluate(()=>api('info'))).user?.id,assignee.id,'Mobile uses the member session.');await phone.getByRole('heading',{name:'测试执行成员，欢迎回来。'}).waitFor();
  await phone.locator('[data-view=tasks]').click();await phone.locator('.task-row').filter({has:phone.getByRole('heading',{name:'需求登记',exact:true})}).click();await phone.getByRole('button',{name:'接受任务',exact:true}).click();await phone.locator('dialog').waitFor({state:'hidden'});
  await phone.locator('.task-row').filter({has:phone.getByRole('heading',{name:'需求登记',exact:true})}).click();await phone.getByRole('button',{name:'提交成果',exact:true}).click();
  const help=phone.locator('.check-help summary').first();await help.scrollIntoViewIfNeeded();const helpBox=await help.boundingBox();const touch=await mobile.newCDPSession(phone);
  await touch.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:helpBox.x+10,y:helpBox.y+10}]});await new Promise(r=>setTimeout(r,550));await touch.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
  assert.equal(await phone.locator('.check-help').first().getAttribute('open'),'');await phone.screenshot({path:'.local/qa/mobile-check-help.png',fullPage:true});await phone.locator('[data-close]').click();await phone.locator('[data-view=overview]').first().click();
  await mobile.clearCookies();await mobile.addCookies(await context.cookies());await phone.reload();assert.equal((await phone.evaluate(()=>api('info'))).user?.id,initial.id,'Polling uses the administrator session.');await phone.getByRole('heading',{name:'测试负责人，欢迎回来。'}).waitFor();
  // Automatic polling remains active even while a form is open and does not discard draft input.
  await phone.locator('[data-create]').click();await phone.locator('[name=name]').fill('未提交草稿');
  const polling=phone.waitForResponse(r=>r.url()===base+'/api/state',{timeout:35000});await polling;
  assert.equal(await phone.locator('[name=name]').inputValue(),'未提交草稿');
  assert.deepEqual(errors,[]);await writeFile('.local/qa/browser-result.json',JSON.stringify({passed:true,errors,checks:['initial administrator exclusion','multi-assignee and multi-reviewer','member conflict resume and delivery','admin approval and archive','split points conserve total','gray calendar archive','blank event','custom task','conflict resume','hover help','cloud upload confirmation','link confirmation','reward ledger','save event template','create template','instantiate template','drag reschedule','SOP viewer','mobile layout','30-second poll preserves draft']},null,2));
  console.log('PASS: desktop/mobile interactions, timeline drag, template workflow, submission receipts, rewards, polling and no browser errors.');
}finally{await browser?.close();server.kill();}
