import {spawn} from 'node:child_process';
import {mkdir,writeFile} from 'node:fs/promises';
import {pathToFileURL} from 'node:url';
import assert from 'node:assert/strict';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE?pathToFileURL(process.env.PLAYWRIGHT_MODULE).href:'playwright');
const port=8877,base=`http://127.0.0.1:${port}`;
const server=spawn(process.execPath,['scripts/dev.mjs'],{env:{...process.env,PORT:String(port),DB_PATH:':memory:'},windowsHide:true,stdio:['ignore','pipe','pipe']});
let browser;const errors=[];
try{
  await new Promise((resolve,reject)=>{server.stdout.on('data',b=>{if(b.toString().includes('Local:'))resolve()});server.stderr.on('data',b=>process.stderr.write(b));server.on('error',reject);server.on('exit',code=>reject(Error('Server exited '+code)))});
  browser=await chromium.launch({channel:'msedge',headless:true});
  const context=await browser.newContext({viewport:{width:1440,height:1080}});
  const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));
  await page.goto(base+'/#setup=local-preview-only-setup');
  await page.locator('[name=username]').fill('qa_owner');await page.locator('[name=name]').fill('测试负责人');
  await page.locator('[name=password]').fill('Browser-test-2026!');await page.locator('[name=confirm]').fill('Browser-test-2026!');
  await page.getByRole('button',{name:'创建管理员账号',exact:true}).click();
  await page.getByRole('heading',{name:'测试负责人，欢迎回来。'}).waitFor();
  await page.locator('[data-create]').first().click();
  assert.equal(await page.locator('[name=template]').inputValue(),'blank');
  await page.locator('[name=name]').fill('迎新宣传协作');
  await page.locator('[name=date]').fill('2026-09-20');await page.locator('[name=endDate]').fill('2026-09-23');
  await page.locator('[name=allDay]').uncheck();
  await page.locator('[name=location]').fill('书院报告厅');await page.locator('textarea[name=description]').fill('活动前预写文案，素材精选后完成推送与归档。');
  await page.locator('[name=cloudUrl]').fill('https://example.com/drive');
  await page.locator('.form-section summary').click();await page.locator('[name=rewardPoints]').fill('20');await page.locator('[name=rewardNote]').fill('优秀作品展示');
  await page.getByRole('button',{name:'创建活动',exact:true}).click();
  await page.locator('dialog').waitFor({state:'hidden'});await page.getByText('空白日程 · 尚未派单').waitFor();
  await page.getByRole('button',{name:'＋ 任务',exact:true}).click();await page.locator('[name=name]').fill('摄影与精选照片交付');await page.locator('[name=requirements]').fill('精选 10—15 张照片，注明人物与摄影者。');
  await page.getByRole('button',{name:'添加并派单'}).click();await page.locator('dialog').waitFor({state:'hidden'});
  await page.locator('.flow-step').first().click();await page.getByRole('button',{name:'时间冲突',exact:true}).click();await page.locator('[name=feedback]').fill('课程冲突，稍后确认');await page.getByRole('button',{name:'提交',exact:true}).click();await page.locator('dialog').waitFor({state:'hidden'});
  await page.locator('.flow-step').first().click();await page.getByRole('button',{name:'冲突已解决，恢复接活'}).click();await page.locator('dialog').waitFor({state:'hidden'});
  await page.locator('.flow-step').first().click();await page.getByRole('button',{name:'提交成果',exact:true}).click();
  await page.locator('.check-help summary').first().hover();assert.equal(await page.locator('.check-popover').first().isVisible(),true);
  await page.locator('.check-help summary').first().click();await page.locator('[name=check0]').check();await page.locator('[name=check1]').check();await page.locator('[name=submission]').fill('精选照片已上传，已按日期及场景命名，摄影署名见文件说明。');
  assert.equal(await page.locator('[name=uploadConfirmed]').isDisabled(),true);
  // Avoid requesting the sample cloud URL, while exercising the click and confirmation controls.
  await context.route('https://example.com/**',route=>route.fulfill({status:200,body:'QA cloud placeholder'}));
  const popupWait=page.waitForEvent('popup');await page.locator('[data-open-upload]').click();const popup=await popupWait;await popup.close();
  await page.locator('[name=uploadConfirmed]').check();await page.locator('[name=link]').fill('https://example.com/results');await page.locator('[name=linkConfirmed]').check();
  await mkdir('.local/qa',{recursive:true});await page.screenshot({path:'.local/qa/desktop-submit.png',fullPage:true});
  await page.getByRole('button',{name:'提交给 测试负责人'}).click();await page.locator('dialog').waitFor({state:'hidden'});
  await page.locator('.flow-step').first().click();await page.getByRole('button',{name:'验收通过'}).click();await page.locator('dialog').waitFor({state:'hidden'});
  await page.locator('[data-view=rewards]').click();await page.getByText('+20',{exact:true}).waitFor();
  await page.locator('[data-view=activities]').click();await page.getByRole('button',{name:'活动详情',exact:true}).click();await page.getByRole('button',{name:'保存为模板'}).click();await page.getByRole('button',{name:'保存模板',exact:true}).click();await page.locator('dialog').waitFor({state:'hidden'});
  await page.locator('[data-view=templates]').click();await page.getByRole('heading',{name:'迎新宣传协作流程'}).waitFor();
  await page.getByRole('button',{name:'＋ 创建模板'}).click();await page.locator('[name=name]').fill('新建模板测试');await page.locator('[data-add-step]').click();await page.locator('[data-key=name]').fill('需求登记');await page.locator('[data-key=requirements]').fill('登记需求方与交付形式');await page.getByRole('button',{name:'保存模板',exact:true}).click();await page.locator('dialog').waitFor({state:'hidden'});
  await page.locator('.template-card').filter({has:page.getByRole('heading',{name:'新建模板测试'})}).getByRole('button',{name:'使用模板'}).click();
  await page.locator('[name=name]').fill('从模板创建的活动');await page.getByRole('button',{name:'创建活动',exact:true}).click();await page.locator('dialog').waitFor({state:'hidden'});
  await page.locator('[data-view=overview]').first().click();
  await page.locator('.time-scroll').evaluate(el=>el.scrollLeft=17*68);
  const handle=page.locator('[data-drag-event]').first();await handle.scrollIntoViewIfNeeded();const box=await handle.boundingBox();
  await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.down();await page.mouse.move(box.x+box.width/2+68,box.y+box.height/2,{steps:6});await page.mouse.up();
  await page.getByRole('heading',{name:'确认活动改期'}).waitFor();await page.getByRole('button',{name:'确认并同步日历'}).click();await page.locator('dialog').waitFor({state:'hidden'});
  await page.screenshot({path:'.local/qa/desktop-overview.png',fullPage:true});
  await page.locator('[data-view=calendar]').first().click();await page.screenshot({path:'.local/qa/desktop-calendar.png',fullPage:true});
  await page.locator('[data-view=sop]').click();await page.locator('.sop-document').first().waitFor();await page.locator('.sop-document').first().click();await page.locator('.sop-reader').waitFor();await page.locator('[data-close]').click();
  const mobile=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,storageState:await context.storageState()});
  const phone=await mobile.newPage();phone.on('pageerror',e=>errors.push(e.message));await phone.goto(base);await phone.getByRole('heading',{name:'测试负责人，欢迎回来。'}).waitFor();
  await phone.screenshot({path:'.local/qa/mobile-overview.png',fullPage:true});
  assert.ok(await phone.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Mobile viewport must not overflow');
  await phone.locator('[data-create]').click();await phone.screenshot({path:'.local/qa/mobile-event.png',fullPage:true});
  assert.ok(await phone.evaluate(()=>document.querySelector('dialog').scrollWidth<=document.querySelector('dialog').clientWidth+1),'Mobile dialog must not overflow');
  await phone.locator('[data-close]').click();
  await phone.locator('[data-view=tasks]').click();await phone.locator('.task-row').filter({has:phone.getByRole('heading',{name:'需求登记',exact:true})}).click();await phone.getByRole('button',{name:'接受任务',exact:true}).click();await phone.locator('dialog').waitFor({state:'hidden'});
  await phone.locator('.task-row').filter({has:phone.getByRole('heading',{name:'需求登记',exact:true})}).click();await phone.getByRole('button',{name:'提交成果',exact:true}).click();
  const help=phone.locator('.check-help summary').first();await help.scrollIntoViewIfNeeded();const helpBox=await help.boundingBox();const touch=await mobile.newCDPSession(phone);
  await touch.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:helpBox.x+10,y:helpBox.y+10}]});await new Promise(r=>setTimeout(r,550));await touch.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
  assert.equal(await phone.locator('.check-help').first().getAttribute('open'),'');await phone.screenshot({path:'.local/qa/mobile-check-help.png',fullPage:true});await phone.locator('[data-close]').click();await phone.locator('[data-view=overview]').first().click();
  // Automatic polling remains active even while a form is open and does not discard draft input.
  await phone.locator('[data-create]').click();await phone.locator('[name=name]').fill('未提交草稿');
  const polling=phone.waitForResponse(r=>r.url()===base+'/api/state',{timeout:35000});await polling;
  assert.equal(await phone.locator('[name=name]').inputValue(),'未提交草稿');
  assert.deepEqual(errors,[]);await writeFile('.local/qa/browser-result.json',JSON.stringify({passed:true,errors,checks:['blank event','custom task','conflict resume','hover help','cloud upload confirmation','link confirmation','reward ledger','save event template','create template','instantiate template','drag reschedule','SOP viewer','mobile layout','30-second poll preserves draft']},null,2));
  console.log('PASS: desktop/mobile interactions, timeline drag, template workflow, submission receipts, rewards, polling and no browser errors.');
}finally{await browser?.close();server.kill();}
