import {readFile,writeFile,mkdir,readdir} from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
process.chdir(fileURLToPath(new URL('..',import.meta.url)));
import {build} from 'esbuild';
const files={'/index.html':'text/html; charset=utf-8','/app.js':'text/javascript; charset=utf-8','/style.css':'text/css; charset=utf-8'};
const release='v1.0.1';
const assets={};for(const [file,type] of Object.entries(files))assets[file]={type,body:await readFile('src'+file,'utf8')};
assets['/app.js'].body=await readFile('../miniprogram/utils/task-model.js','utf8').then(s=>s.replace('module.exports=','const WorkspaceModel='))+'\n'+assets['/app.js'].body;
assets['/app.js'].body+='\n'+await readFile('src/enhancements.js','utf8')+'\n'+await readFile('src/community.js','utf8')+'\n'+await readFile('src/workspace-ui.js','utf8');
assets['/style.css'].body+='\n'+await readFile('src/v2.css','utf8')+'\n'+await readFile('src/community.css','utf8')+'\n'+await readFile('src/workspace-ui.css','utf8');
assets['/index.html'].body=assets['/index.html'].body.replace(/<link rel="icon"[^>]*>/,'<link rel="icon" type="image/png" href="/brand/emblem.png">').replace('#183e36','#ff861b');
assets['/index.html'].body=assets['/index.html'].body.replace('href="style.css"','href="/style.css?v='+release+'"').replace('src="app.js"','src="/app.js?v='+release+'"');
for(const file of ['emblem.png','wordmark.png'])assets['/brand/'+file]={type:'image/png',base64:true,body:(await readFile('src/brand/'+file)).toString('base64')};
const images=(await readdir('sop/screenshots').catch(()=>[])).filter(f=>f.endsWith('.png')).sort();
for(const file of images)assets['/guide/'+encodeURIComponent(file)]={type:'image/png',base64:true,body:(await readFile('sop/screenshots/'+file)).toString('base64')};
const documents=[{path:'工作台操作手册.md',title:'工作台操作手册 · 图解',content:await readFile('sop/工作台操作手册.md','utf8'),images:images.map(f=>({url:'/guide/'+encodeURIComponent(f),caption:f.replace(/^\d+-/,'').replace('.png','')}))},{path:'知识库.md',title:'知识库',content:await readFile('sop/知识库.md','utf8')}];assets['/sop-docs.json']={type:'application/json; charset=utf-8',body:JSON.stringify(documents)};
await writeFile('src/assets.generated.js','export default '+JSON.stringify(assets));
await mkdir('dist/server',{recursive:true});
await build({absWorkingDir:process.cwd(),entryPoints:['./src/worker.js'],outfile:'dist/server/index.js',bundle:true,format:'esm',platform:'browser',target:'es2022',minify:true});
console.log('Worker and embedded assets built.');
