import assert from 'node:assert/strict';
import {readFile,readdir} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {database} from './local-db.mjs';
import worker from '../dist/server/index.js';
import {anonymousAddress,recordRequest,readStatistics,pruneTelemetry,maintainStatistics} from '../src/observability.js';
const DB=database();for(const f of(await readdir('drizzle')).filter(f=>f.endsWith('.sql')).sort())DB.sqlite.exec(await readFile('drizzle/'+f,'utf8'));
assert.equal(anonymousAddress('198.51.100.77').masked,'198.51.100.0/24');assert.equal(anonymousAddress('2001:db8:abcd:0042::1').masked,'2001:0db8:abcd::/48');assert.equal(anonymousAddress('127.0.0.1').masked,'本机 / 内网');assert.equal(anonymousAddress('1.2.3.999').masked,'未知来源');
const privateMarker='PRIVATE_COOKIE_PASSWORD_TOKEN_QUERY',origin='https://local.test',env={DB,TELEMETRY_CONTEXT:{source:'cloudflare',ip:'198.51.100.77',country:'CN'}};
await recordRequest(new Request(origin+'/?reset='+privateMarker,{headers:{Cookie:privateMarker}}),new Response('',{status:200}),env);
await recordRequest(new Request(origin+'/.env?'+privateMarker),new Response('',{status:404}),env);
await recordRequest(new Request(origin+'/api/login',{method:'POST',headers:{Origin:origin,'X-FR-Request':'1'},body:JSON.stringify({password:privateMarker})}),new Response('',{status:423,headers:{'X-FR-Security':'PASSWORD_LOCKED'}}),env);
await recordRequest(new Request(origin+'/api/tasks/action',{method:'POST',headers:{Origin:origin,'X-FR-Request':'1'},body:privateMarker}),new Response('',{status:500}),{...env,TELEMETRY_CONTEXT:{source:'unknown',ip:'2001:db8:abcd:0042::1',country:'US'}});
let stats=await readStatistics(DB);assert.equal(stats.summary.pageviews,1);assert.equal(stats.summary.risks,2);assert.equal(stats.summary.failures,1);assert.equal(stats.summary.visitorDays,2);assert.ok(stats.countries.some(x=>x.country==='CN'));assert.ok(stats.countries.some(x=>x.country==='unknown'));assert.ok(!stats.countries.some(x=>x.country==='US'),'Untrusted location is never plotted.');assert.ok(stats.codes.some(x=>x.code==='PASSWORD_LOCKED'));const dump=JSON.stringify(stats);assert.ok(!dump.includes(privateMarker)&&!dump.includes('198.51.100.77')&&!dump.includes('2001:db8:abcd:0042::1')&&!dump.includes('"fingerprint":')&&!dump.includes('"salt":'));
const columns=DB.sqlite.prepare('SELECT masked_ip,fingerprint FROM site_visitors').all();assert.equal(columns[0].fingerprint.length,64);assert.ok(columns.every(x=>!JSON.stringify(x).includes('198.51.100.77')));
// Retention and row limits protect long-running deployments.
DB.sqlite.prepare('UPDATE site_request_events SET time=? WHERE code=?').run(Date.now()-16*86400000,'SENSITIVE_PATH_PROBE');await pruneTelemetry(DB,Date.now(),true);assert.ok(!(await readStatistics(DB)).events.some(x=>x.code==='SENSITIVE_PATH_PROBE'));
DB.sqlite.exec('BEGIN');const insert=DB.sqlite.prepare('INSERT INTO site_request_events (id,time,route,method,status,code,risk,duration,masked_ip,country) VALUES (?,?,?,?,?,?,?,?,?,?)');for(let i=0;i<1210;i++)insert.run('test-'+i,Date.now()+i,'api:state','GET',500,'REQUEST_FAILED',0,1,'未知来源','unknown');DB.sqlite.exec('COMMIT');await pruneTelemetry(DB,Date.now(),true);assert.equal(DB.sqlite.prepare('SELECT COUNT(*) AS n FROM site_request_events').get().n,1200);
const authEnv={DB,BOOTSTRAP_HASH:createHash('sha256').update('stats-only-test').digest('hex')};async function api(path,data,cookie='',status=200){const r=await worker.fetch(new Request(origin+'/api/'+path,{method:data?'POST':'GET',headers:{Origin:origin,'X-FR-Request':'1','Content-Type':'application/json',Cookie:cookie},body:data?JSON.stringify(data):undefined}),authEnv);const b=await r.json();assert.equal(r.status,status,path+':'+JSON.stringify(b));return {body:b,cookie:r.headers.get('set-cookie')?.split(';')[0]||cookie}}
await api('stats',null,'',401);const owner=await api('setup',{token:'stats-only-test',username:'stats_owner',name:'Synthetic',dept:'办公室',password:'Stats-password-47-strong'});const member=await api('register',{username:'stats_member',name:'Synthetic member',dept:'办公室',password:'Stats-password-47-strong'});const id=(await api('members',null,owner.cookie)).body.members.find(u=>u.username==='stats_member').id;await api('members/update',{id,dept:'办公室',role:'member',status:'active'},owner.cookie);const active=await api('login',{username:'stats_member',password:'Stats-password-47-strong'});await api('stats',null,active.cookie,403);await api('stats/maintenance',{action:'clear'},active.cookie,403);
const before=DB.sqlite.prepare('SELECT COUNT(*) AS n FROM users').get().n;await api('stats/maintenance',{action:'clear'},owner.cookie);stats=await readStatistics(DB);assert.equal(stats.summary.requests,0);assert.equal(DB.sqlite.prepare('SELECT COUNT(*) AS n FROM users').get().n,before);DB.sqlite.close();console.log('PASS private statistics: IP masks, trusted country map, risk/error categories, no bodies/tokens/accounts, bounded retention, admin-only access, safe maintenance.');
