import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createRequire} from 'node:module';
import {webcrypto} from 'node:crypto';
import vm from 'node:vm';
const require=createRequire(import.meta.url),source=readFileSync(new URL('../src/presence-v105.js',import.meta.url),'utf8');
const people=[{id:'owner',name:'演示管理员',username:'demo_owner',role:'admin',owner:true,dept:'',status:'active',online:true},{id:'live',name:'演示伙伴一',username:'demo_live',role:'member',dept:'办公室',status:'active',online:true},{id:'away',name:'演示伙伴二',username:'demo_away',role:'member',dept:'办公室',status:'active',online:false}];
const flush=async()=>{for(let i=0;i<12;i++)await Promise.resolve()};
function statusElement(id){const text={textContent:''},classes=new Set();return {dataset:{presenceId:id},classList:{toggle(k,value){value?classes.add(k):classes.delete(k)}},classes,text,querySelector:()=>text}}
function web(){
 let now=100000,timerId=0,pending,readCount=0,renderCount=0,readonly=false,next=structuredClone(people);const listeners={},timers=new Map(),calls=[],elements=people.map(p=>statusElement(p.id));
 class DateMock extends Date{static now(){return now}}
 const account=structuredClone(people[0]),node={id:'person:live',kind:'person',person:structuredClone(people[1]),x:250,y:180,vx:12,vy:8};
 const context={crypto:webcrypto,Date:DateMock,AbortController,JSON,Map,Set,Array,String,Number,document:{hidden:false,querySelector:()=>null,querySelectorAll:()=>elements,addEventListener:(name,fn)=>listeners[name]=fn},navigator:{onLine:true},window:{WorkbenchRecovery:{isReadOnly:()=>readonly},addEventListener:(name,fn)=>listeners[name]=fn},user:account,state:{people:structuredClone(people)},members:structuredClone(people),view:'members',orgScene:{account:account.id,nodes:[node]},personPinned:'',orgWords:(zh,en)=>zh,
 setTimeout:()=>++timerId,clearTimeout(){},setInterval:fn=>{timers.set(++timerId,fn);return timerId},clearInterval:id=>timers.delete(id),render:()=>renderCount++,auth(){},api:async path=>{assert.equal(path,'members');readCount++;return {members:structuredClone(next)}},
 fetch:async (url,options)=>{assert.equal(url,'/api/presence');assert.equal(options.credentials,'same-origin');assert.equal(options.headers['X-FR-Request'],'1');const body=JSON.parse(options.body);assert.deepEqual(Object.keys(body).sort(),['active','client','seq']);assert.match(body.client,/^[a-zA-Z0-9-]{16,64}$/);calls.push({body,keepalive:options.keepalive});return pending?await pending:{ok:true,status:200}}
 };vm.createContext(context);vm.runInContext(source,context);
 return {context,calls,elements,timers,node,advance(ms){now+=ms;for(const fn of [...timers.values()])fn()},event(name){listeners[name]?.()},next(value){next=value},readonly(value){readonly=value},pending(p){pending=p},get readCount(){return readCount},get renderCount(){return renderCount}};
}
const page=web();await flush();assert.equal(page.calls.length,1);assert.equal(page.calls[0].body.active,true);assert.equal(page.readCount,1);assert.equal(page.elements[1].text.textContent,'在线');assert.equal(page.elements[2].text.textContent,'离线');assert.equal(page.node.vx,12);assert.equal(page.renderCount,0,'Presence-only updates do not rerender the moving graph');
const sameNode=page.node;page.next(people.map(p=>({...p,online:p.id==='away'})));page.advance(25000);await flush();assert.equal(page.calls.length,2);assert.equal(page.elements[1].text.textContent,'离线');assert.equal(page.elements[2].text.textContent,'在线');assert.equal(page.context.orgScene.nodes[0],sameNode);assert.deepEqual({x:page.node.x,y:page.node.y,vx:page.node.vx,vy:page.node.vy},{x:250,y:180,vx:12,vy:8},'Status changes retain node position and velocity');
page.context.document.hidden=true;page.event('visibilitychange');await flush();assert.equal(page.calls.at(-1).body.active,false);assert.equal(page.calls.at(-1).keepalive,true);assert.equal(page.timers.size,0);const hiddenCount=page.calls.length;page.context.render();page.advance(30000);await flush();assert.equal(page.calls.length,hiddenCount,'Background refresh cannot revive online status');
page.context.document.hidden=false;page.event('visibilitychange');await flush();assert.equal(page.calls.at(-1).body.active,true);assert.equal(page.timers.size,1);assert.ok(page.calls.every((c,i)=>i===0||c.body.seq>page.calls[i-1].body.seq),'Sequence increases across foreground/background races');
page.event('pagehide');await flush();assert.equal(page.calls.at(-1).body.active,false);assert.equal(page.timers.size,0);page.event('pageshow');await flush();assert.equal(page.calls.at(-1).body.active,true);page.context.navigator.onLine=false;page.event('offline');await flush();assert.equal(page.calls.at(-1).body.active,false);page.context.navigator.onLine=true;page.event('online');await flush();assert.equal(page.calls.at(-1).body.active,true);
page.readonly(true);const beforeReadonly=page.calls.length;page.advance(25000);await flush();assert.equal(page.calls.length,beforeReadonly,'Cosmetic heartbeat respects local read-only state without invoking mutation recovery');page.readonly(false);page.context.user=null;page.context.auth('login');const beforeAuth=page.calls.length;page.advance(100000);await flush();assert.equal(page.calls.length,beforeAuth);assert.equal(page.timers.size,0,'Sign-out stops heartbeats');
const stale=web();await flush();let release;stale.pending(new Promise(r=>release=r));stale.advance(25000);stale.context.user={...people[0],id:'new-account',online:false};stale.context.auth('login');release({ok:true,status:200});await flush();assert.equal(stale.context.user.online,false,'A late heartbeat cannot mutate another signed-in account');assert.equal(stale.calls.length,2);
const delayed=web();await flush();let complete;delayed.context.api=async()=>await new Promise(resolve=>complete=resolve);delayed.advance(25000);await flush();delayed.context.user={...people[0],id:'next-account',online:false};delayed.context.auth('login');complete({members:people.map(p=>({...p,name:'过期资料'}))});await flush();assert.ok(delayed.context.members.every(p=>p.name!=='过期资料'),'A late member response is discarded on account change');

const O=require('../../miniprogram/utils/organization.js'),nativeSource=readFileSync(new URL('../../miniprogram/pages/members/index.js',import.meta.url),'utf8');let native,nextMembers=structuredClone(people),token='demo-token';
const V={roles:{admin:'管理员',manager:'部门负责人',member:'成员'},depts:O.depts,page:spec=>spec,api:{token:()=>token,call:async path=>{assert.equal(path,'members');return {members:structuredClone(nextMembers),reviews:[]}}}},UI={language:()=> 'zh-CN',t:s=>s},R={markSuccess(){},capture(){}};
vm.runInNewContext(nativeSource,{require:name=>name.endsWith('/view')?V:name.endsWith('/organization')?O:name.endsWith('/interface')?UI:R,Page:p=>native=p,wx:{},setInterval:()=>1,clearInterval(){},Date});native.data=structuredClone(native.data);native.setData=function(patch,callback){Object.assign(this.data,patch);callback?.()};native.user=structuredClone(people[0]);native.data.expanded=['办公室'];await native.load();assert.equal(native.members.find(p=>p.id==='live').onlineLabel,'在线');assert.equal(native.data.orgNodes.find(p=>p.id==='person:away').onlineLabel,'离线');native.person({currentTarget:{dataset:{id:'live'}}});assert.equal(native.data.selectedPerson.online,true);
const child=O.node(native.orgScene,'person:live');child.vx=22;nextMembers=nextMembers.map(p=>({...p,online:p.id==='away'}));await native.load();assert.equal(native.data.selectedPerson.onlineLabel,'离线');assert.equal(native.data.orgNodes.find(p=>p.id==='person:away').onlineLabel,'在线');assert.equal(O.node(native.orgScene,'person:live'),child);assert.equal(child.vx,22,'Native status refresh retains physical node velocity');
UI.language=()=> 'en';await native.load();assert.equal(native.members.find(p=>p.id==='away').onlineLabel,'Online');assert.equal(native.members.find(p=>p.id==='live').onlineLabel,'Offline');
const nativeWxml=readFileSync(new URL('../../miniprogram/pages/members/index.wxml',import.meta.url),'utf8');assert.ok(nativeWxml.includes('{{item.onlineLabel}}')&&nativeWxml.includes('{{person.onlineLabel}}')&&nativeWxml.includes('{{selectedPerson.onlineLabel}}'),'Bubbles, member rows and profile show textual status');
const appSource=readFileSync(new URL('../../miniprogram/app.js',import.meta.url),'utf8');
function nativeApp(scene=1001){
 let app,now=100000,timerId=0,subscriber,session='fixture-session',tokenReads=0,refreshes=0,bootRepairs=0,backendOnline=false;const timers=new Map(),calls=[],routes=[],snapshot={user:{id:'review-admin',online:false},settings:{}};
 class DateMock extends Date{static now(){return now}}
 const api={token(){tokenReads++;return session},config:()=>({pollMs:30000}),subscribe(fn){subscriber=fn;return ()=>{}},getState:()=>snapshot,call:async(path,data)=>{calls.push({path,data});if(path==='presence'){backendOnline=data.active;return {online:backendOnline}}return {user:{status:'active'}}},refresh:async()=>{refreshes++;snapshot.user.online=backendOnline;return snapshot},clear(){session=''}};
 vm.runInNewContext(appSource,{App:p=>app=p,Date:DateMock,Math,wx:{getLaunchOptionsSync:()=>({scene}),reLaunch:o=>routes.push(o.url)},require:name=>name.includes('recovery')?{bootRepair(){bootRepairs++},capture(){},noteRecovery(){}}:api,setInterval:(fn,ms)=>{timers.set(++timerId,{fn,ms});return timerId},clearInterval:id=>timers.delete(id)});
 return {app,api,calls,timers,routes,notify(){subscriber?.(snapshot)},advance(ms){now+=ms;for(const value of [...timers.values()])value.fn()},get tokenReads(){return tokenReads},get refreshes(){return refreshes},get bootRepairs(){return bootRepairs},clear(){session=''}};
}
const app=nativeApp();app.app.onLaunch({scene:1001});await flush();assert.equal(app.bootRepairs,1);app.notify();await flush();assert.equal(app.calls.filter(c=>c.path==='presence').length,1,'The first signed-in foreground snapshot sends one heartbeat');assert.equal(app.calls.at(-1).data.active,true);assert.equal(app.refreshes,2,'An initially stale own status refreshes once after an acknowledged heartbeat');
app.app.onShow({scene:1001});await flush();assert.equal(app.timers.size,2);const initialClient=app.calls.filter(c=>c.path==='presence')[0].data.client;app.advance(25000);await flush();assert.ok(app.calls.filter(c=>c.path==='presence').every(c=>c.data.client===initialClient));const activeCalls=app.calls.filter(c=>c.path==='presence');assert.ok(activeCalls.every((c,i)=>i===0||c.data.seq>activeCalls[i-1].data.seq));app.app.onHide();await flush();assert.equal(app.calls.at(-1).data.active,false);assert.equal(app.timers.size,0);const countBeforeBackground=app.calls.length;app.notify();app.advance(50000);await flush();assert.equal(app.calls.length,countBeforeBackground,'Background app state updates never announce active presence');app.app.onShow({scene:1001});await flush();assert.equal(app.calls.at(-1).data.active,true);app.clear();const beforeSignOut=app.calls.length;app.app.onHide();await flush();assert.equal(app.calls.length,beforeSignOut,'Logged-out app does not issue a private presence request');
const preview=nativeApp(1154);preview.app.onLaunch({scene:1154,query:{setup:'PRIVATE_SETUP'}});preview.app.onShow({scene:1154});preview.app.onHide();preview.app.sendPresence(true);preview.app.sendPresence(false);preview.app.hydrate();preview.app.startPolling();preview.app.onPageNotFound();await flush();assert.equal(preview.tokenReads,0,'Public scene 1154 never reads saved account credentials, including recovery and missing-page paths');assert.equal(preview.calls.length,0);assert.equal(preview.timers.size,0);assert.equal(preview.bootRepairs,0);assert.equal(preview.routes.length,0,'Public single-page preview avoids unsupported route APIs');assert.equal(preview.app.pendingAuth,undefined);
const localization=require('../../miniprogram/utils/localization.js'),chrome=[],displayWrites=[],navigationErrors=[],visiblePage={route:'pages/calendar/index'},hiddenPage={route:'pages/profile/index'};let currentPages=()=>[hiddenPage,visiblePage];
const navigationModule={exports:{}};vm.runInNewContext(readFileSync(new URL('../../miniprogram/utils/interface.js',import.meta.url),'utf8'),{module:navigationModule,getCurrentPages:()=>currentPages(),wx:Object.fromEntries(['setNavigationBarTitle','setNavigationBarColor','setBackgroundColor','setTabBarStyle','setTabBarItem'].map(name=>[name,value=>chrome.push({name,value})])),require:name=>name.includes('localization')?localization:name.includes('recovery')?{normalizeSettings:s=>s,safeWrite:(key,value)=>displayWrites.push({key,value}),saveDisplay:settings=>displayWrites.push({settings}),capture:(_,type)=>navigationErrors.push(type)}:{getState:()=>null}});
const navigationState={settings:{language:'en',themeColor:'#167d49'},dark:false,_localReadOnly:true};navigationModule.exports.navigation(hiddenPage,navigationState);assert.equal(chrome.length,0);assert.equal(displayWrites.length,0,'Hidden-page subscriptions cannot overwrite current navigation or display state');navigationModule.exports.navigation(visiblePage,navigationState);assert.equal(chrome.find(c=>c.name==='setNavigationBarTitle').value.title,localization.translate('日历安排','en')+' · Read only');assert.equal(chrome.filter(c=>c.name==='setTabBarItem').length,4);assert.equal(displayWrites.length,2,'The current top page owns native title, theme and tab labels');const beforeNavigationError=chrome.length;currentPages=()=>{throw Error('Fixture page stack unavailable')};navigationModule.exports.navigation(hiddenPage,navigationState);assert.equal(chrome.length,beforeNavigationError);assert.deepEqual(navigationErrors,['render'],'A missing page stack records only a fixed local category and leaves native chrome untouched');
console.log('PASS presence UI: active-only web/native heartbeat, tab/device sequence, fast offline, read-only isolation, account guards, text labels, stable physics, English, public scene 1154 zero auth/private requests, and visible-page-only native navigation.');
