import assert from 'node:assert/strict';import {readFile,readdir} from 'node:fs/promises';import {createHash} from 'node:crypto';import worker from '../dist/server/index.js';import {database} from './local-db.mjs';
const DB=database();for(const f of (await readdir('drizzle')).filter(x=>x.endsWith('.sql')))DB.sqlite.exec(await readFile('drizzle/'+f,'utf8'));
const env={DB,BOOTSTRAP_HASH:createHash('sha256').update('test-initialization-token').digest('hex')},origin='https://local.test';let ip=0;
async function call(path,data,cookie='',expected=200,overrides={}){const headers={'Origin':origin,'CF-Connecting-IP':'127.0.0.'+(++ip),'X-FR-Request':'1',...overrides};if(cookie)headers.Cookie=cookie;if(data)headers['Content-Type']='application/json';const r=await worker.fetch(new Request(origin+'/api/'+path,{method:data?'POST':'GET',headers,body:data?JSON.stringify(data):undefined}),env);const b=await r.json();assert.equal(r.status,expected,`${path}: ${JSON.stringify(b)}`);return {body:b,cookie:r.headers.get('set-cookie')?.split(';')[0]||cookie}}
const password='Test-password-47-strong';
await call('state',null,'',401);
await call('setup',{token:'wrong',username:'owner',name:'负责人',dept:'办公室',password},'',403);
let owner=await call('setup',{token:'test-initialization-token',username:'owner',name:'负责人',dept:'办公室',password});assert.ok(owner.cookie.includes('fr_session_v2='));
await call('setup',{token:'test-initialization-token',username:'owner2',name:'非法管理员',dept:'办公室',password},'',409);
let applicant=await call('register',{username:'photographer',name:'摄影成员',dept:'视觉传达部',password});await call('state',null,applicant.cookie,403);
const list=(await call('members',null,owner.cookie)).body.members;const applicantId=list.find(x=>x.username==='photographer').id;
await call('members/update',{id:applicantId,dept:'视觉传达部',role:'member',status:'active'},owner.cookie);await call('state',null,applicant.cookie,401);
applicant=await call('login',{username:'photographer',password});await call('members',null,applicant.cookie,403);await call('invite',{dept:'视觉传达部',role:'member'},applicant.cookie,403);
const invite=(await call('invite',{dept:'新媒体运营部',role:'manager'},owner.cookie)).body.token;
let editor=await call('register',{username:'editor',name:'新媒体负责人',dept:'办公室',password,invite});let editorInfo=(await call('info',null,editor.cookie)).body.user;assert.equal(editorInfo.dept,'新媒体运营部');assert.equal(editorInfo.role,'manager');
await call('register',{username:'second-editor',name:'重复邀请',dept:'办公室',password,invite},'',400);
await call('invite',{dept:'办公室',role:'manager'},editor.cookie,403);
await call('members/update',{id:applicantId,dept:'新媒体运营部',role:'admin',status:'active'},editor.cookie,403);
await call('events/create',{name:'测试典礼',date:'2026-10-12',location:'书院',template:'ceremony',visual:applicantId,editor:editorInfo.id},applicant.cookie,403);
const event=(await call('events/create',{name:'测试典礼',date:'2026-10-12',location:'书院',template:'ceremony',visual:applicantId,editor:editorInfo.id},owner.cookie)).body.id;
const photo=event+'-1',select=event+'-2',copy=event+'-0',publish=event+'-3';
await call('tasks/action',{id:photo,action:'accept'},editor.cookie,403);
await call('tasks/action',{id:select,action:'accept'},applicant.cookie,403);
await call('tasks/action',{id:photo,action:'accept'},applicant.cookie);
await call('tasks/action',{id:photo,action:'submit',submission:'照片完成',checked:[false,true]},applicant.cookie,400);
await call('tasks/action',{id:photo,action:'submit',submission:'照片完成',checked:[true,true],link:'javascript:alert(1)'},applicant.cookie,400);
await call('tasks/action',{id:photo,action:'submit',submission:'照片完成',checked:[true,true],link:'https://example.com/material',linkConfirmed:true},applicant.cookie);
await call('tasks/action',{id:photo,action:'approve'},applicant.cookie,403);
await call('tasks/action',{id:photo,action:'approve'},owner.cookie);
assert.equal((await call('state',null,applicant.cookie)).body.tasks.find(x=>x.id===select).status,'pending');
await call('tasks/action',{id:select,action:'accept'},applicant.cookie);
await call('tasks/action',{id:select,action:'submit',submission:'精选照片',checked:[true,true]},applicant.cookie);
await call('tasks/action',{id:select,action:'approve'},editor.cookie);
await call('tasks/action',{id:copy,action:'accept'},editor.cookie);
await call('tasks/action',{id:copy,action:'submit',submission:'文案草稿',checked:[true,true]},editor.cookie);
await call('tasks/action',{id:copy,action:'approve'},owner.cookie);
assert.equal((await call('state',null,editor.cookie)).body.tasks.find(x=>x.id===publish).status,'pending');
await call('events/reschedule',{id:event,date:'2026-10-13'},editor.cookie,403);
await call('events/reschedule',{id:event,date:'2026-10-13'},owner.cookie);
let st=(await call('state',null,owner.cookie)).body;assert.ok(st.tasks.find(t=>t.id===publish).due.startsWith('2026-10-15'));assert.ok(st.tasks.find(t=>t.id===photo).due.startsWith('2026-10-12'));
// Blank events, reusable templates, receipt verification, recovery and exactly-once rewards.
const blank=(await call('events/create',{name:'自由日程',date:'2026-09-21',endDate:'2026-09-22',allDay:false,startTime:'09:00',endTime:'17:00',template:'blank',rewardPoints:25,rewardNote:'作品展示'},owner.cookie)).body.id;
assert.equal((await call('state',null,owner.cookie)).body.tasks.filter(t=>t.event===blank).length,0);
await call('events/create',{name:'无效时间',date:'2026-09-21',allDay:false,startTime:'18:00',endTime:'17:00'},owner.cookie,400);
await call('events/update',{id:blank,cloudUrl:'javascript:alert(1)'},owner.cookie,400);
await call('events/update',{id:blank,cloudUrl:'https://example.com/upload'},applicant.cookie,403);
await call('events/update',{id:blank,cloudUrl:'https://example.com/upload'},owner.cookie);
const custom=(await call('tasks/create',{event:blank,name:'自由拍摄任务',owner:applicantId,receiver:editorInfo.id,due:'2026-09-22T17:00',requirements:'精选照片与署名'},owner.cookie)).body.id;
await call('tasks/create',{event:blank,name:'越权派单',owner:applicantId,receiver:editorInfo.id,due:'2026-09-22T17:00',requirements:'照片'},applicant.cookie,403);
assert.equal((await call('state',null,applicant.cookie)).body.events.find(e=>e.id===blank).cloudUrl,'https://example.com/upload');
await call('tasks/action',{id:custom,action:'conflict',feedback:'上课冲突'},applicant.cookie);
await call('tasks/action',{id:custom,action:'resume'},editor.cookie,403);
await call('tasks/action',{id:custom,action:'resume'},applicant.cookie);
await call('tasks/action',{id:custom,action:'submit',submission:'完成',checked:[true,true]},applicant.cookie,400);
await call('tasks/action',{id:custom,action:'submit',submission:'完成',checked:[true,true],uploadConfirmed:true,uploadUrl:'https://example.com/old'},applicant.cookie,400);
await call('tasks/action',{id:custom,action:'submit',submission:'完成',checked:[true,true],uploadConfirmed:true,uploadUrl:'https://example.com/upload',link:'https://example.com/result'},applicant.cookie,400);
const submission={id:custom,action:'submit',submission:'已完成并上传',checked:[true,true],uploadConfirmed:true,uploadUrl:'https://example.com/upload',link:'https://example.com/result',linkConfirmed:true};
await call('tasks/action',submission,applicant.cookie);
await call('tasks/action',{id:custom,action:'reject',feedback:'请补充署名'},editor.cookie);
await call('tasks/action',{id:custom,action:'conflict',feedback:'临时课程'},applicant.cookie);
await call('tasks/action',{id:custom,action:'resume'},applicant.cookie);
let resumed=(await call('state',null,applicant.cookie)).body.tasks.find(t=>t.id===custom);assert.equal(resumed.status,'revise');assert.equal(resumed.feedback,'请补充署名');
await call('tasks/action',submission,applicant.cookie);
await call('tasks/action',{id:custom,action:'approve'},editor.cookie);
await call('tasks/action',{id:custom,action:'approve'},editor.cookie,403);
let ledger=(await call('state',null,applicant.cookie)).body.ledger;assert.equal(ledger.filter(x=>x.task===custom).length,1);assert.equal(ledger.find(x=>x.task===custom).points,25);
assert.equal((await call('state',null,editor.cookie)).body.ledger.some(x=>x.task===custom),false);
await call('tasks/action',{id:custom,action:'assign',owner:editorInfo.id,receiver:applicantId,due:'2026-09-22T18:00',requirements:'改变奖励',rewardPoints:99},owner.cookie,403);
await call('events/reschedule',{id:blank,date:'2026-09-24'},owner.cookie);
const afterMove=(await call('state',null,owner.cookie)).body;assert.equal(afterMove.events.find(e=>e.id===blank).endDate,'2026-09-25');assert.equal(afterMove.tasks.find(t=>t.id===custom).due,'2026-09-22T17:00');
const steps=[{name:'需求登记',dept:'办公室',offset:-1,time:'18:00',depends:[],requirements:'登记需求',rewardPoints:null},{name:'交付',dept:'视觉传达部',offset:1,time:'12:00',depends:[0],requirements:'交付素材',rewardPoints:5}];
await call('templates/save',{name:'越权模板',steps},applicant.cookie,403);
await call('templates/save',{name:'循环依赖',steps:[{...steps[0],depends:[0]}]},owner.cookie,400);
const template=(await call('templates/save',{name:'测试模板',steps},owner.cookie)).body.id;
await call('templates/save',{id:template,name:'越权编辑',steps},editor.cookie,403);
const reusable=(await call('events/create',{name:'模板活动',date:'2026-10-01',template,rewardPoints:12,assignments:[{owner:editorInfo.id,receiver:editorInfo.id},{owner:applicantId,receiver:editorInfo.id}]},owner.cookie)).body.id;
let reusableTasks=(await call('state',null,owner.cookie)).body.tasks.filter(t=>t.event===reusable);assert.equal(reusableTasks.length,2);assert.equal(reusableTasks[0].rewardPoints,12);assert.equal(reusableTasks[1].rewardPoints,5);assert.equal(reusableTasks[1].status,'blocked');
await call('templates/save',{id:template,name:'更新后的模板',steps:[]},owner.cookie);
assert.equal((await call('state',null,owner.cookie)).body.tasks.filter(t=>t.event===reusable).length,2);
await call('invite',{dept:'办公室',role:'member'},owner.cookie,403,{Origin:'https://attacker.test'});
const reset=(await call('reset-link',{id:applicantId},owner.cookie)).body.token;
await call('recover',{token:reset,password:'New-member-password-12'});await call('state',null,applicant.cookie,401);await call('recover',{token:reset,password:'Another-member-password'},'',400);
applicant=await call('login',{username:'photographer',password:'New-member-password-12'});
await call('members/update',{id:applicantId,dept:'视觉传达部',role:'member',status:'disabled'},owner.cookie);await call('state',null,applicant.cookie,401);
await call('login',{username:'photographer',password:'New-member-password-12'},'',403);
await call('logout',{},editor.cookie);await call('state',null,editor.cookie,401);
const stored=DB.sqlite.prepare('SELECT password FROM users WHERE username=?').get('owner').password;assert.ok(stored.startsWith('$2b$12$'));assert.ok(!JSON.stringify(st).includes(stored));
console.log('PASS: accounts, role boundaries, CSRF, dependencies, blank events, template creation/reuse, upload/link confirmations, conflict recovery, rescheduling, exactly-once reward ledger, recovery, session revocation and password hashing.');


