import {readFileSync} from 'node:fs';
import {createRequire} from 'node:module';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const require=createRequire(import.meta.url),O=require('../../miniprogram/utils/organization.js'),mutations=[];
const V={depts:['办公室','新媒体运营部','视觉传达部','创意设计部'],roles:{admin:'管理员',manager:'部门负责人',member:'成员'},statuses:{},day:()=> '2026-10-06',page:s=>s,api:{mutate:async(p,d)=>{mutations.push({p,d});return{}},call:async()=>({members:[]})},action:async(_,f)=>f(),error:e=>{throw e}};
function load(file){let page;vm.runInNewContext(readFileSync(new URL('../../miniprogram/pages/'+file,import.meta.url),'utf8'),{require:p=>p.includes('organization')?O:p.includes('task-model')?require('../../miniprogram/utils/task-model.js'):p.includes('task-ui')?require('../../miniprogram/utils/task-ui.js'):V,Page:p=>page=p,wx:{showToast(){},navigateBack(){}}});page.data=structuredClone(page.data);page.setData=function(d){for(const [key,value] of Object.entries(d)){if(key.startsWith('fields[')){const m=key.match(/^fields\[(\d+)\]\.(.+)$/);this.data.fields[Number(m[1])][m[2]]=value}else this.data[key]=value}};return page}
const user={id:'u1',name:'伙伴',role:'member',dept:'办公室'},people=[user,{id:'u2',name:'创设伙伴',role:'member',dept:'创意设计部'}],state={user,people,events:[{id:'e1',name:'大任务',date:'2026-10-10'}],tasks:[{id:'t1',event:'e1',owner:'u1',receiver:'u2'}],templates:[]};
let page=load('editor/index.js');page.options={mode:'event-new'};page.renderState(state);const i=page.data.fields.findIndex(f=>f.key==='requester');assert.equal(page.data.fields[i].type,'person');assert.equal(page.data.fields[i].groups.length,4);page.selectPerson({currentTarget:{dataset:{index:i,value:'__other__'}}});assert.equal(page.data.fields.find(f=>f.key==='requesterOther').hidden,false);page.data.fields.find(f=>f.key==='requesterOther').value='外部伙伴';await page.save();assert.equal(mutations.at(-1).d.requester,'外部伙伴');
page=load('editor/index.js');page.options={mode:'task-new',event:'e1'};page.renderState(state);const owner=page.data.fields.find(f=>f.key==='owners');assert.equal(owner.type,'multiPerson');assert.equal(owner.groups[3].people[0].value,'u2');
page=load('tasks/index.js');page.renderState(state);assert.equal(page.data.groups[0].tasks.length,1);page.toggle({currentTarget:{dataset:{id:'e1'}}});assert.equal(page.data.groups[0].open,false);page.renderState(state);assert.equal(page.data.groups[0].open,false);
const config=JSON.parse(readFileSync(new URL('../../miniprogram/app.json',import.meta.url),'utf8'));assert.ok(config.pages.includes('pages/profile/settings'));assert.equal(O.color('创意设计部'),'#8b5bc7');
console.log('PASS: mini UI department hierarchy, other requester payload, personnel assignment, persistent task expansion and profile route.');
