const R=require('../../utils/recovery'),UI=require('../../utils/interface'),api=require('../../services/api'),Share=require('../../utils/sharing'),config=require('../../config');
const zh={title:'本机安全中心',intro:'检查当前设备的界面与缓存，无需网络。',storage:'本机存储',presentation:'展示配置',renderer:'页面渲染',canvas:'动态背景能力',cache:'展示缓存',version:'当前版本',available:'可用',limited:'受限',valid:'正常',repairNeeded:'需要修复',ready:'正常',fallback:'安全回退',unknown:'等待页面使用',supported:'支持',repair:'一键本机修复',reset:'重置本机外观',restart:'重启界面',clear:'清除展示缓存',copy:'复制脱敏诊断',history:'近期匿名错误摘要',empty:'尚无近期错误',result:'最近恢复结果',done:'已完成',partial:'部分完成',noRecovery:'尚无恢复记录',noData:'诊断仅含版本、能力、缓存大小和固定错误码，不含姓名、账号、任务、令牌或连接地址。',repairDone:'本机修复完成',repairPartial:'存储受限，部分修复未完成',copied:'脱敏诊断已复制',copyFailed:'复制未完成，请重试',restartHint:'正在重新打开界面',startup:'启动规范化',clearDisplay:'清理展示缓存',resetAppearance:'本机外观已重置',readonly:'本次登录的内存快照为只读，刷新后才能编辑。'};
const en={title:'Local Safety Center',intro:'Check this device’s interface and cache without a network request.',storage:'Local storage',presentation:'Display preferences',renderer:'Page rendering',canvas:'Animated background support',cache:'Display cache',version:'Current version',available:'Available',limited:'Limited',valid:'Valid',repairNeeded:'Repair needed',ready:'Ready',fallback:'Safe fallback',unknown:'Waiting for use',supported:'Supported',repair:'Repair this device',reset:'Reset local appearance',restart:'Restart interface',clear:'Clear display cache',copy:'Copy sanitized diagnostics',history:'Recent anonymous error codes',empty:'No recent errors',result:'Last recovery',done:'Completed',partial:'Partly completed',noRecovery:'No recovery recorded',noData:'Diagnostics contain only version, capabilities, cache size and fixed error codes. Names, accounts, tasks, tokens and connection addresses are excluded.',repairDone:'Local repair completed',repairPartial:'Storage is limited; some repairs could not finish',copied:'Sanitized diagnostics copied',copyFailed:'Copy failed. Try again.',restartHint:'Reopening the interface',startup:'Startup normalization',clearDisplay:'Display cache cleared',resetAppearance:'Local appearance reset',readonly:'This sign-in’s memory snapshot is read only. Refresh before editing.'};
Page(Share.page({
 data:{},
 onLoad(){UI.install(this);this.update()},onShow(){if(this.interfaceInstalled)this.update()},
 update(){const l=UI.language()==='en'?en:zh,h=R.health(config.releaseVersion||api.getState()?.version||''),settings=R.applySettings(api.getState()?.settings||R.displaySettings());let systemTheme='light';try{systemTheme=wx.getSystemInfoSync?.().theme||'light'}catch{}const dark=settings.appearance==='dark'||settings.appearance==='auto'&&systemTheme==='dark';this.setData({l,health:h,themeStyle:UI.style(settings),fontScale:settings.fontScale,motion:settings.motion,particles:settings.particles,particleStyle:settings.particles,particleDensity:settings.particleDensity,particleSystem:settings.particleSystem,particleTheme:settings.themeColor,rotationMinutes:settings.rotationMinutes,dark,readOnly:api.isReadOnly(),checks:[{key:'storage',label:l.storage,value:l[h.storage],good:h.storage==='available'},{key:'presentation',label:l.presentation,value:h.presentation==='valid'?l.valid:l.repairNeeded,good:h.presentation==='valid'},{key:'renderer',label:l.renderer,value:l[h.renderer]||l.unknown,good:h.renderer!=='fallback'},{key:'canvas',label:l.canvas,value:l[h.canvas]||l.unknown,good:h.canvas==='supported'},{key:'cache',label:l.cache,value:h.cacheKB+' KB',good:true},{key:'version',label:l.version,value:h.version,good:true}],recoveryLabel:h.lastRecovery?(l[h.lastRecovery.action]||l.repair)+' · '+l[h.lastRecovery.result]:l.noRecovery});UI.navigation(this,{settings,dark})},
 repair(){const r=R.repair();this.update();wx.showToast({title:r.result==='done'?this.data.l.repairDone:this.data.l.repairPartial,icon:r.result==='done'?'success':'none'})},
 reset(){const r=R.repair({resetAppearance:true});this.update();wx.showToast({title:r.result==='done'?this.data.l.resetAppearance:this.data.l.repairPartial,icon:'none'})},
 clear(){R.clearDisplay();this.update();wx.showToast({title:this.data.l.clearDisplay,icon:'none'})},
 restart(){R.noteRecovery('restart');api.discardSnapshot();try{wx.reLaunch({url:api.token()?'/pages/home/index':'/pages/auth/index'})}catch(error){R.capture(error,'render');this.update()}},
 copy(){const diagnostics=R.diagnostic(config.releaseVersion||api.getState()?.version||'');try{wx.setClipboardData({data:diagnostics,success:()=>wx.showToast({title:this.data.l.copied,icon:'none'}),fail:error=>{R.capture(error,'runtime');wx.showToast({title:this.data.l.copyFailed,icon:'none'})}})}catch(error){R.capture(error,'runtime');wx.showToast({title:this.data.l.copyFailed,icon:'none'})}},
 particleTouchStart(e){UI.pointer(this,e)},particleTouchMove(e){UI.pointer(this,e)},particleTouchEnd(e){UI.pointer(this,e)}
}));
