const E=require('../../utils/particle-engine');
const STYLES=['constellation','fireflies','snow','petals','rain','orbits','stars','bubbles'];
Component({
 properties:{enabled:{type:Boolean,value:true},effect:{type:String,value:'constellation'},density:{type:Number,value:48},settings:{type:Object,value:{}},theme:{type:String,value:'#e77b24'},rotation:{type:Number,value:5}},
 observers:{'enabled,effect,density,settings,theme,rotation':function(){this.update()}},
 lifetimes:{ready(){this.ready=true;this.update()},detached(){this.destroyed=true;this.stop();this.canvas=null;this.context=null;this.system=null}},
 pageLifetimes:{show(){this.hidden=false;this.update()},hide(){this.hidden=true;this.stop();this.points=[]},resize(){this.measure()}},
 methods:{
  update(){if(!this.ready||this.destroyed)return;if(!this.data.enabled||this.data.effect==='off'){this.stop();this.context?.clearRect(0,0,this.width||0,this.height||0);this.canvas=null;this.context=null;this.system=null;this.points=[];return}if(this.system){E.configure(this.system,this.data.settings||{});if(this.system.particles.length!==Math.max(10,Math.min(80,Number(this.data.density)||48)))this.system=E.create({width:this.width,height:this.height,count:this.data.density,settings:this.data.settings||{}})}if(!this.canvas){if(wx.nextTick)wx.nextTick(()=>this.measure());else setTimeout(()=>this.measure(),0)}else this.start()},
  measure(){if(!this.ready||this.destroyed||this.measuring||!this.data.enabled)return;this.measuring=true;this.createSelectorQuery().select('#particle-canvas').fields({node:true,size:true,rect:true}).exec(result=>{this.measuring=false;if(this.destroyed||!this.data.enabled||this.data.effect==='off')return;const r=result?.[0];if(!r?.node?.getContext||!r.width||!r.height){this.stop();return}try{this.canvas=r.node;this.context=this.canvas.getContext('2d');this.width=r.width;this.height=r.height;this.origin={left:r.left||0,top:r.top||0};const info=wx.getWindowInfo?.()||wx.getSystemInfoSync?.()||{};const dpr=Math.min(2,Math.max(1,info.pixelRatio||1));this.canvas.width=Math.round(r.width*dpr);this.canvas.height=Math.round(r.height*dpr);this.context.setTransform?.(dpr,0,0,dpr,0,0);if(!this.context.setTransform)this.context.scale(dpr,dpr);if(this.system)E.resize(this.system,r.width,r.height);else this.system=E.create({width:r.width,height:r.height,count:this.data.density,settings:this.data.settings||{}});this.start()}catch{this.stop();this.canvas=null;this.context=null}})},
  start(){if(this.handle!=null||this.hidden||this.destroyed||!this.data.enabled||!this.canvas||!this.context)return;this.lastTime=0;this.lastDraw=0;const tick=now=>{this.handle=null;if(this.hidden||this.destroyed||!this.data.enabled)return;const time=Number.isFinite(now)?now:Date.now();if(!this.lastDraw||time-this.lastDraw>=32){const dt=this.lastTime?Math.min(.065,Math.max(.001,(time-this.lastTime)/1000)):1/30;this.lastTime=time;this.lastDraw=time;const style=this.currentStyle(time);E.step(this.system,dt,this.points||[],this.data.theme);E.draw(this.context,this.system,style,this.data.theme)}this.handle=this.schedule(tick)};this.handle=this.schedule(tick)},
  schedule(fn){return this.canvas.requestAnimationFrame?this.canvas.requestAnimationFrame(fn):setTimeout(()=>fn(Date.now()),34)},
  stop(){if(this.handle!=null){if(this.canvas?.cancelAnimationFrame)this.canvas.cancelAnimationFrame(this.handle);else clearTimeout(this.handle)}this.handle=null;this.lastTime=0;this.lastDraw=0},
  currentStyle(time){if(this.data.effect==='random'){this.randomStyle||=STYLES[Math.floor(Math.random()*STYLES.length)];return this.randomStyle}if(this.data.effect==='rotate')return STYLES[Math.floor(Date.now()/(Math.max(1,this.data.rotation||5)*60000))%STYLES.length];return this.data.effect},
  pointer(touches){this.points=(touches||[]).map(t=>({x:Number(t.clientX??t.x)-(this.origin?.left||0),y:Number(t.clientY??t.y)-(this.origin?.top||0)})).filter(t=>Number.isFinite(t.x)&&Number.isFinite(t.y))},
  refresh(){this.measure()}
 }
});
