import {cp,mkdir,readFile,writeFile} from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const source=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const target=path.resolve('C:/Users/QiuXY/WeChatProjects/miniprogram-1');
if(target!=='C:\\Users\\QiuXY\\WeChatProjects\\miniprogram-1'&&target.replaceAll('\\','/')!=='C:/Users/QiuXY/WeChatProjects/miniprogram-1')throw Error('Unexpected installation target');
const original=JSON.parse(await readFile(path.join(target,'project.config.json'),'utf8'));
if(original.appid!=='wx329dab0b8d30dec7')throw Error('AppID does not match inspected project');
const stamp=new Date().toISOString().replace(/[:.]/g,'-'),backup=path.join(source,'.backup',stamp);
await mkdir(backup,{recursive:true});
for(const name of ['miniprogram','cloudfunctions','project.config.json','project.private.config.json','README.md'])await cp(path.join(target,name),path.join(backup,name),{recursive:true});
for(const name of ['miniprogram','cloudfunctions','project.config.json','README.md'])await cp(path.join(source,name),path.join(target,name),{recursive:true,force:true});
await writeFile(path.join(source,'.qa','installation.json'),JSON.stringify({target,backup,installedAt:new Date().toISOString()},null,2));
console.log('Installed native project at '+target+'; original template backup: '+backup);
