const V=require('../../utils/view'),UI=require('../../utils/interface');
const lang=(zh,en)=>UI.language()==='en'?en:zh;
Page(V.page({data:{submission:'',link:'',checks:[],uploadConfirmed:false,linkConfirmed:false,uploadVisited:false,submitting:false,submissionMode:'submit',busy:false,feedbackMode:'',feedback:''},
 renderState(s){const t=s.tasks.find(t=>t.id===this.options.id),e=s.events.find(e=>e.id===t?.event),changed=this.data.event?.cloudUrl&&this.data.event.cloudUrl!==e?.cloudUrl,unblocked=(t?.depends||[]).every(id=>s.tasks.some(x=>x.id===id&&x.status==='done')),proxyStatuses=['pending','active','revise','conflict',...(unblocked?['blocked']:[])];this.setData({task:t||null,event:e||null,canAccept:t?.isOwner&&t.status==='pending',canResume:t?.isOwner&&t.status==='conflict',canSubmit:t?.isOwner&&['active','revise'].includes(t.status),canProxySubmit:t?.canProxySubmit&&proxyStatuses.includes(t.status)&&!(t.isOwner&&['active','revise'].includes(t.status)),canArchive:t?.canArchive&&[...proxyStatuses,'review'].includes(t.status),canConflict:t?.isOwner&&['pending','active','revise'].includes(t.status),canReview:t?.isReviewer&&t.status==='review',taskLabels:{proxy:lang('代成员交付','Deliver for member'),archive:lang('完成交付并归档','Deliver and archive'),archiveTitle:lang('交付与归档','Deliver and archive'),archiveSubmit:lang('确认归档','Confirm archive'),reassign:lang('转派给下属','Reassign to team member'),legacy:lang('此任务仍由初始管理员执行，请调整分工后继续。','This task needs reassignment from the initial administrator.'),owners:lang('共同执行人','Assigned members'),receivers:lang('共同验收人','Reviewers'),total:lang('任务总积分','Total task points')},...(changed?{uploadConfirmed:false,uploadVisited:false}:{})});if(t&&!this.initialized){this.initialized=true;this.setData({submission:t.submission||'',link:t.link||''})}},
 input(e){const k=e.currentTarget.dataset.key;this.setData({[k]:e.detail.value,...(k==='link'?{linkConfirmed:false}:{})})},checks(e){this.setData({checks:e.detail.value})},confirm(e){this.setData({[e.currentTarget.dataset.key]:e.detail.value.length>0})},startSubmit(e){const mode=e?.currentTarget?.dataset?.mode==='archive'?'archive':'submit';if(mode==='archive'&&!this.data.canArchive||mode==='submit'&&!this.data.canSubmit&&!this.data.canProxySubmit)return;this.setData({submitting:true,submissionMode:mode,checks:[],uploadConfirmed:false,linkConfirmed:false,uploadVisited:false})},cancel(){this.setData({submitting:false,feedbackMode:''})},feedback(e){this.setData({feedbackMode:e.currentTarget.dataset.action,feedback:''})},
 async doAction(e){const a=e.currentTarget.dataset.action;await V.action(this,async()=>{await V.api.mutate('tasks/action',{id:this.options.id,action:a});wx.showToast({title:lang('已更新','Updated')})})},
 async sendFeedback(){await V.action(this,async()=>{await V.api.mutate('tasks/action',{id:this.options.id,action:this.data.feedbackMode,feedback:this.data.feedback});this.setData({feedbackMode:''})})},
 async send(){await V.action(this,async()=>{const d=this.data,t=d.task,checked=(t.checks||[]).map((_,i)=>d.checks.includes(String(i)));if(!checked.every(Boolean))throw Error(lang('请完成全部核对项','Complete every checklist item'));if(!d.submission.trim())throw Error(lang('请填写成果与交接说明','Describe the deliverables and handoff'));if(d.event.cloudUrl&&!d.uploadConfirmed)throw Error(lang('请确认已上传至活动素材库','Confirm the upload to the event library'));if(d.link&&!d.linkConfirmed)throw Error(lang('请确认个人成果链接可访问','Confirm the deliverable link is accessible'));const archive=d.submissionMode==='archive';if(archive&&!d.canArchive||!archive&&!d.canSubmit&&!d.canProxySubmit)throw Error(lang('当前不能提交这个任务','This task cannot be submitted now'));await V.api.mutate('tasks/action',{id:t.id,action:archive?'archive':'submit',submission:d.submission,link:d.link,checked,uploadConfirmed:d.uploadConfirmed,uploadUrl:d.event.cloudUrl||'',linkConfirmed:d.linkConfirmed});this.setData({submitting:false});wx.showToast({title:archive?lang('已归档','Archived'):lang('成果已提交','Submitted')})})},
 help(e){const i=Number(e.currentTarget.dataset.index),t=this.data.task,v=this.data.event;wx.showModal({title:t.checks[i],content:i===0?`${v.name}\n${v.date} ${v.startTime||'全天'}\n${v.location||'地点待定'}\n${v.description||''}\n交付要求：${t.requirements}\n截止：${t.dueLabel}\n验收：${t.receiverName}`:`交接给 ${t.receiverName}。写清成果内容、版本与文件位置。文件按“日期_活动名_内容_序号”命名；照片注明人物与摄影者，视频按机位/环节归类，设计保留源文件与导出图。`,showCancel:false})},
 cloud(){V.copy(this.data.event.cloudUrl);this.setData({uploadVisited:true})},copyLink(){V.copy(this.data.link||this.data.task.link)},receipt(){V.copy(this.data.task.uploadReceipt.url)}
}));
