const V=require('../../utils/view');
Page(V.page({data:{submission:'',link:'',checks:[],uploadConfirmed:false,linkConfirmed:false,uploadVisited:false,submitting:false,busy:false,feedbackMode:'',feedback:''},renderState(s){const t=s.tasks.find(t=>t.id===this.options.id);const e=s.events.find(e=>e.id===t?.event);const changed=this.data.event?.cloudUrl&&this.data.event.cloudUrl!==e?.cloudUrl;this.setData({task:t||null,event:e||null,canAccept:t?.isOwner&&t.status==='pending',canResume:t?.isOwner&&t.status==='conflict',canSubmit:t?.isOwner&&['active','revise'].includes(t.status),canConflict:t?.isOwner&&['pending','active','revise'].includes(t.status),canReview:t?.isReviewer&&t.status==='review',...(changed?{uploadConfirmed:false,uploadVisited:false}:{} )});if(t&&!this.initialized){this.initialized=true;this.setData({submission:t.submission||'',link:t.link||''})}},
 input(e){const k=e.currentTarget.dataset.key;this.setData({[k]:e.detail.value,...(k==='link'?{linkConfirmed:false}:{})})},checks(e){this.setData({checks:e.detail.value})},confirm(e){this.setData({[e.currentTarget.dataset.key]:e.detail.value.length>0})},startSubmit(){this.setData({submitting:true})},cancel(){this.setData({submitting:false,feedbackMode:''})},feedback(e){this.setData({feedbackMode:e.currentTarget.dataset.action,feedback:''})},
 async doAction(e){const a=e.currentTarget.dataset.action;await V.action(this,async()=>{await V.api.mutate('tasks/action',{id:this.options.id,action:a});wx.showToast({title:'已更新'})})},
 async sendFeedback(){await V.action(this,async()=>{await V.api.mutate('tasks/action',{id:this.options.id,action:this.data.feedbackMode,feedback:this.data.feedback});this.setData({feedbackMode:''})})},
 async send(){await V.action(this,async()=>{const d=this.data,t=d.task;if(d.checks.length!==t.checks.length)throw Error('请完成全部核对项');if(!d.submission.trim())throw Error('请填写成果与交接说明');if(d.event.cloudUrl&&!d.uploadConfirmed)throw Error('请确认已上传至活动素材库');if(d.link&&!d.linkConfirmed)throw Error('请确认个人成果链接可访问');await V.api.mutate('tasks/action',{id:t.id,action:'submit',submission:d.submission,link:d.link,checked:t.checks.map((_,i)=>d.checks.includes(String(i))),uploadConfirmed:d.uploadConfirmed,uploadUrl:d.event.cloudUrl||'',linkConfirmed:d.linkConfirmed});this.setData({submitting:false});wx.showToast({title:'成果已提交'})})},
 help(e){const i=Number(e.currentTarget.dataset.index),t=this.data.task,v=this.data.event;wx.showModal({title:t.checks[i],content:i===0?`${v.name}\n${v.date} ${v.startTime||'全天'}\n${v.location||'地点待定'}\n${v.description||''}\n交付要求：${t.requirements}\n截止：${t.dueLabel}\n验收：${t.receiverName}`:`交接给 ${t.receiverName}。写清成果内容、版本与文件位置。文件按“日期_活动名_内容_序号”命名；照片注明人物与摄影者，视频按机位/环节归类，设计保留源文件与导出图。`,showCancel:false})},
 cloud(){V.copy(this.data.event.cloudUrl);this.setData({uploadVisited:true})},copyLink(){V.copy(this.data.link||this.data.task.link)},receipt(){V.copy(this.data.task.uploadReceipt.url)}
}));
