const V=require('../../utils/view'),I=require('../../utils/interface'),E=require('../../utils/particle-engine');
const styleNames=['关闭','星座连线','萤火微光','轻雪','花瓣','流星雨','轨道光环','闪烁星空','漂浮气泡','每次随机','定时轮换'],styleKeys=['off','constellation','fireflies','snow','petals','rain','orbits','stars','bubbles','random','rotate'];
const controls=[
 ['movement','speed','速度','Speed',0,180],['movement','gravityX','横向引力','Horizontal gravity',-160,160],['movement','gravityY','纵向引力','Vertical gravity',-160,160],['movement','drag','阻尼','Drag',0,3],['movement','bounce','碰撞弹性','Bounce',0,1],['movement','life','生命周期（秒）','Lifetime (seconds)',4,60],['movement','lifeRandom','生命周期随机性','Lifetime variation',0,1],['movement','size','粒子大小','Particle size',1,8],['movement','sizeRandom','大小随机性','Size variation',0,1],['movement','randomness','运动随机性','Motion variation',0,1],
 ['interaction','pointerForce','触点力度','Pointer strength',0,600],['interaction','pointerRadius','作用范围','Interaction radius',40,320],['interaction','edgeBias','边缘聚集','Edge concentration',0,1],
 ['light','opacity','透明度','Opacity',.05,1],['light','brightness','亮度','Brightness',.2,2],['light','twinkle','闪烁幅度','Twinkle amount',0,1],['light','twinkleSpeed','闪烁速度','Twinkle speed',0,4],['light','colorSpeed','色彩变化速度','Color shift speed',0,2]
];
const copy={font:'字体大小',fontSample:'这就是你的工作台字号',fontHint:'拖动即可预览；保存后应用到所有页面与设备。',particles:'粒子工作室',preset:'色彩预设',movement:'运动与生命周期',interaction:'触控交互',light:'光影与颜色',collision:'粒子碰撞',pointer:'触点行为',mode:'颜色模式',start:'渐变起点／自定义颜色',end:'渐变终点',saveHint:'预览当前效果，保存后同步。',disabled:'动态效果已关闭，所有粒子及漂浮动画将暂停。',on:'开启动效',gradient:'渐变预览'};
const en={font:'Font size',fontSample:'Your workspace at this font size',fontHint:'Drag to preview. Save to apply across pages and devices.',particles:'Particle studio',preset:'Color presets',movement:'Motion and lifetime',interaction:'Touch interaction',light:'Light and color',collision:'Particle collisions',pointer:'Pointer behavior',mode:'Color mode',start:'Gradient start / custom color',end:'Gradient end',saveHint:'Preview changes here. Save to sync.',disabled:'Motion is off. Particles and floating animations are paused.',on:'Enable motion',gradient:'Gradient preview'};
Page(V.page({
 data:{tab:'general',physicsTab:'movement',styles:styleNames,appearanceLabels:['白','黑','跟随系统'],languageLabels:['中文','English'],colors:['#e77b24','#168875','#d47918','#3478c5','#8b5bc7','#ca416b'],reason:'',password:''},
 renderState(s){if(!this.initialized){this.initialized=true;const settings={particles:'constellation',particleDensity:48,rotationMinutes:5,themeColor:'#e77b24',appearance:'light',motion:true,...(s.settings||{}),fontScale:I.fontScale(s.settings),particleSystem:E.normalize(s.settings?.particleSystem)};delete settings.compact;delete settings.respectSystemMotion;this.setData({settings,particleIndex:Math.max(0,styleKeys.indexOf(settings.particles)),appearanceIndex:Math.max(0,['light','dark','auto'].indexOf(settings.appearance)),languageIndex:settings.language==='en'?1:0})}this.setData({request:s.accountRequest,styles:styleNames.map(I.t),appearanceLabels:['白','黑','跟随系统'].map(I.t)});this.preview()},
 preview(){const settings=this.data.settings||{},english=I.language()==='en',p=E.normalize(settings.particleSystem),keys=Object.keys(E.presets);this.setData({l:english?en:copy,fontPercent:Math.round(I.fontScale(settings)*100),fontScale:I.fontScale(settings),themeStyle:I.style(settings),dark:settings.appearance==='dark'||settings.appearance==='auto'&&wx.getSystemInfoSync?.().theme==='dark',motion:settings.motion!==false,particles:settings.particles||'constellation',particleStyle:settings.particles||'constellation',particleSystem:p,particleDensity:Number(settings.particleDensity)||48,rotationMinutes:Number(settings.rotationMinutes)||5,presetKeys:keys,presetIndex:Math.max(0,keys.indexOf(p.preset)),presetLabels:keys.map(k=>english?E.presets[k].labelEn:E.presets[k].label),presetSwatches:keys.map(k=>({key:k,label:english?E.presets[k].labelEn:E.presets[k].label,start:E.presets[k].config.colorStart||E.defaults.colorStart,end:E.presets[k].config.colorEnd||E.defaults.colorEnd})),interactionLabels:english?['Repel','Attract','Off']:['排斥','吸引','关闭'],interactionIndex:Math.max(0,['repel','attract','off'].indexOf(p.interaction)),colorLabels:english?['Gradient','Theme color','Custom color','Rainbow cycle']:['渐变','主题色','自定义单色','循环变色'],colorIndex:Math.max(0,['gradient','theme','custom','cycle'].indexOf(p.colorMode)),controls:controls.filter(c=>c[0]===this.data.physicsTab).map(c=>({key:c[1],label:english?c[3]:c[2],value:Math.round((p[c[1]]-c[4])/(c[5]-c[4])*100),display:Number(p[c[1]].toFixed(2))}))})},
 tab(e){this.setData({tab:e.currentTarget.dataset.id})},physicsTab(e){this.setData({physicsTab:e.currentTarget.dataset.id});this.preview()},
 color(e){this.setData({'settings.themeColor':e.currentTarget.dataset.color});this.preview()},input(e){this.setData({['settings.'+e.currentTarget.dataset.key]:e.detail.value});this.preview()},toggle(e){this.setData({['settings.'+e.currentTarget.dataset.key]:e.detail.value});this.preview()},
 font(e){this.setData({'settings.fontScale':Math.max(.85,Math.min(1.35,Number(e.detail.value)/100))});this.preview()},
 particle(e){const i=Number(e.detail.value);this.setData({particleIndex:i,'settings.particles':styleKeys[i]});this.preview()},appearance(e){const i=Number(e.detail.value);this.setData({appearanceIndex:i,'settings.appearance':['light','dark','auto'][i]});this.preview()},languageChange(e){const i=Number(e.detail.value);this.setData({languageIndex:i,'settings.language':i?'en':'zh-CN'})},
 preset(e){const key=e.currentTarget.dataset.preset||this.data.presetKeys[Number(e.detail.value)];if(!E.presets[key])return;this.setData({'settings.particleSystem':E.normalize({...E.defaults,...E.presets[key].config,preset:key})});this.preview()},
 control(e){const c=controls.find(c=>c[1]===e.currentTarget.dataset.key);if(!c)return;this.setData({['settings.particleSystem.'+c[1]]:Number((c[4]+(c[5]-c[4])*Number(e.detail.value)/100).toFixed(2))});this.preview()},
 systemToggle(e){this.setData({['settings.particleSystem.'+e.currentTarget.dataset.key]:e.detail.value});this.preview()},systemInput(e){this.setData({['settings.particleSystem.'+e.currentTarget.dataset.key]:e.detail.value});this.preview()},
 interaction(e){this.setData({'settings.particleSystem.interaction':['repel','attract','off'][Number(e.detail.value)]});this.preview()},colorMode(e){this.setData({'settings.particleSystem.colorMode':['gradient','theme','custom','cycle'][Number(e.detail.value)]});this.preview()},
 async save(){await V.action(this,async()=>{const settings={...this.data.settings,fontScale:I.fontScale(this.data.settings),particleDensity:Number(this.data.settings.particleDensity||48),rotationMinutes:Number(this.data.settings.rotationMinutes||5)};for(const key of ['colorStart','colorEnd'])if(!/^#[0-9a-f]{6}$/i.test(settings.particleSystem?.[key]||''))throw Error(I.language()==='en'?'Use a six-digit color such as #66d9c5.':'颜色请使用六位十六进制格式，例如 #66d9c5。');settings.particleSystem=E.normalize(settings.particleSystem);delete settings.compact;delete settings.respectSystemMotion;await V.api.mutate('settings/save',settings);this.initialized=false;const s=V.api.getState();if(s)this.renderState(V.decorate(s));wx.showToast({title:I.t('设置已同步')})})},
 async clearCache(){await V.action(this,async()=>{for(const key of wx.getStorageInfoSync().keys)if(key.startsWith('fr.')&&!['fr.token','fr.connection','fr.language'].includes(key))wx.removeStorageSync(key);await V.api.refresh(true);wx.showToast({title:I.t('缓存已清理')})})},
 reason(e){this.setData({reason:e.detail.value})},password(e){this.setData({password:e.detail.value})},async requestClosure(){await V.action(this,async()=>{await V.api.mutate('account/request',{reason:this.data.reason,password:this.data.password});this.setData({password:''});wx.showToast({title:I.t('已提交审核')})})},async cancelClosure(){await V.action(this,()=>V.api.mutate('account/cancel',{}))},async logout(){await V.action(this,async()=>{await V.api.call('logout',{});wx.reLaunch({url:'/pages/auth/index'})})}
}));
