const V=require('../../utils/view'),I=require('../../utils/interface');
const labels=['关闭','星座连线','萤火微光','轻雪','花瓣','流星雨','轨道光环','闪烁星空','漂浮气泡','每次随机','定时轮换'],styles=['off','constellation','fireflies','snow','petals','rain','orbits','stars','bubbles','random','rotate'];
Page(V.page({
 data:{tab:'general',styles:labels,appearanceLabels:['白','黑','跟随系统'],languageLabels:['中文','English'],colors:['#e77b24','#168875','#d47918','#3478c5','#8b5bc7','#ca416b'],reason:'',password:''},
 renderState(s){if(!this.initialized){this.initialized=true;this.setData({settings:s.settings||{},particleIndex:Math.max(0,styles.indexOf(s.settings?.particles)),appearanceIndex:Math.max(0,['light','dark','auto'].indexOf(s.settings?.appearance)),languageIndex:s.settings?.language==='en'?1:0})}this.setData({request:s.accountRequest,styles:labels.map(I.t),appearanceLabels:['白','黑','跟随系统'].map(I.t)})},
 tab(e){this.setData({tab:e.currentTarget.dataset.id})},color(e){this.setData({'settings.themeColor':e.currentTarget.dataset.color})},input(e){this.setData({['settings.'+e.currentTarget.dataset.key]:e.detail.value})},toggle(e){this.setData({['settings.'+e.currentTarget.dataset.key]:e.detail.value})},
 particle(e){const i=Number(e.detail.value);this.setData({particleIndex:i,'settings.particles':styles[i]})},appearance(e){const i=Number(e.detail.value);this.setData({appearanceIndex:i,'settings.appearance':['light','dark','auto'][i]})},languageChange(e){const i=Number(e.detail.value);this.setData({languageIndex:i,'settings.language':i?'en':'zh-CN'})},
 async save(){await V.action(this,async()=>{const settings={...this.data.settings,particleDensity:Number(this.data.settings.particleDensity||48),rotationMinutes:Number(this.data.settings.rotationMinutes||5)};await V.api.mutate('settings/save',settings);wx.showToast({title:I.t('设置已同步')})})},
 async clearCache(){await V.action(this,async()=>{for(const key of wx.getStorageInfoSync().keys)if(key.startsWith('fr.')&&!['fr.token','fr.connection','fr.language'].includes(key))wx.removeStorageSync(key);await V.api.refresh(true);wx.showToast({title:I.t('缓存已清理')})})},
 reason(e){this.setData({reason:e.detail.value})},password(e){this.setData({password:e.detail.value})},async requestClosure(){await V.action(this,async()=>{await V.api.mutate('account/request',{reason:this.data.reason,password:this.data.password});this.setData({password:''});wx.showToast({title:I.t('已提交审核')})})},async cancelClosure(){await V.action(this,()=>V.api.mutate('account/cancel',{}))},async logout(){await V.action(this,async()=>{await V.api.call('logout',{});wx.reLaunch({url:'/pages/auth/index'})})}
}));
