const V=require('../../utils/view'),UI=require('../../utils/interface'),Crop=require('../../utils/avatar-crop');
const lang=(zh,en)=>UI.language()==='en'?en:zh;
Page(V.page({
 data:{name:'',avatar:'',initialized:false,cropping:false,zoom:100,cropSaving:false},
 renderState(s){if(this.profileOwner&&this.profileOwner!==s.user.id){this.closeCrop();this.setData({initialized:false})}this.profileOwner=s.user.id;if(!this.data.initialized)this.setData({name:s.user.name,avatar:s.user.avatar||'',initialized:true});this.setData({profile:s.profile,cropLabels:{title:lang('调整头像','Adjust avatar'),hint:lang('拖动照片移动位置，双指或滑块缩放。','Drag to reposition. Pinch or use the slider to zoom.'),zoom:lang('缩放','Zoom'),reset:lang('重置位置','Reset position'),cancel:lang('取消','Cancel'),apply:lang('使用头像','Use avatar'),preview:lang('圆形预览','Circular preview')}})},
 name(e){this.setData({name:e.detail.value})},clearAvatar(){this.setData({avatar:''})},
 async chooseAvatar(){if(this.data.busy||this.data.cropping||this.avatarSelecting||this.avatarDisposed)return;const epoch=this.avatarEpoch=(this.avatarEpoch||0)+1,owner=this.profileOwner;this.avatarSelecting=true;try{const media=await wx.chooseMedia({count:1,mediaType:['image'],sizeType:['compressed'],sourceType:['album','camera']});if(epoch!==this.avatarEpoch||this.avatarDisposed||owner!==this.profileOwner)return;const file=media.tempFiles?.[0];if(!file)return;if(file.size>10*1024*1024)throw Error(lang('请选择 10 MB 以内的图片','Choose an image smaller than 10 MB'));const info=await wx.getImageInfo({src:file.tempFilePath});if(epoch!==this.avatarEpoch||this.avatarDisposed||owner!==this.profileOwner)return;if(info.width*info.height>64000000)throw Error(lang('图片尺寸过大，请先缩小','This image is too large. Resize it first.'));this.avatarSource=file.tempFilePath;this.avatarInfo=info;this.cropOwner=owner;await new Promise(resolve=>this.setData({cropping:true,zoom:100},resolve));await this.setupCrop()}catch(e){if(this.avatarDisposed||epoch!==this.avatarEpoch||String(e?.errMsg||'').includes('cancel'))return;this.closeCrop();V.error(e?.name==='Error'?e:Error(lang('暂时无法读取这张图片，请重试。','Could not read this image. Try again.')))}finally{this.avatarSelecting=false}},
 async setupCrop(){const result=await new Promise(resolve=>wx.createSelectorQuery().in(this).select('#avatar-crop-canvas').fields({node:true,size:true,rect:true}).exec(r=>resolve(r?.[0])));if(!this.data.cropping||this.avatarDisposed||this.cropOwner!==this.profileOwner)return;if(!result?.node||!result.width)throw Error(lang('头像画布尚未就绪，请重试。','The avatar canvas is not ready. Try again.'));this.cropCanvas=result.node;this.cropRect=result;this.cropContext=this.cropCanvas.getContext('2d');const size=result.width;let dpr=1;try{dpr=Math.min(2,wx.getWindowInfo?.().pixelRatio||wx.getSystemInfoSync?.().pixelRatio||1)}catch{}this.cropCanvas.width=this.cropCanvas.height=Math.round(size*dpr);this.cropContext.scale(dpr,dpr);const img=this.cropCanvas.createImage();await new Promise((resolve,reject)=>{img.onload=resolve;img.onerror=()=>reject(Error(lang('图片读取失败','Image could not be decoded')));img.src=this.avatarSource});if(!this.data.cropping||this.avatarDisposed||this.cropOwner!==this.profileOwner)return;this.cropImage=img;this.cropState=Crop.create(this.avatarInfo.width,this.avatarInfo.height,size);this.drawCrop()},
 drawCrop(){if(!this.cropState||!this.cropContext||!this.cropImage)return;const g=this.cropState,ctx=this.cropContext;ctx.clearRect(0,0,g.size,g.size);ctx.drawImage(this.cropImage,g.x,g.y,g.width*g.base*g.zoom,g.height*g.base*g.zoom)},
 cropBackdropMove(){},
 cropTouchStart(e){const points=e.touches||[];if(!this.cropState)return;this.cropGesture={points:points.map(p=>({x:p.clientX,y:p.clientY})),x:this.cropState.x,y:this.cropState.y,zoom:this.cropState.zoom};if(points.length>=2)this.cropGesture.distance=Math.hypot(points[0].clientX-points[1].clientX,points[0].clientY-points[1].clientY)},
 cropTouchMove(e){const points=e.touches||[],gesture=this.cropGesture;if(!gesture||!this.cropState||!points.length)return;if(points.length>=2&&gesture.distance){const midX=(points[0].clientX+points[1].clientX)/2-(this.cropRect.left||0),midY=(points[0].clientY+points[1].clientY)/2-(this.cropRect.top||0),distance=Math.hypot(points[0].clientX-points[1].clientX,points[0].clientY-points[1].clientY);Crop.zoom(this.cropState,gesture.zoom*distance/gesture.distance,midX,midY);this.setData({zoom:Math.round(this.cropState.zoom*100)})}else if(gesture.points.length===1){this.cropState.x=gesture.x+points[0].clientX-gesture.points[0].x;this.cropState.y=gesture.y+points[0].clientY-gesture.points[0].y;Crop.constrain(this.cropState)}this.drawCrop()},
 cropTouchEnd(e){this.cropGesture=null;if(e.touches?.length)this.cropTouchStart(e)},
 cropZoom(e){if(!this.cropState)return;Crop.zoom(this.cropState,Number(e.detail.value)/100);this.setData({zoom:Math.round(this.cropState.zoom*100)});this.drawCrop()},
 resetCrop(){if(!this.cropState)return;this.cropState=Crop.create(this.cropState.width,this.cropState.height,this.cropState.size);this.setData({zoom:100});this.drawCrop()},
 closeCrop(){this.avatarEpoch=(this.avatarEpoch||0)+1;this.cropOwner=null;this.cropGesture=null;this.cropState=null;this.cropImage=null;this.cropContext=null;this.cropCanvas=null;this.avatarSource='';this.avatarInfo=null;this.setData({cropping:false,cropSaving:false})},
 async applyCrop(){if(this.data.cropSaving||!this.cropState)return;if(this.cropOwner!==this.profileOwner){this.closeCrop();return;}this.setData({cropSaving:true});try{const output=await new Promise(resolve=>wx.createSelectorQuery().in(this).select('#avatar-output-canvas').fields({node:true,size:true}).exec(r=>resolve(r?.[0]?.node)));if(this.avatarDisposed||!this.data.cropping||this.cropOwner!==this.profileOwner)return;if(!output)throw Error(lang('头像输出画布尚未就绪','The avatar output canvas is not ready'));const region=Crop.source(this.cropState);let avatar='';for(const [size,quality]of [[256,.7],[256,.5],[192,.55],[128,.6]]){output.width=output.height=size;const ctx=output.getContext('2d');ctx.fillStyle='#ffffff';ctx.fillRect(0,0,size,size);ctx.drawImage(this.cropImage,region.x,region.y,region.size,region.size,0,0,size,size);avatar=output.toDataURL('image/jpeg',quality);if(avatar.length<=14000)break}if(!/^data:image\/jpeg;base64,/.test(avatar)||avatar.length>18000)throw Error(lang('头像过于复杂，请缩小裁剪范围或换图。','This image is too complex. Crop more closely or choose another.'));this.setData({avatar});this.closeCrop()}catch(e){V.error(e);this.setData({cropSaving:false})}},
 onUnload(){this.avatarDisposed=true;this.avatarEpoch=(this.avatarEpoch||0)+1;this.cropOwner=null;this.cropGesture=null;this.cropState=null;this.cropImage=null;this.cropContext=null;this.cropCanvas=null;this.avatarSource='';this.avatarInfo=null},
 async save(){if(this.data.cropping)return;await V.action(this,async()=>{await V.api.mutate('profile/request',{name:this.data.name,avatar:this.data.avatar});wx.showModal({title:lang('已提交审核','Submitted for review'),content:lang('管理员批准后，姓名和头像将在所有设备生效。','Your name and avatar will sync across devices after approval.'),showCancel:false,success:()=>wx.navigateBack()})})}
}));
