const V=require('../../utils/view'),O=require('../../utils/organization'),UI=require('../../utils/interface'),R=require('../../utils/recovery');
const roleOrder={admin:0,manager:1,member:2};
const presence=p=>{const online=p.status==='active'&&p.online===true;return {online,onlineLabel:UI.language()==='en'?(online?'Online':'Offline'):(online?'在线':'离线')}};
Page(V.page({
 data:{department:'',groups:[],reviews:[],expanded:[],orgNodes:[],orgLinks:[],network:[],zoomLabel:'100%',worldWidth:800,worldHeight:620,cameraX:0,cameraY:0,zoom:1},
 renderState(s){if(this.user&&this.user.id!==s.user.id){this.stopMotion();this.loadEpoch=(this.loadEpoch||0)+1;this.members=[];this.orgScene=null;this.gesture=null;this.setData({orgNodes:[],orgLinks:[],groups:[],network:[],reviews:[],expanded:[],selectedPerson:null})}this.user=s.user;this.setData({manager:s.manager,admin:s.user.role==='admin'});if(this.orgScene&&this.orgScene.fontScale!==this.data.fontScale){O.resize(this.orgScene,this.boardSize?.width||340,this.boardSize?.height||520,this.data.fontScale||1);this.publishScene(true)}this.load();if(s.settings?.motion===false)this.stopMotion();else if(!this.hidden)this.startMotion()},
 onShow(){this.hidden=false;this.measureBoard();if(this.data.motion!==false)this.startMotion()},onHide(){this.hidden=true;this.stopMotion();if(this.orgScene)O.endDrag(this.orgScene,Date.now(),true);this.gesture=null},onResize(){this.measureBoard()},
 onUnload(){this.destroyed=true;this.loadEpoch=(this.loadEpoch||0)+1;this.stopMotion();this.members=[];this.user=null;this.orgScene=null;this.gesture=null;this.boardSize=null;this.data.orgNodes=[];this.data.orgLinks=[];this.data.network=[];this.data.groups=[];this.data.reviews=[];this.data.selectedPerson=null},
 measureBoard(){const q=wx.createSelectorQuery?.();q?.in(this).select('.org105-board').boundingClientRect(r=>{if(this.destroyed||!r?.width||!r?.height)return;const first=!this.boardSize;this.boardSize=r;this.ensureScene();O.resize(this.orgScene,r.width,r.height,this.data.fontScale||1);if(first)O.resetView(this.orgScene);this.publishScene(true)}).exec()},
 ensureScene(){if(!this.orgScene)this.orgScene=O.create({width:this.boardSize?.width||340,height:this.boardSize?.height||520,fontScale:this.data.fontScale||1,people:this.members||[],expanded:this.data.expanded});return this.orgScene},
 startMotion(){if(this.motionTimer||this.hidden||this.destroyed||this.data.motion===false)return;this.ensureScene();this.lastMotion=Date.now();this.motionTimer=setInterval(()=>this.animateMotion(),33)},stopMotion(){clearInterval(this.motionTimer);this.motionTimer=null},
 animateMotion(){if(this.destroyed||this.hidden||!this.orgScene)return;try{const now=Date.now(),dt=Math.min(.065,(now-this.lastMotion)/1000||1/30);this.lastMotion=now;O.step(this.orgScene,dt,this.data.motion!==false);this.publishScene(false)}catch(error){this.stopMotion();R.capture(error,'render');this.setData({motion:false})}},
 publishScene(full=false){if(!this.orgScene||this.destroyed||this.publishPending&&!full)return;const s=this.orgScene,zoom=s.view.zoom,links=O.links(s).map(l=>({...l,length:Math.hypot(l.x2-l.x1,l.y2-l.y1),angle:Math.atan2(l.y2-l.y1,l.x2-l.x1)*180/Math.PI,color:O.color(l.dept)})),nodes=s.nodes.map(n=>({id:n.id,kind:n.kind,dept:n.dept,r:n.r,x:n.x,y:n.y,diameter:n.r*2,color:O.color(n.dept),position:`left:${n.x.toFixed(3)}px;top:${n.y.toFixed(3)}px;`,name:n.kind==='root'?'冯如学媒':n.kind==='department'?UI.t(n.dept):n.person.name,avatar:n.person?.avatar||'',initial:n.person?.name?.slice(0,1)||'',roleLabel:n.person?UI.t(V.roles[n.person.role]||'成员'):'',...(n.person?presence(n.person):{}),description:n.kind==='department'?UI.t(O.descriptions[n.dept]):'',peopleCount:n.kind==='department'?(this.members||[]).filter(p=>!p.owner&&p.dept===n.dept&&p.status==='active').length:0,expanded:s.expanded.includes(n.dept)}));
  const patch={zoom,orgCompact:zoom<.9,cameraX:s.view.x,cameraY:s.view.y,zoomLabel:Math.round(zoom*100)+'%',worldWidth:s.width,worldHeight:s.height};
  if(full||this.data.orgNodes.length!==nodes.length){patch.orgNodes=nodes;patch.orgLinks=links;patch.network=nodes.filter(n=>n.kind==='department').map(n=>({...n,people:(this.members||[]).filter(p=>!p.owner&&p.dept===n.dept&&p.status==='active').sort((a,b)=>roleOrder[a.role]-roleOrder[b.role])}));patch.orgText={expand:UI.t('展开'),collapse:UI.t('收起'),people:UI.language()==='en'?'members':'位伙伴',center:UI.language()==='en'?'Center':'居中',in:UI.language()==='en'?'Zoom in':'放大',out:UI.language()==='en'?'Zoom out':'缩小'}}else{nodes.forEach((n,i)=>{patch[`orgNodes[${i}].position`]=n.position;patch[`orgNodes[${i}].x`]=n.x;patch[`orgNodes[${i}].y`]=n.y});links.forEach((l,i)=>{for(const k of ['x1','y1','length','angle'])patch[`orgLinks[${i}].${k}`]=l[k]})}this.publishPending=true;this.setData(patch,()=>{this.publishPending=false});R.markSuccess('render');
 },
 async load(){if(this.loading||!this.user)return;this.loading=true;const token=V.api.token(),epoch=this.loadEpoch=(this.loadEpoch||0)+1,owner=this.user.id;try{const b=await V.api.call('members');if(this.destroyed||epoch!==this.loadEpoch||token!==V.api.token()||this.user?.id!==owner)return;this.members=b.members.map(m=>({...m,...presence(m),roleLabel:UI.t(V.roles[m.role]),statusLabel:UI.t({active:'已开通',pending:'待审核',disabled:'已停用'}[m.status]),canEdit:!m.owner&&m.id!==this.user.id&&(this.user.role==='admin'||this.data.manager&&m.dept===this.user.dept&&m.role==='member')}));this.setData({reviews:b.reviews||[],selectedPerson:this.data.selectedPerson?this.members.find(p=>p.id===this.data.selectedPerson.id)||null:null});this.filterGroups()}catch(e){if(!this.destroyed&&epoch===this.loadEpoch&&token===V.api.token()&&this.user?.id===owner)this.setData({syncError:e.message})}finally{this.loading=false}},
 filterGroups(){this.ensureScene();O.reconcile(this.orgScene,this.members||[],this.data.expanded);this.setData({groups:O.groups(this.members||[]).filter(g=>!this.data.department||g.dept===this.data.department)});this.publishScene(true)},department(e){const d=e.currentTarget?.dataset?.dept||'';this.setData({department:'',expanded:d?(this.data.expanded.includes(d)?this.data.expanded.filter(x=>x!==d):[...this.data.expanded,d]):V.depts});this.filterGroups()},collapse(){this.setData({expanded:[]});this.filterGroups()},
 point(t){return {x:Number(t.clientX??t.x)-(this.boardSize?.left||0),y:Number(t.clientY??t.y)-(this.boardSize?.top||0)}},midpoint(touches){const a=this.point(touches[0]),b=this.point(touches[1]);return {x:(a.x+b.x)/2,y:(a.y+b.y)/2,d:Math.hypot(a.x-b.x,a.y-b.y)}},
 orgStart(e){this.particleTouchStart?.(e);const s=this.ensureScene(),touches=e.touches||[];if(!touches.length)return;if(touches.length>1){O.endDrag(s,Date.now(),true);this.gesture={mode:'pinch',...this.midpoint(touches),moved:true};return}const p=this.point(touches[0]),id=e.currentTarget.dataset.node,w=O.unproject(s,p.x,p.y);if(id)O.beginDrag(s,id,w.x,w.y,Date.now());this.gesture={mode:id?'node':'pan',id,start:{...p},last:{...p},moved:false}},
 orgMove(e){this.particleTouchMove?.(e);const touches=e.touches||[],s=this.orgScene,g=this.gesture;if(!s||!g||!touches.length)return;if(touches.length>1){const m=this.midpoint(touches);if(g.mode!=='pinch'){O.endDrag(s,Date.now(),true);this.gesture={mode:'pinch',...m,moved:true};return}O.pan(s,m.x-g.x,m.y-g.y);O.setZoom(s,s.view.zoom*m.d/Math.max(1,g.d),m.x,m.y);this.gesture={mode:'pinch',...m,moved:true};this.publishScene();return}const p=this.point(touches[0]);if(g.mode==='pinch'){this.gesture={mode:'pan',start:{...p},last:{...p},moved:true};return}if(Math.hypot(p.x-g.start.x,p.y-g.start.y)>7)g.moved=true;if(g.moved){if(g.mode==='node'){const w=O.unproject(s,p.x,p.y);O.drag(s,w.x,w.y,Date.now())}else O.pan(s,p.x-g.last.x,p.y-g.last.y);g.last={...p};this.publishScene()}},
 orgEnd(e){this.particleTouchEnd?.(e);const s=this.orgScene,g=this.gesture;if(!s)return;if(e.touches?.length){O.endDrag(s,Date.now(),true);const p=this.point(e.touches[0]);this.gesture={mode:'pan',start:{...p},last:{...p},moved:true};return}O.endDrag(s,Date.now(),e.type==='touchcancel');this.gesture=null;if(g&&!g.moved&&g.id&&e.type!=='touchcancel'){const n=O.node(s,g.id);if(n?.kind==='department')this.department({currentTarget:{dataset:{dept:n.dept}}});else if(n?.kind==='person')this.person({currentTarget:{dataset:{id:n.person.id}}})}this.publishScene()},
 zoomIn(){O.setZoom(this.ensureScene(),this.orgScene.view.zoom*1.18);this.publishScene()},zoomOut(){O.setZoom(this.ensureScene(),this.orgScene.view.zoom/1.18);this.publishScene()},center(){O.resetView(this.ensureScene());this.publishScene()},closePerson(){this.setData({selectedPerson:null})},person(e){const p=this.members.find(p=>p.id===e.currentTarget.dataset.id);if(p)this.setData({selectedPerson:this.data.selectedPerson?.id===p.id?null:p})},
 async review(e){const d=e.currentTarget.dataset;await V.action(this,async()=>{await V.api.mutate('profile/review',{id:d.id,revision:Number(d.revision),action:d.action});await this.load();wx.showToast({title:UI.t('审核已同步')})})}
}));
