const V=require('../../utils/view'),O=require('../../utils/organization'),F=require('../../utils/floating');
Page(V.page({
 data:{department:'',groups:[],reviews:[],expanded:[],positions:[[23,22],[77,22],[23,72],[77,72]]},
 renderState(s){this.user=s.user;this.setData({manager:s.manager,admin:s.user.role==='admin'});this.load();if(s.settings?.motion===false)this.stopMotion();else if(!this.hidden)this.startMotion()},
 onShow(){this.hidden=false;this.measureBoard();if(this.data.motion!==false)this.startMotion()},
 onHide(){this.hidden=true;this.stopMotion()},onUnload(){this.stopMotion()},
 measureBoard(){const q=wx.createSelectorQuery?.();q?.in(this).select('.bubble-board').boundingClientRect(r=>{if(r?.width&&r?.height){this.boardSize=r;this.filterGroups()}}).exec()},
 startMotion(){if(this.motionTimer||this.data.motion===false)return;this.springNodes||=F.create(this.data.positions);this.motionTime||=0;this.lastMotion=Date.now();this.motionTimer=setInterval(()=>this.animateMotion(),33)},
 stopMotion(){clearInterval(this.motionTimer);this.motionTimer=null},
 animateMotion(){if(!this.data.network?.length||this.data.selectedPerson)return;const now=Date.now(),dt=Math.min(.04,(now-this.lastMotion)/1000);this.lastMotion=now;this.motionTime+=dt;const paused=this.data.network.filter(g=>g.expanded||this.drag?.index===g.index).map(g=>g.index);F.step(this.springNodes,this.data.positions,this.motionTime,dt,paused);const patch={};this.springNodes.forEach((n,i)=>{const l=F.line(n.x,n.y,this.boardSize?.width,this.boardSize?.height);for(const [k,v]of Object.entries({x:n.x,y:n.y,...l}))patch[`network[${i}].${k}`]=Number(v.toFixed(3))});this.setData(patch)},
 async load(){if(this.loading)return;this.loading=true;try{const b=await V.api.call('members');this.members=b.members.map(m=>({...m,roleLabel:V.roles[m.role],statusLabel:{active:'已开通',pending:'待审核',disabled:'已停用'}[m.status],canEdit:!m.owner&&m.id!==this.user.id&&(this.user.role==='admin'||this.data.manager&&m.dept===this.user.dept&&m.role==='member')}));this.setData({reviews:b.reviews||[],allGroups:O.groups(this.members)});this.filterGroups()}catch(e){this.setData({syncError:e.message})}finally{this.loading=false}},
 filterGroups(){this.setData({network:O.groups(this.members||[]).map((g,i)=>{const n=this.springNodes?.[i],[x,y]=n?[n.x,n.y]:this.data.positions[i];return {...g,index:i,x,y,...F.line(x,y,this.boardSize?.width,this.boardSize?.height),expanded:this.data.expanded.includes(g.dept),people:g.people.filter(p=>p.status==='active').sort((a,b)=>({admin:0,manager:1,member:2}[a.role])-({admin:0,manager:1,member:2}[b.role]))}}),groups:O.groups(this.members||[]).filter(g=>!this.data.department||g.dept===this.data.department)})},
 department(e){const d=e.currentTarget.dataset.dept||'';this.setData({department:'',expanded:d?(this.data.expanded.includes(d)?this.data.expanded.filter(x=>x!==d):[...this.data.expanded,d]):V.depts});this.filterGroups()},
 dragStart(e){const index=Number(e.currentTarget.dataset.index),n=this.springNodes?.[index];this.drag={index,x:e.touches[0].clientX,y:e.touches[0].clientY,pos:n?[n.x,n.y]:this.data.positions[index]};this.moved=false},
 dragMove(e){if(!this.drag)return;const t=e.touches[0],dx=t.clientX-this.drag.x,dy=t.clientY-this.drag.y;if(Math.abs(dx)+Math.abs(dy)<8&&!this.moved)return;this.moved=true;const positions=this.data.positions.slice(),i=this.drag.index;positions[i]=[Math.max(17,Math.min(83,this.drag.pos[0]+dx/(this.boardSize?.width||340)*100)),Math.max(16,Math.min(82,this.drag.pos[1]+dy/(this.boardSize?.height||370)*100))];this.springNodes||=F.create(positions);Object.assign(this.springNodes[i],{x:positions[i][0],y:positions[i][1],vx:0,vy:0});this.setData({positions});this.filterGroups()},
 dragEnd(){this.drag=null},toggleDepartment(e){this.dragEnd();if(this.moved){this.moved=false;return}this.department(e)},
 closePerson(){this.setData({selectedPerson:null})},person(e){const p=this.members.find(p=>p.id===e.currentTarget.dataset.id);if(p)this.setData({selectedPerson:this.data.selectedPerson?.id===p.id?null:p})},
 async review(e){const d=e.currentTarget.dataset;await V.action(this,async()=>{await V.api.mutate('profile/review',{id:d.id,revision:Number(d.revision),action:d.action});await this.load();wx.showToast({title:'审核已同步'})})}
}));
