// Cropping is local. Only the re-encoded square JPEG is added to the profile draft.
(() => {
 let active=null,pendingEpoch=0,pendingSave=null;
 const text=(zh,en)=>typeof prefs==='function'&&prefs().language==='en'?en:zh;
 const clamp=(n,min,max)=>Math.max(min,Math.min(max,n));
 function constrain(g){const scale=g.base*g.zoom;g.x=clamp(g.x,g.size-g.width*scale,0);g.y=clamp(g.y,g.size-g.height*scale,0)}
 function zoom(g,value,x=g.size/2,y=g.size/2){const previous=g.base*g.zoom;g.zoom=clamp(value,1,4);g.x=x-(x-g.x)/previous*g.base*g.zoom;g.y=y-(y-g.y)/previous*g.base*g.zoom;constrain(g)}
 function cleanup(){const item=active;if(!item)return;active=null;item.bitmap?.close?.();item.dialog.close();item.dialog.remove();item.fileInput.value='';pendingSave=null;if(item.saveButton)item.saveButton.disabled=item.saveDisabled}
 function showError(message){const node=document.querySelector('#form-error');if(node)node.textContent=message;else if(typeof toast==='function')toast(message)}
 document.addEventListener('change',async event=>{
  const input=event.target;if(!(input instanceof HTMLInputElement)||!input.matches('[data-avatar-upload]'))return;
  event.stopImmediatePropagation();const file=input.files?.[0],form=input.closest('#profile-form');if(!file||!form)return;
  cleanup();const sourceOwner=typeof user==='object'?user?.id:null,epoch=++pendingEpoch,saveButton=document.querySelector('[data-profile-save]'),saveDisabled=pendingSave?.button===saveButton?pendingSave.initial:saveButton?.disabled;pendingSave={button:saveButton,initial:saveDisabled};if(saveButton)saveButton.disabled=true;
  let bitmap,dialog;
  try{
   if(file.size>10*1024*1024)throw Error(text('请选择 10 MB 以内的图片','Choose an image smaller than 10 MB'));
   if(!/^image\/(png|jpeg|webp)$/i.test(file.type))throw Error(text('请选择 PNG、JPEG 或 WebP 图片','Choose a PNG, JPEG or WebP image'));
   bitmap=await createImageBitmap(file);if(bitmap.width*bitmap.height>64000000)throw Error(text('图片尺寸过大，请先缩小','This image is too large. Resize it first.'));
   if(epoch!==pendingEpoch){bitmap.close();return}if(!form.isConnected||sourceOwner!==(typeof user==='object'?user?.id:null)){bitmap.close();pendingSave=null;if(saveButton)saveButton.disabled=saveDisabled;return}
   dialog=document.createElement('dialog');dialog.className='avatar-crop-dialog';dialog.setAttribute('aria-label',text('调整头像','Adjust avatar'));
   dialog.innerHTML=`<div class="avatar-crop-header"><h2>${text('调整头像','Adjust avatar')}</h2><button type="button" data-avatar-cancel aria-label="${text('取消','Cancel')}">×</button></div><p class="sub">${text('拖动照片移动位置，双指或滑块缩放。','Drag to reposition. Pinch or use the slider to zoom.')}</p><div class="avatar-crop-stage" tabindex="0" aria-label="${text('头像裁剪预览，方向键调整位置','Avatar crop preview. Use arrow keys to reposition')}" role="img"><canvas aria-hidden="true"></canvas><div class="avatar-crop-circle"></div></div><p class="avatar-crop-preview-label">${text('圆形预览','Circular preview')}</p><label class="avatar-zoom-field">${text('缩放','Zoom')} <output>100%</output><input type="range" min="100" max="400" step="5" value="100" aria-label="${text('头像缩放','Avatar zoom')}"></label><button type="button" class="text-btn" data-avatar-reset>${text('重置位置','Reset position')}</button><p class="avatar-crop-error" role="alert"></p><div class="avatar-crop-actions"><button type="button" class="secondary" data-avatar-cancel>${text('取消','Cancel')}</button><button type="button" class="primary" data-avatar-apply>${text('使用头像','Use avatar')}</button></div>`;
   document.body.append(dialog);dialog.showModal();const stage=dialog.querySelector('.avatar-crop-stage'),canvas=stage.querySelector('canvas'),size=stage.clientWidth,dpr=Math.min(2,devicePixelRatio||1);canvas.width=canvas.height=Math.round(size*dpr);const ctx=canvas.getContext('2d');if(!ctx)throw Error('Canvas unavailable');ctx.scale(dpr,dpr);
   const base=Math.max(size/bitmap.width,size/bitmap.height),g={width:bitmap.width,height:bitmap.height,size,base,zoom:1,x:(size-bitmap.width*base)/2,y:(size-bitmap.height*base)/2};
   active={dialog,bitmap,fileInput:input,form,saveButton,saveDisabled,owner:sourceOwner};const pointers=new Map();let gesture=null;
   const draw=()=>{ctx.clearRect(0,0,size,size);ctx.drawImage(bitmap,g.x,g.y,g.width*g.base*g.zoom,g.height*g.base*g.zoom);dialog.querySelector('output').textContent=Math.round(g.zoom*100)+'%';dialog.querySelector('input[type=range]').value=Math.round(g.zoom*100)};
   const restartGesture=()=>{const points=[...pointers.values()];gesture=points.length?{points,x:g.x,y:g.y,zoom:g.zoom,distance:points.length>1?Math.hypot(points[0].x-points[1].x,points[0].y-points[1].y):0}:null};
   stage.addEventListener('pointerdown',e=>{if(e.button!==0)return;const r=stage.getBoundingClientRect();pointers.set(e.pointerId,{x:e.clientX-r.left,y:e.clientY-r.top});stage.setPointerCapture(e.pointerId);restartGesture()});
   stage.addEventListener('pointermove',e=>{if(!pointers.has(e.pointerId)||!gesture)return;const r=stage.getBoundingClientRect();pointers.set(e.pointerId,{x:e.clientX-r.left,y:e.clientY-r.top});const points=[...pointers.values()];if(points.length>=2&&gesture.distance){const distance=Math.hypot(points[0].x-points[1].x,points[0].y-points[1].y);zoom(g,gesture.zoom*distance/gesture.distance,(points[0].x+points[1].x)/2,(points[0].y+points[1].y)/2)}else if(gesture.points.length===1){g.x=gesture.x+points[0].x-gesture.points[0].x;g.y=gesture.y+points[0].y-gesture.points[0].y;constrain(g)}draw()});
   const end=e=>{pointers.delete(e.pointerId);restartGesture()};stage.addEventListener('pointerup',end);stage.addEventListener('pointercancel',end);
   stage.addEventListener('keydown',e=>{const directions={ArrowLeft:[10,0],ArrowRight:[-10,0],ArrowUp:[0,10],ArrowDown:[0,-10]};if(!directions[e.key])return;e.preventDefault();g.x+=directions[e.key][0];g.y+=directions[e.key][1];constrain(g);draw()});
   stage.addEventListener('wheel',e=>{e.preventDefault();const r=stage.getBoundingClientRect();zoom(g,g.zoom*Math.exp(-e.deltaY*.0015),e.clientX-r.left,e.clientY-r.top);draw()},{passive:false});
   dialog.querySelector('input[type=range]').addEventListener('input',e=>{zoom(g,Number(e.target.value)/100);draw()});
   dialog.querySelector('[data-avatar-reset]').addEventListener('click',()=>{g.zoom=1;g.x=(size-g.width*base)/2;g.y=(size-g.height*base)/2;draw()});
   for(const button of dialog.querySelectorAll('[data-avatar-cancel]'))button.addEventListener('click',cleanup);dialog.addEventListener('cancel',e=>{e.preventDefault();cleanup()});dialog.addEventListener('click',e=>{if(e.target===dialog)cleanup()});
   dialog.querySelector('[data-avatar-apply]').addEventListener('click',()=>{try{if(!active?.form.isConnected||active.owner!==(typeof user==='object'?user?.id:null)){cleanup();return}const output=document.createElement('canvas'),scale=g.base*g.zoom,sx=-g.x/scale,sy=-g.y/scale,side=size/scale;let avatar='';for(const [dimension,quality]of [[256,.7],[256,.5],[192,.55],[128,.6]]){output.width=output.height=dimension;const out=output.getContext('2d');out.fillStyle='#ffffff';out.fillRect(0,0,dimension,dimension);out.drawImage(bitmap,sx,sy,side,side,0,0,dimension,dimension);avatar=output.toDataURL('image/jpeg',quality);if(avatar.length<=14000)break}if(avatar.length>18000)throw Error(text('头像过于复杂，请换一张图片','This image is too complex. Choose another image.'));form.dataset.avatar=avatar;const preview=form.querySelector('#profile-preview');if(preview){preview.replaceChildren();const image=document.createElement('img');image.className='avatar';image.src=avatar;image.alt=text('新头像预览','New avatar preview');preview.append(image)}cleanup()}catch{dialog.querySelector('.avatar-crop-error').textContent=text('裁剪暂未完成，请重新选择图片。','The crop could not finish. Choose the image again.')}});
   draw();dialog.querySelector('[data-avatar-apply]').focus();
  }catch(error){if(active?.dialog===dialog)cleanup();else if(dialog?.isConnected){dialog.close();dialog.remove()}bitmap?.close?.();if(epoch!==pendingEpoch)return;pendingSave=null;if(saveButton)saveButton.disabled=saveDisabled;input.value='';showError(error?.name==='Error'&&/^(请选择|图片尺寸|Choose |This image)/.test(error.message)?error.message:text('暂时无法读取这张图片，请重试。','Could not read this image. Try again.'))}
 },true);
})();
