// Organization and personal contribution iteration.
const departmentColors=['#168875','#d47918','#3478c5','#8b5bc7'];
const deptColor=dept=>departmentColors[depts.indexOf(dept)]||'#777';
let organizationDept='',profileReviews=[];
function avatarMarkup(p){return p.avatar?`<img class="avatar" src="${esc(p.avatar)}" alt="${esc(p.name)}的头像">`:`<span class="avatar">${esc(p.name?.[0]||'?')}</span>`}
function requesterField(value){const match=state.people.find(p=>p.name===value);return `<select name="requesterChoice" data-requester><option value="">未指定</option>${peopleOptions(match?.id)}<option value="other" ${value&&!match?'selected':''}>其他 · 填写姓名</option></select><input name="requester" maxlength="100" value="${esc(value)}" ${value&&!match?'':'hidden'} placeholder="填写其他对接人姓名">`}
const priorEventPayload=eventPayload;
eventPayload=function(f){const d=priorEventPayload(f);d.requester=d.requesterChoice==='other'?d.requester:state.people.find(p=>p.id===d.requesterChoice)?.name||'';return d};
function leaderboard(){return `<section class="panel leaderboard"><div class="panel-head"><h2>贡献排行榜</h2><button class="text-btn" data-view="rewards">成果与贡献 →</button></div>${(state.ranking||[]).slice(0,5).map((p,i)=>`<div class="asset-row"><b class="rank">${i+1}</b>${avatarMarkup(p)}<div class="task-copy"><h3>${esc(p.name)}</h3><p>${esc(p.dept)}</p></div><b style="color:${deptColor(p.dept)}">${p.points} 分</b></div>`).join('')||'<p class="empty">验收完成后累计积分</p>'}</section>`}
const communityOverview=overview;
overview=function(){return communityOverview()+leaderboard()};
tasksView=function(){const mine=state.tasks.filter(t=>t.owner===user.id||t.receiver===user.id);return head('我的任务','按大任务展开，查看你负责和验收的子任务。')+state.events.filter(e=>mine.some(t=>t.event===e.id)).map(e=>{const ts=mine.filter(t=>t.event===e.id);return `<details class="panel task-group" data-expand="${e.id}" open><summary><span>${esc(e.name)}</span><small>${ts.filter(t=>t.status==='done').length} / ${ts.length} 子任务完成</small></summary>${ts.map(taskRow).join('')}</details>`}).join('')+(!mine.length?'<div class="panel empty">暂无任务</div>':'')};
const contributionRewards=rewardsView;
rewardsView=function(){return contributionRewards().replace('我的积分','成果与贡献')+`<section class="panel"><div class="panel-head"><h2>成果归档</h2></div>${state.tasks.filter(t=>t.submission).map(taskRow).join('')||'<div class="empty">提交成果后在此归档</div>'}</section>`};
function organizationGraph(){return `<section class="panel organization"><div class="panel-head"><h2>学媒协作网络</h2><button class="text-btn" data-org-dept="">显示全部</button></div><p class="sub">点击部门筛选成员；点击成员查看资料。连线表示组织归属。</p><div class="org-map"><div class="org-center">冯如学媒<small>${members.filter(p=>p.status==='active').length} 名成员</small></div>${depts.map(dept=>`<div class="org-cluster ${organizationDept&&organizationDept!==dept?'dimmed':''}" style="--dept-color:${deptColor(dept)}"><button class="org-department" data-org-dept="${esc(dept)}">${esc(dept)}</button><div class="org-nodes">${members.filter(p=>p.dept===dept&&p.status==='active').map(p=>`<button class="org-node" data-person="${p.id}" title="${esc(p.name)} · ${roleNames[p.role]}">${avatarMarkup(p)}<span>${esc(p.name)}</span></button>`).join('')||'<span class="sub">暂无成员</span>'}</div></div>`).join('')}</div></section>`}
membersView=function(){return head('成员与权限','',manager()?'<button class="primary" data-invite>＋ 邀请成员</button>':'')+organizationGraph()+(admin()?`<section class="panel"><div class="panel-head"><h2>姓名与头像审核</h2></div>${profileReviews.map(p=>`<div class="asset-row">${avatarMarkup({name:p.pending_name,avatar:p.pending_avatar})}<div class="task-copy"><h3>${esc(p.name)} → ${esc(p.pending_name)}</h3><p>${esc(p.dept)} · 申请修改个人资料</p></div><button class="secondary" data-profile-review="${p.user}" data-revision="${p.revision}" data-decision="reject">退回</button><button class="primary" data-profile-review="${p.user}" data-revision="${p.revision}" data-decision="approve">批准</button></div>`).join('')||'<div class="empty">暂无待审核资料</div>'}</section>`:'')+depts.filter(d=>!organizationDept||d===organizationDept).map(dept=>`<section class="panel" style="border-top:3px solid ${deptColor(dept)}"><div class="panel-head"><h2>${esc(dept)} <span class="count">${members.filter(p=>p.dept===dept).length}</span></h2></div>${members.filter(p=>p.dept===dept).map(p=>`<div class="asset-row">${avatarMarkup(p)}<div class="task-copy"><h3>${esc(p.name)}</h3><p>${roleNames[p.role]} · @${esc(p.username)}</p></div>${presenceMarkup(p)}<span class="badge ${p.status}">${{active:'已开通',pending:'待审核',disabled:'已停用'}[p.status]}</span>${!p.owner&&p.id!==user.id&&(admin()||manager()&&p.dept===user.dept&&p.role==='member')?`<button class="secondary" data-member="${p.id}">管理</button>`:''}</div>`).join('')||'<div class="empty">暂无成员</div>'}</section>`).join('')};
const communityRefresh=refresh;
refresh=async function(){if(view==='members'){const b=await api('members');profileReviews=b.reviews||[]}return communityRefresh()};
const expansionStates=new Map();
document.addEventListener('toggle',e=>{if(e.target.matches?.('[data-expand]'))expansionStates.set(e.target.dataset.expand,e.target.open)},true);
const communityRender=render;
render=function(){communityRender();document.querySelectorAll('[data-expand]').forEach(el=>{if(expansionStates.has(el.dataset.expand))el.open=expansionStates.get(el.dataset.expand)});document.querySelectorAll('[data-task]').forEach(el=>{const t=state.tasks.find(t=>t.id===el.dataset.task);if(t)el.style.setProperty('--dept-color',deptColor(t.dept))});document.querySelectorAll('.cal-event.activity,.time-bar').forEach(el=>{const id=el.dataset.event||el.querySelector('[data-event]')?.dataset.event;const dept=calendarDept||state.tasks.find(t=>t.event===id)?.dept;el.style.setProperty('--dept-color',deptColor(dept))});$('.schedule-panel')?.style.setProperty('--dept-color',deptColor(calendarDept));};
function profileForm(){const p=state.profile;modal('个人资料',`<form id="profile-form" data-avatar="${esc(user.avatar||'')}"><div id="profile-preview">${avatarMarkup(user)}</div><label class="field">姓名<input name="name" required maxlength="30" value="${esc(user.name)}"></label><label class="field">头像<input type="file" accept="image/png,image/jpeg,image/webp" data-avatar-upload></label><button class="text-btn" type="button" data-avatar-clear>移除头像</button><p class="hint">姓名与头像修改需管理员审核。</p>${p?.review_status==='pending'?`<p class="hint">待审核姓名：${esc(p.pending_name)}。重新提交将替换原申请。</p>`:p?.review_status==='rejected'?`<p class="hint">上次申请已退回：${esc(p.review_note||'请调整后重新提交')}</p>`:''}</form>`,`<button class="secondary" data-password>修改密码</button><button class="primary" data-profile-save>提交审核</button>`)}
document.addEventListener('change',async e=>{if(e.target.matches('[data-requester]')){const input=e.target.form.elements.requester;input.hidden=e.target.value!=='other';if(!input.hidden)input.focus()}if(e.target.matches('[data-avatar-upload]')){const file=e.target.files[0];if(!file)return;try{if(file.size>10*1024*1024)throw Error('请选择 10 MB 以内的图片');const bitmap=await createImageBitmap(file),canvas=document.createElement('canvas');canvas.width=canvas.height=112;const ctx=canvas.getContext('2d'),size=Math.min(bitmap.width,bitmap.height);ctx.drawImage(bitmap,(bitmap.width-size)/2,(bitmap.height-size)/2,size,size,0,0,112,112);bitmap.close();const data=canvas.toDataURL('image/webp',.65);if(data.length>18000)throw Error('图片过于复杂，请选择更简单的头像');$('#profile-form').dataset.avatar=data;$('#profile-preview').innerHTML=avatarMarkup({name:user.name,avatar:data})}catch(err){$('#form-error').textContent=err.message}}});
document.addEventListener('click',async e=>{const d=e.target.closest('button')?.dataset;if(!d)return;try{if(d.profile!==undefined)profileForm();if(d.avatarClear!==undefined){$('#profile-form').dataset.avatar='';$('#profile-preview').innerHTML=avatarMarkup({name:user.name})}if(d.profileSave!==undefined){const f=$('#profile-form');if(!f.reportValidity())return;await api('profile/request',{name:f.elements.name.value,avatar:f.dataset.avatar});$('#dialog').close();await refresh();toast('已提交，等待管理员审核')}if(d.profileReview){await api('profile/review',{id:d.profileReview,revision:Number(d.revision),action:d.decision});await refresh();toast(d.decision==='approve'?'资料已批准并同步':'申请已退回')}if(d.orgDept!==undefined){organizationDept=d.orgDept;if(typeof expandOrganization==='function')expandOrganization(d.orgDept);else render()}if(d.person&&!aeroOrganizationActive()){const p=members.find(x=>x.id===d.person);if(p)modal(p.name,`${avatarMarkup(p)}<p>${esc(p.dept)} · ${roleNames[p.role]}</p>`)} }catch(err){if($('#dialog').open)$('#form-error').textContent=err.message;else toast(err.message)}});
// One accessible department -> member control for every personnel select.
let cascadeSerial=0;
function upgradePeopleSelectors(){document.querySelectorAll('#dialog select').forEach(select=>{if(!select.querySelector('optgroup')||select.dataset.cascade)return;const key='person-selector-'+(++cascadeSerial);select.id=key;select.dataset.cascade='1';select.classList.add('cascade-native');select.tabIndex=-1;const menu=document.createElement('details');menu.className='person-cascade';menu.dataset.select=key;menu.innerHTML=`<summary>${esc(select.selectedOptions[0]?.textContent||'请选择')} ▾</summary><div class="cascade-panel">${[...select.children].map(child=>child.tagName==='OPTGROUP'?`<details class="cascade-department"><summary>${esc(child.label)}</summary><div>${[...child.children].map(o=>`<button type="button" data-select-person="${key}" data-value="${esc(o.value)}">${esc(o.textContent)}</button>`).join('')}</div></details>`:`<button type="button" data-select-person="${key}" data-value="${esc(child.value)}">${esc(child.textContent)}</button>`).join('')}</div>`;select.after(menu);select.addEventListener('change',()=>menu.querySelector(':scope > summary').textContent=(select.selectedOptions[0]?.textContent||'请选择')+' ▾');select.addEventListener('invalid',()=>{menu.open=true;menu.querySelector('summary').focus()});})}
new MutationObserver(upgradePeopleSelectors).observe($('#dialog-body'),{childList:true,subtree:true});
document.addEventListener('click',e=>{const b=e.target.closest('[data-select-person]');if(!b)return;e.preventDefault();const select=document.getElementById(b.dataset.selectPerson);select.value=b.dataset.value;select.dispatchEvent(new Event('change',{bubbles:true}));b.closest('.person-cascade').open=false;});
