// Local workbench v2: events, reusable workflows, contribution ledger and shared schedule.
let sopDocuments=[],sopLoading=false,calendarDept='',timelineScale=68,selectedDay='';
const canEditEvent=e=>!!e&&(admin()||manager()&&e.createdBy===user.id);
const localDay=(d=new Date())=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const dayShift=(s,n)=>{const d=new Date(s+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10)};
const dayDiff=(a,b)=>Math.round((Date.parse(a.slice(0,10))-Date.parse(b.slice(0,10)))/86400000);
const externalLink=(url,label,extra='')=>url?`<a class="secondary link-button" href="${esc(url)}" target="_blank" rel="noopener noreferrer" ${extra}>${esc(label)} ↗</a>`:'';
const eventTime=e=>`${dateText(e.date)}${e.allDay===false?' '+esc(e.startTime):' · 全天'}${e.endDate&&e.endDate!==e.date?' — '+dateText(e.endDate):''}${e.allDay===false?' — '+esc(e.endTime):''}`;
const visibleEvents=()=>state.events.filter(e=>!calendarDept||state.tasks.some(t=>t.event===e.id&&t.dept===calendarDept));
const visibleTasks=()=>state.tasks.filter(t=>!calendarDept||t.dept===calendarDept);
function rewardFields(value={}) {return `<div class="form-grid"><label class="field">每项任务积分<input name="rewardPoints" type="number" min="0" max="10000" step="1" value="${Number(value.rewardPoints||0)}"></label><label class="field">其他奖励备注<input name="rewardNote" maxlength="500" value="${esc(value.rewardNote||'')}" placeholder="如：优秀作品展示、实践证明"></label></div><p class="sub">任务验收通过后积分入账一次。活动中的设置用于新任务，已有任务可在调整分工中修改。</p>`}

// Keep open forms intact while refreshing data; mutations and sibling tabs refresh immediately.
const baseApi=api;
let refreshSerial=0;
const baseRender=render,timelinePositions=new Map();
render=function(){
  const previous=$('.time-scroll');if(previous)timelinePositions.set(previous.dataset.month,previous.scrollLeft);
  baseRender();const scroll=$('.time-scroll');if(scroll){const key=`${year}-${month}`;scroll.dataset.month=key;scroll.scrollLeft=timelinePositions.get(key)??(year===new Date().getFullYear()&&month===new Date().getMonth()?Math.max(0,new Date().getDate()-3)*timelineScale:0)}
};
const baseAuth=auth;
auth=function(...args){baseAuth(...args);const mark=$('.auth-brand .mark');if(mark)mark.outerHTML='<img class="brand-wordmark" src="/brand/wordmark.png" alt="冯如书院 FENGRU COLLEGE">'};
refresh=async function(){
  const serial=++refreshSerial,next=await baseApi('state');
  const nextMembers=view==='members'&&['admin','manager'].includes(next.user.role)?(await baseApi('members')).members:members;
  if(serial!==refreshSerial)return;
  state=next;user=state.user;members=nextMembers;render();
};
const syncChannel=typeof BroadcastChannel==='function'?new BroadcastChannel('fengru-workbench-v2'):null;
if(syncChannel)syncChannel.onmessage=()=>{if(user?.status==='active')refresh().catch(()=>{})};
api=async function(path,data){const result=await baseApi(path,data);if(data&&user?.status==='active'&&!['login','logout','register','setup','recover'].includes(path)){syncChannel?.postMessage('changed');await refresh()}return result};

const oldOverview=overview;
overview=function(){const body=oldOverview();const pos=body.indexOf('<div class="overview-grid">');return body.slice(0,pos)+timelineView()+body.slice(pos)};

function eventFields(e={}){
  const day=e.date||localDay();
  return `<label class="field">活动名称<input name="name" required maxlength="60" value="${esc(e.name||'')}" placeholder="添加活动标题"></label>
    <label class="check-line"><input type="checkbox" name="allDay" ${e.allDay!==false?'checked':''}> 全天</label>
    <div class="form-grid"><label class="field">开始日期<input type="date" name="date" required value="${day}"></label><label class="field">结束日期<input type="date" name="endDate" required value="${e.endDate||day}"></label></div>
    <div class="form-grid time-fields" ${e.allDay!==false?'hidden':''}><label class="field">开始时间<input type="time" name="startTime" value="${e.startTime||'09:00'}"></label><label class="field">结束时间<input type="time" name="endTime" value="${e.endTime||'10:00'}"></label></div>
    <label class="field">地点（可选）<input name="location" maxlength="100" value="${esc(e.location||'')}" placeholder="添加地点或线上会议位置"></label>
    <div class="form-grid"><label class="field">需求来源<select name="source">${options(['学媒自有','外派需求'],e.source||'学媒自有')}</select></label><label class="field">需求方 / 对接人（可选）<input name="requester" maxlength="100" value="${esc(e.requester||'')}" placeholder="办公室统一登记外派需求"></label></div>
    <label class="field">活动说明与交付目标<textarea name="description" maxlength="3000" placeholder="安排、参与范围、期望成果和注意事项">${esc(e.description||'')}</textarea></label>
    <label class="field">活动素材库 · 云盘上传链接（可稍后添加）<input type="url" name="cloudUrl" maxlength="2000" value="${esc(e.cloudUrl||'')}" placeholder="https://…"></label>
    <p class="sub">请提供成员有上传权限的文件夹链接；接活人会在任务详情和提交页面看到入口。</p>
    <details class="form-section" ${e.rewardPoints||e.rewardNote?'open':''}><summary>积分与其他奖励</summary>${rewardFields(e)}</details>`;
}
createForm=function(template='blank'){
  modal('新建活动',`<form id="create-form"><label class="field">活动模板<select name="template"><option value="blank">空白日程 · 自由创建</option>${(state.templates||[]).map(t=>`<option value="${t.id}" ${template===t.id?'selected':''}>${esc(t.name)} · ${t.steps.length} 个环节</option>`).join('')}</select></label>${eventFields()}<div id="template-assignment"></div></form>`,`<button class="primary" type="submit" form="create-form">创建活动</button>`);
  renderAssignments();
};
function renderAssignments(){
  const template=(state.templates||[]).find(t=>t.id===$('#create-form [name=template]').value);
  $('#template-assignment').innerHTML=template?`<h3 class="detail-label">确认任务分工</h3><p class="sub">${esc(template.description||'')} 模板会复制为本活动任务，后续修改模板不会改动已创建活动。</p>${template.steps.map((s,i)=>`<fieldset class="assignment" data-assignment="${i}"><legend>${i+1}. ${esc(s.name)}</legend><p class="sub">${esc(s.dept)} · 活动${s.offset<0?'前':'后'} ${Math.abs(s.offset)} 天 ${s.time}</p><div class="form-grid"><label class="field">负责人<select name="owner-${i}" required><option value="">请选择</option>${peopleOptions(state.people.find(p=>p.dept===s.dept)?.id)}</select></label><label class="field">验收人<select name="receiver-${i}">${peopleOptions(user.id)}</select></label></div></fieldset>`).join('')}`:'<div class="hint">只创建日程，不自动派单。创建后可按需添加任务，也可将活动流程保存成模板。</div>';
}
function eventPayload(f){const d=Object.fromEntries(new FormData(f));return {...d,allDay:f.elements.allDay.checked,assignments:[...f.querySelectorAll('[data-assignment]')].map(el=>({owner:el.querySelector('[name^=owner-]').value,receiver:el.querySelector('[name^=receiver-]').value}))}}
function editEvent(id){const e=state.events.find(x=>x.id===id);modal('编辑活动',`<form id="event-edit-form" data-id="${id}">${eventFields(e)}<p class="hint">调整开始日期时，未完成任务同步平移；已完成任务和已发积分保留。</p></form>`,`<button class="primary" type="submit" form="event-edit-form">保存活动</button>`)}
function addTaskForm(id){const e=state.events.find(x=>x.id===id),ts=state.tasks.filter(t=>t.event===id);modal('添加活动任务',`<form id="task-new-form" data-event="${id}"><p class="sub">${esc(e.name)}</p><label class="field">任务名称<input name="name" required maxlength="100"></label><div class="form-grid"><label class="field">负责人<select name="owner">${peopleOptions(user.id)}</select></label><label class="field">验收人<select name="receiver">${peopleOptions(user.id)}</select></label></div><label class="field">截止时间<input name="due" type="datetime-local" value="${e.date}T${e.endTime||'18:00'}" required></label><label class="field">交付要求<textarea name="requirements" required maxlength="3000" placeholder="明确交付物、验收标准和交接说明"></textarea></label><details class="form-section"><summary>前序依赖（可选）</summary><p class="sub">所选任务全部验收后，才可以接受此任务。</p>${ts.map(t=>`<label class="check-line"><input type="checkbox" name="depends" value="${t.id}">${esc(t.name)}</label>`).join('')||'<p class="sub">当前还没有前序任务</p>'}</details>${rewardFields(e)}</form>`,`<button class="primary" form="task-new-form" type="submit">添加并派单</button>`)}
function cloudBlock(e){return e.cloudUrl?`<div class="cloud-card"><div><h3>活动素材库</h3><p class="sub">上传到活动统一文件夹，便于跨部门交接。</p></div><div class="actions">${externalLink(e.cloudUrl,'打开云盘上传')}<button type="button" class="text-btn" data-copy-url="${esc(e.cloudUrl)}">复制链接</button></div></div>`:'<p class="sub">暂未设置活动素材库，可由活动负责人稍后补充。</p>'}
function showEvent(id){const e=state.events.find(x=>x.id===id);if(!e)return;const ts=state.tasks.filter(t=>t.event===id);modal(e.name,`<p class="event-kicker">${esc(e.type||'自由活动')} · ${esc(e.source||'学媒自有')}</p><h3>${eventTime(e)}</h3><p class="sub">${esc(e.location||'地点待定')}${e.requester?' · 对接：'+esc(e.requester):''}</p><p class="detail-copy">${esc(e.description||'暂无补充说明')}</p>${cloudBlock(e)}<p class="reward-label">新任务默认 ${e.rewardPoints||0} 积分${e.rewardNote?' · '+esc(e.rewardNote):''}</p><h3 class="detail-label">任务与交付</h3>${ts.map(taskRow).join('')||'<div class="empty">还没有任务，可以保留为日程或稍后添加分工。</div>'}`,canEditEvent(e)?`<button class="secondary" data-from-event="${id}">保存为模板</button><button class="secondary" data-event-edit="${id}">编辑活动</button><button class="primary" data-add-task="${id}">＋ 添加任务</button>`:'')}
activitiesView=function(){return head('活动协作','从空白日程开始，也可以复用团队流程。',manager()?'<button class="primary" data-create>＋ 新建活动</button>':'')+state.events.map(e=>{const ts=state.tasks.filter(t=>t.event===e.id);return `<section class="activity-card"><div class="activity-top"><div class="activity-title"><span class="event-kicker">${esc(e.type||'自由活动')} · ${esc(e.source||'学媒自有')}</span><h2><button class="title-button" data-event="${e.id}">${esc(e.name)}</button></h2><p>${eventTime(e)} · ${esc(e.location||'地点待定')}</p></div><div class="actions"><button class="secondary" data-event="${e.id}">活动详情</button>${canEditEvent(e)?`<button class="primary" data-add-task="${e.id}">＋ 任务</button>`:''}</div></div>${e.description?`<p class="detail-copy">${esc(e.description)}</p>`:''}${cloudBlock(e)}<div class="activity-progress"><span>${ts.filter(t=>t.status==='done').length} / ${ts.length} 项任务完成</span><span>任务奖励共 ${ts.reduce((n,t)=>n+(t.rewardPoints||0),0)} 积分</span></div><div class="flow">${ts.map((t,i)=>`<div class="flow-step" role="button" tabindex="0" data-task="${t.id}"><div class="step-num">${String(i+1).padStart(2,'0')} / ${esc(t.dept)}</div><h3>${esc(t.name)}</h3>${badge(t)}<p>${esc(person(t.owner))}</p><p>${dateText(t.due)}</p><span class="reward-label">+${t.rewardPoints||0} 积分</span></div>`).join('')}</div>${!ts.length?'<p class="sub">空白日程 · 尚未派单</p>':''}</section>`}).join('')+(!state.events.length?'<div class="panel empty">还没有活动。点击“新建活动”添加一个空白日程。</div>':'')};

const baseShowTask=showTask;
showTask=function(id){baseShowTask(id);const t=state.tasks.find(x=>x.id===id);if(!t)return;const e=ev(t);const content=$('#dialog .modal-content');content.insertAdjacentHTML('beforeend',`${cloudBlock(e)}<div class="reward-label">本任务 ${t.rewardPoints||0} 积分${t.rewardNote?' · '+esc(t.rewardNote):''}${t.status==='done'?' · 已验收入账':''}</div>${t.uploadReceipt?`<div class="hint">提交者已确认上传（${dateText(t.uploadReceipt.confirmedAt.slice(0,16))}）。${externalLink(t.uploadReceipt.url,'查看提交时的上传位置')}<p>此记录为成员确认，验收人仍需检查云盘内的实际文件。</p></div>`:''}`);if(t.owner===user.id&&t.status==='conflict'){$('#dialog-body').insertAdjacentHTML('beforeend',`<div class="modal-footer"><button class="primary" data-action="resume" data-id="${id}">冲突已解决，恢复接活</button></div>`)}};
function checkInformation(t,i){const e=ev(t);return i===0?`${e.name}\n时间：${eventTime(e).replace(/<[^>]+>/g,'')}\n地点：${e.location||'待定'}\n活动说明：${e.description||'无'}\n交付要求：${t.requirements}\n截止：${dateText(t.due)}\n验收人：${person(t.receiver)}`:`交接给：${person(t.receiver)}\n写清已完成内容、文件位置、版本及待注意事项。\n文件命名：日期_活动名_内容_序号。\n照片按场景分类并记录摄影署名；视频按机位/环节归类；设计保留可编辑源文件与导出图。\n${e.cloudUrl?'上传到本活动素材库，并确认接收人可访问。':'可附个人成果链接，并确认接收人可访问。'}`}
submitForm=function(id){const t=state.tasks.find(x=>x.id===id),e=ev(t);modal('提交成果',`<form id="submit-form" data-id="${id}" data-upload-url="${esc(e.cloudUrl||'')}"><div class="checklist">${t.checks.map((c,i)=>`<div class="check-detail"><label class="check-line"><input type="checkbox" name="check${i}" required><span>${esc(c)}</span></label><details class="check-help"><summary title="${esc(checkInformation(t,i))}">查看要求</summary><div class="check-popover">${esc(checkInformation(t,i))}</div></details></div>`).join('')}</div><label class="field" style="margin-top:20px">成果与交接说明<textarea name="submission" required maxlength="3000" placeholder="完成了什么、文件在哪里、有哪些交接事项">${esc(t.submission||'')}</textarea></label>${e.cloudUrl?`<section class="upload-section"><h3>上传到活动素材库</h3><p class="sub">先打开云盘完成上传，再返回确认。此处不会自动上传文件或验证云盘内容。</p>${externalLink(e.cloudUrl,'前往云盘上传','data-open-upload')}<label class="check-line"><input type="checkbox" name="uploadConfirmed" required disabled> 我已完成上传，并确认验收人能访问文件</label></section>`:''}<label class="field">个人成果链接（可选）<input name="link" type="url" maxlength="2000" value="${esc(t.link||'')}" placeholder="https://…"></label><div class="personal-link-confirm" ${t.link?'':'hidden'}><button type="button" class="secondary" data-preview-link>打开链接核对 ↗</button><label class="check-line"><input type="checkbox" name="linkConfirmed" ${t.link?'required':''}> 我已核对链接和访问权限</label></div></form>`,`<button class="primary" form="submit-form" type="submit">提交给 ${esc(person(t.receiver))}</button>`)};

function templatesView(){return head('流程模板','沉淀标准流程，为每次活动保留调整空间。',manager()?'<button class="primary" data-template-new>＋ 创建模板</button>':'')+`<div class="template-grid"><section class="template-card blank-template"><span class="event-kicker">自由安排</span><h2>空白日程</h2><p>只填写活动信息，不预置任务。后续按需派单，再将成熟流程保存为模板。</p>${manager()?'<button class="secondary" data-create>从空白开始</button>':''}</section>${(state.templates||[]).map(t=>`<section class="template-card"><span class="event-kicker">${t.createdBy?'团队模板':'SOP 标准流程'} · ${t.steps.length} 个环节</span><h2>${esc(t.name)}</h2><p>${esc(t.description||'')}</p><ol>${t.steps.map(s=>`<li>${esc(s.name)} <small>${esc(s.dept)}</small></li>`).join('')}</ol>${manager()?`<div class="actions"><button class="primary" data-use-template="${t.id}">使用模板</button><button class="secondary" data-template-edit="${t.id}">${t.createdBy&&(admin()||t.createdBy===user.id)?'编辑':'复制编辑'}</button></div>`:''}</section>`).join('')}</div>`}
function stepEditor(s={},i=0){return `<fieldset class="template-step"><legend>环节 <span class="step-index">${i+1}</span></legend><label class="field">环节名称<input data-key="name" required maxlength="100" value="${esc(s.name||'')}"></label><div class="form-grid"><label class="field">建议部门<select data-key="dept">${options(depts,s.dept||user.dept)}</select></label><label class="field">距活动开始日（天）<input data-key="offset" type="number" min="-365" max="365" value="${s.offset||0}" required></label></div><div class="form-grid"><label class="field">截止时间<input data-key="time" type="time" value="${s.time||'18:00'}" required></label><label class="field">前序环节编号<input data-key="depends" value="${(s.depends||[]).map(j=>j+1).join(',')}" placeholder="如：1,2；无依赖则留空"></label></div><label class="field">交付要求<textarea data-key="requirements" maxlength="3000" required>${esc(s.requirements||'')}</textarea></label><div class="form-grid"><label class="field">积分（留空沿用活动设置）<input data-key="rewardPoints" type="number" min="0" max="10000" value="${s.rewardPoints??''}"></label><label class="field">其他奖励<input data-key="rewardNote" maxlength="500" value="${esc(s.rewardNote||'')}"></label></div><button type="button" class="text-btn danger-text" data-remove-step>删除此环节</button></fieldset>`}
function templateForm(id,preset){const original=(state.templates||[]).find(t=>t.id===id);const editable=original?.createdBy&&(admin()||original.createdBy===user.id);const t=preset||original||{};modal(editable?'编辑模板':'创建模板',`<form id="template-form" data-id="${editable?id:''}"><label class="field">模板名称<input name="name" value="${esc(t.name||'')}" required maxlength="60"></label><label class="field">使用说明<textarea name="description" maxlength="500">${esc(t.description||'')}</textarea></label><div id="template-steps">${(t.steps||[]).map(stepEditor).join('')}</div><button class="secondary" type="button" data-add-step>＋ 添加环节</button><p class="sub">用相对活动开始日的天数表示排期（负数为提前）。前序编号必须小于当前环节；保存后可在新建活动中选择。</p></form>`,`<button class="primary" form="template-form" type="submit">保存模板</button>`)}
function templatePayload(f){const d=Object.fromEntries(new FormData(f));return {...d,...(f.dataset.id?{id:f.dataset.id}:{}),steps:[...f.querySelectorAll('.template-step')].map(el=>{const x=Object.fromEntries([...el.querySelectorAll('[data-key]')].map(n=>[n.dataset.key,n.value]));return {...x,offset:Number(x.offset),rewardPoints:x.rewardPoints===''?null:Number(x.rewardPoints),depends:x.depends.trim()?x.depends.split(/[,，]/).map(v=>Number(v.trim())-1):[]}})}}
function templateFromEvent(id){const e=state.events.find(x=>x.id===id),ts=state.tasks.filter(t=>t.event===id);templateForm(null,{name:e.name+'流程',description:e.description||'',steps:ts.map(t=>({name:t.name,dept:t.dept,offset:dayDiff(t.due,e.date),time:t.due.slice(11,16),depends:t.depends.map(id=>ts.findIndex(x=>x.id===id)),requirements:t.requirements,rewardPoints:t.rewardPoints,rewardNote:t.rewardNote}))})}
function rewardRanking(){const totals={};state.ledger.forEach(x=>{if(x.points)totals[x.user]=(totals[x.user]||0)+x.points});const rows=Object.entries(totals).map(([id,points])=>({name:person(id)||'已停用成员',points,me:id===user.id})).sort((a,b)=>b.points-a.points).slice(0,10);const medals=['🥇','🥈','🥉'];const max=Math.max(1,...rows.map(x=>x.points));return `<section class="panel"><div class="panel-head"><h2>积分排名</h2></div><div class="rank-list">${rows.map((r,i)=>`<div class="rank-row ${r.me?'me':''}"><span class="rank-medal">${medals[i]||(i+1)}</span><div class="rank-copy"><b>${esc(r.name)}</b><span class="rank-bar"><i style="width:${Math.max(2,Math.round(r.points/max*100))}%"></i></span></div><strong>${r.points}分</strong></div>`).join('')||'<div class="empty">暂无积分记录</div>'}</div></section>`}
function rewardsView(){const ledger=state.ledger||[],mine=ledger.filter(x=>x.user===user.id),total=mine.reduce((n,x)=>n+x.points,0);return head('贡献与积分','每一分都来自验收通过，踏踏实实记在这里。')+`<div class="reward-summary"><div><span class="event-kicker">我的累计积分</span><strong>${total}<small>分</small></strong></div><div><h3>${mine.length} 项任务已验收</h3><p class="sub">积分仅在验收后入账，不因重复点击而增加。其他奖励由负责人按备注兑现。</p></div></div>${rewardRanking()}<section class="panel"><div class="panel-head"><h2>${admin()?'全体成员':manager()?'本部门':'我的'}积分记录</h2></div>${[...ledger].reverse().map(x=>`<div class="asset-row"><span class="points-chip">+${x.points}</span><div class="task-copy"><h3>${esc(x.taskName)}</h3><p>${esc(x.eventName)} · ${esc(person(x.user))} · 验收人 ${esc(person(x.approvedBy))}</p>${x.note?`<p>奖励备注：${esc(x.note)}</p>`:''}</div><small>${dateText(x.time.slice(0,16))}</small></div>`).join('')||'<div class="empty">任务验收通过后，积分和奖励记录会显示在这里。</div>'}</section>`}

function scheduleToolbar(){return `<div class="schedule-controls"><div class="actions"><button class="secondary" data-month="-1" aria-label="上月">‹</button><h2>${year} 年 ${month+1} 月</h2><button class="secondary" data-month="1" aria-label="下月">›</button><button class="text-btn" data-today>今天</button></div><label class="filter-label">部门<select data-calendar-dept><option value="">所有可见部门</option>${options(depts,calendarDept)}</select></label></div>`}
function timelineView(){const first=`${year}-${String(month+1).padStart(2,'0')}-01`,days=new Date(year,month+1,0).getDate(),events=visibleEvents().filter(e=>e.date<=dayShift(first,days-1)&&(e.endDate||e.date)>=first);return `<section class="panel schedule-panel"><div class="panel-head"><div><span class="event-kicker">共享排期</span><h2>活动时间轴</h2></div><button class="text-btn" data-view="calendar">查看日历 →</button></div>${scheduleToolbar()}<div class="timeline-tools"><span class="sub">横向拖动浏览 · 点击活动查看 · 拖动 ⠿ 调整日期</span><label>缩放 <input type="range" min="44" max="110" value="${timelineScale}" data-timeline-scale aria-label="时间轴缩放"></label></div><div class="time-scroll" tabindex="0" aria-label="活动时间轴，可横向滚动"><div class="time-canvas" style="--day-width:${timelineScale}px;width:${days*timelineScale}px"><div class="time-dates">${Array.from({length:days},(_,i)=>{const d=dayShift(first,i);return `<button class="time-date ${d===localDay()?'today':''} ${d===selectedDay?'selected':''}" style="width:${timelineScale}px" data-select-day="${d}">${i+1}<small>${['日','一','二','三','四','五','六'][new Date(d+'T12:00').getDay()]}</small></button>`}).join('')}</div>${events.map(e=>{const start=Math.max(0,dayDiff(e.date,first)),end=Math.min(days,dayDiff(e.endDate||e.date,first)+1);return `<div class="time-lane"><div class="time-bar" style="left:${start*timelineScale+3}px;width:${Math.max(timelineScale-6,(end-start)*timelineScale-6)}px" title="${esc(e.name)} · ${esc(eventTime(e))}">${canEditEvent(e)?`<button class="drag-handle" data-drag-event="${e.id}" title="拖动调整日期，也可在活动详情编辑" aria-label="拖动调整 ${esc(e.name)} 日期">⠿</button>`:''}<button class="time-event" data-event="${e.id}">${esc(e.name)}</button></div></div>`}).join('')||'<div class="timeline-empty">本月暂无活动，可切换月份或新建日程。</div>'}</div></div>${selectedDay?`<div class="selected-day"><h3>${dateText(selectedDay)}</h3>${visibleTasks().filter(t=>t.due.startsWith(selectedDay)).map(taskRow).join('')||'<p class="sub">当日暂无任务截止。</p>'}</div>`:''}</section>`}
calendarView=function(){const start=(new Date(year,month,1).getDay()+6)%7,last=new Date(year,month+1,0).getDate();let cells='';for(let i=0;i<Math.ceil((start+last)/7)*7;i++){const d=i-start+1,key=`${year}-${String(month+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`;cells+=`<div class="day ${d<1||d>last?'out':''} ${key===localDay()?'today':''} ${key===selectedDay?'selected':''}">${d<1||d>last?'':`<button class="day-num" data-select-day="${key}">${d}</button>${visibleEvents().filter(e=>e.date<=key&&(e.endDate||e.date)>=key).map(e=>`<button class="cal-event activity" data-event="${e.id}" title="${esc(e.name)}">${esc(e.name)}</button>`).join('')}${visibleTasks().filter(t=>t.due.startsWith(key)).map(t=>`<button class="cal-event" data-task="${t.id}" title="${esc(t.name)}">${t.due.slice(11)} ${esc(t.name)}</button>`).join('')}`}</div>`}return head('日历与时间轴','活动日期与任务截止时间共用同一份排期。',manager()?'<button class="primary" data-create>＋ 新建活动</button>':'')+`<div class="calendar">${scheduleToolbar()}<div class="cal-week">${['一','二','三','四','五','六','日'].map(x=>`<div>周${x}</div>`).join('')}</div><div class="cal-grid">${cells}</div></div>`+timelineView()};

function adminStatsView(){loadAdminStats().then(s=>{if(view==='stats'&&s)renderAdminStats(s)}).catch(()=>{if(view==='stats')document.getElementById('admin-stats').innerHTML='<div class="empty">统计暂时无法读取</div>'});return head('站长统计','这里汇总网站访问数据，方便了解使用情况。')+`<div id="admin-stats"><div class="empty">正在读取统计…</div></div>`}
function loadAdminStats(){return api('stats')}
function renderAdminStats(s){const total=s.total||0,days=s.days||[],max=Math.max(1,...days.map(d=>d.hits));const bars=days.slice().reverse().map(d=>`<div class="stat-bar-item"><div class="stat-bar" style="height:${Math.round(d.hits/max*100)}%"></div><span>${d.date.slice(5)}</span><b>${d.hits}</b></div>`).join('');document.getElementById('admin-stats').innerHTML=`<div class="stat-total">累计访问 <strong>${total}</strong> 次</div><div class="stat-chart">${bars||'<div class="empty">暂无访问数据</div>'}</div>`}
function sopView(){if(!sopDocuments.length&&!sopLoading){sopLoading=true;fetch('/sop-docs.json').then(r=>r.json()).then(x=>{sopDocuments=x;if(view==='sop')render()}).catch(()=>toast('SOP 文档暂时无法读取')).finally(()=>sopLoading=false)}return head('知识库','不用背流程，照着这里走就好；标准的事交给系统，创作的事留给你们。')+`<div class="sop-principles"><div><b>01 / 一个入口</b><p>外派需求先由办公室登记，明确来源、交付目标、负责人和验收人。</p></div><div><b>02 / 素材先行</b><p>文案提前预写；照片精选交付后，再完成推送排版。任务前序验收后自动解锁。</p></div><div><b>03 / 验收与沉淀</b><p>统一活动素材库，保留成果链接与交接记录；成熟流程保存为模板，供下次复用。</p></div></div><div class="hint">照片精选按素材库细则在活动后 48 小时内交付，视频素材按 72 小时执行；实际截止时间以负责人在任务中确认的排期为准。</div><section class="panel"><div class="panel-head"><h2>部门手册与规范</h2></div>${sopDocuments.map((d,i)=>`<button class="sop-document" data-sop-doc="${i+1}"><span>${esc(d.title)}</span><small>${esc(d.path)}</small><span>阅读 ↗</span></button>`).join('')||'<div class="empty">正在读取本地知识库…</div>'}</section><p class="sub">内容来自交付目录中的 SOP 文档快照。历史年度 CSV 是参考资料；新项目中的活动、时间轴和日历由同一数据库同步。</p>`}
function sopMarkdown(src){const lines=String(src||'').replace(/\r\n/g,'\n').split('\n');let html='',i=0;const inline=s=>esc(s).replace(/\*\*(.+?)\*\*/g,'<strong>$1</strong>').replace(/`([^`]+)`/g,'<code>$1</code>').replace(/\[([^\]]+)\]\(([^)]+)\)/g,'<a href="$2">$1</a>');while(i<lines.length){const line=lines[i];if(!line.trim()){i++;continue}if(line.startsWith('```')){let code='';i++;while(i<lines.length&&!lines[i].startsWith('```')){code+=(code?'\n':'')+lines[i];i++}i++;html+='<pre><code>'+esc(code)+'</code></pre>';continue}let m;if(m=line.match(/^######\s+(.*)$/)){html+='<h6>'+inline(m[1])+'</h6>';i++;continue}if(m=line.match(/^#####\s+(.*)$/)){html+='<h5>'+inline(m[1])+'</h5>';i++;continue}if(m=line.match(/^####\s+(.*)$/)){html+='<h4>'+inline(m[1])+'</h4>';i++;continue}if(m=line.match(/^###\s+(.*)$/)){html+='<h3>'+inline(m[1])+'</h3>';i++;continue}if(m=line.match(/^##\s+(.*)$/)){html+='<h2>'+inline(m[1])+'</h2>';i++;continue}if(m=line.match(/^#\s+(.*)$/)){html+='<h1>'+inline(m[1])+'</h1>';i++;continue}if(line.startsWith('|')){const rows=[];while(i<lines.length&&lines[i].startsWith('|')){rows.push(lines[i]);i++}if(rows.length>=2&&/^[\s|:-]+$/.test(rows[1].replace(/\|/g,''))){const parseRow=r=>r.replace(/^\|/,'').replace(/\|$/,'').split('|').map(c=>inline(c.trim()));const header=parseRow(rows[0]);let body='';for(let r=2;r<rows.length;r++){body+='<tr>'+parseRow(rows[r]).map(c=>'<td>'+c+'</td>').join('')+'</tr>'}html+='<table><thead><tr>'+header.map(c=>'<th>'+c+'</th>').join('')+'</tr></thead><tbody>'+body+'</tbody></table>';continue}}if(/^[-*]\s+/.test(line)){const items=[];while(i<lines.length&&/^[-*]\s+/.test(lines[i])){items.push('<li>'+inline(lines[i].replace(/^[-*]\s+/,''))+'</li>');i++}html+='<ul>'+items.join('')+'</ul>';continue}if(/^\d+\.\s+/.test(line)){const items=[];while(i<lines.length&&/^\d+\.\s+/.test(lines[i])){items.push('<li>'+inline(lines[i].replace(/^\d+\.\s+/,''))+'</li>');i++}html+='<ol>'+items.join('')+'</ol>';continue}if(line.startsWith('> ')){const items=[];while(i<lines.length&&lines[i].startsWith('> ')){items.push(inline(lines[i].slice(2)));i++}html+='<blockquote>'+items.join('<br>')+'</blockquote>';continue}const p=[];while(i<lines.length&&lines[i].trim()&&!/^(#{1,6}\s+|\||```|[-*]\s+|\d+\.\s+|>\s+)/.test(lines[i])){p.push(inline(lines[i]));i++}html+='<p>'+p.join('<br>')+'</p>'}return html}
function openSop(index){const d=sopDocuments[Number(index)-1];if(d)modal(d.title,`<p class="sub">${esc(d.path)}</p><div class="sop-reader">${sopMarkdown(d.content)}</div>`)}

document.addEventListener('pointerover',e=>{const summary=e.target.closest('.check-help summary');if(summary&&e.pointerType==='mouse'&&!summary.parentElement.open){summary.parentElement.open=true;summary.parentElement.dataset.hoverOpen='1'}});
document.addEventListener('pointerout',e=>{const help=e.target.closest('.check-help');if(help&&help.dataset.hoverOpen&&!help.contains(e.relatedTarget)){help.open=false;delete help.dataset.hoverOpen}});
document.addEventListener('click',e=>{const summary=e.target.closest('.check-help summary');if(summary&&(summary.parentElement.dataset.hoverOpen||summary.parentElement.dataset.longOpen)){e.preventDefault();delete summary.parentElement.dataset.hoverOpen;delete summary.parentElement.dataset.longOpen;summary.parentElement.open=true}});
document.addEventListener('change',e=>{
  const el=e.target;
  if(el.name==='template'&&el.form?.id==='create-form')renderAssignments();
  if(el.name==='allDay')el.form.querySelector('.time-fields').hidden=el.checked;
  if(el.name==='date'&&el.form?.elements.endDate&&el.form.elements.endDate.value<el.value)el.form.elements.endDate.value=el.value;
  if(el.matches('[data-calendar-dept]')){calendarDept=el.value;render()}
});
document.addEventListener('input',e=>{const el=e.target;if(el.matches('[data-timeline-scale]')){const scroller=$('.time-scroll'),ratio=Number(el.value)/timelineScale,scroll=scroller.scrollLeft,canvas=$('.time-canvas');timelineScale=Number(el.value);canvas.style.width=(new Date(year,month+1,0).getDate()*timelineScale)+'px';canvas.style.setProperty('--day-width',timelineScale+'px');canvas.querySelectorAll('.time-date').forEach(x=>x.style.width=timelineScale+'px');canvas.querySelectorAll('.time-bar').forEach(x=>{x.style.left=((parseFloat(x.style.left)-3)*ratio+3)+'px';x.style.width=((parseFloat(x.style.width)+6)*ratio-6)+'px'});scroller.scrollLeft=scroll*ratio;}
  if(el.name==='link'&&el.form?.id==='submit-form'){const box=el.form.querySelector('.personal-link-confirm'),check=el.form.elements.linkConfirmed;box.hidden=!el.value.trim();check.required=!!el.value.trim();check.checked=false;}
});
document.addEventListener('click',async e=>{const a=e.target.closest('button,a');if(!a)return;try{
  if(a.hasAttribute('data-open-upload')){const check=$('#submit-form [name=uploadConfirmed]');check.disabled=false;}
  if(a.hasAttribute('data-copy-url')){await navigator.clipboard.writeText(a.dataset.copyUrl);toast('链接已复制');}
  if(a.hasAttribute('data-preview-link')){const input=$('#submit-form [name=link]');if(!input.value||!input.checkValidity())throw Error('请先填写有效的成果链接');const url=new URL(input.value);if(!['https:','http:'].includes(url.protocol))throw Error('请使用 http 或 https 链接');window.open(url.href,'_blank','noopener,noreferrer');}
  if(a.hasAttribute('data-add-step')){const list=$('#template-steps');if(list.children.length>=30)throw Error('最多 30 个环节');list.insertAdjacentHTML('beforeend',stepEditor({},list.children.length));}
  if(a.hasAttribute('data-remove-step')){const list=$('#template-steps'),row=a.closest('.template-step'),index=[...list.children].indexOf(row);row.remove();[...list.children].forEach((el,i)=>{el.querySelector('.step-index').textContent=i+1;const dep=el.querySelector('[data-key=depends]');dep.value=dep.value.split(/[,，]/).map(v=>Number(v.trim())).filter(v=>v>0&&v!==index+1).map(v=>v>index+1?v-1:v).join(',')});}
  if(a.hasAttribute('data-today')){year=new Date().getFullYear();month=new Date().getMonth();selectedDay=localDay();render();$('.time-scroll')?.scrollTo({left:(new Date().getDate()-2)*timelineScale,behavior:'smooth'});}
  if(a.dataset.selectDay){selectedDay=a.dataset.selectDay;render();}
}catch(err){toast(err.message)}});

// Mouse drag-to-pan; touch uses native scrolling. Event handles work with mouse and touch.
let timelineDrag=null,pan=null,suppressTimelineClick=false,longPressTimer,longPressOrigin=null;
document.addEventListener('pointerdown',e=>{
  const help=e.target.closest('.check-help summary');if(help&&e.pointerType==='touch'){longPressOrigin={x:e.clientX,y:e.clientY};longPressTimer=setTimeout(()=>{help.parentElement.open=true;help.parentElement.dataset.longOpen='1'},450);}
  const handle=e.target.closest('[data-drag-event]');if(handle){timelineDrag={id:handle.dataset.dragEvent,startX:e.clientX,delta:0,handle};handle.setPointerCapture(e.pointerId);e.preventDefault();return;}
  const scroller=e.target.closest('.time-scroll');if(scroller&&e.pointerType==='mouse'&&!e.target.closest('button')){pan={el:scroller,x:e.clientX,left:scroller.scrollLeft};scroller.setPointerCapture(e.pointerId)}
});
document.addEventListener('pointermove',e=>{if(longPressOrigin&&Math.hypot(e.clientX-longPressOrigin.x,e.clientY-longPressOrigin.y)>12){clearTimeout(longPressTimer);longPressOrigin=null}if(timelineDrag){const d=timelineDrag;d.delta=Math.round((e.clientX-d.startX)/timelineScale);d.handle.closest('.time-bar').style.transform=`translateX(${d.delta*timelineScale}px)`}if(pan)pan.el.scrollLeft=pan.left+pan.x-e.clientX;});
function endPointer(e,cancel=false){clearTimeout(longPressTimer);pan=null;if(!timelineDrag)return;const d=timelineDrag;timelineDrag=null;d.handle.closest('.time-bar').style.transform='';if(cancel||!d.delta)return;const event=state.events.find(x=>x.id===d.id);const date=dayShift(event.date,d.delta);suppressTimelineClick=true;setTimeout(()=>suppressTimelineClick=false,300);modal('确认活动改期',`<form id="date-form" data-id="${event.id}"><p>${esc(event.name)}</p><label class="field">新的开始日期<input name="date" type="date" value="${date}" required></label><div class="hint">未完成任务与活动结束日期同步平移 ${d.delta} 天，已完成记录和积分保持不变。</div></form>`,`<button class="primary" form="date-form" type="submit">确认并同步日历</button>`)}
document.addEventListener('pointerup',e=>endPointer(e));
document.addEventListener('pointercancel',e=>endPointer(e,true));
document.addEventListener('click',e=>{if(suppressTimelineClick&&e.target.closest('.time-scroll')){e.stopImmediatePropagation();e.preventDefault()}},true);