// Adaptive CAPTCHA and cooldown UX. Password submissions are never retried automatically.
(()=>{
 let current=null,epoch=0,timer=0;
 const text=(zh,en)=>uiLanguage()==='en'?en:zh;
 function form(){return document.querySelector('#auth-form')}
 function stop(){clearInterval(timer);timer=0;current=null;epoch++}
 function status(){const f=form();if(!f||authMode!=='login'||!current)return;const seconds=Math.max(0,Math.ceil((current.until-Date.now())/1000)),button=f.querySelector('[type=submit]'),hint=f.querySelector('[data-login-status]');
  if(hint)hint.textContent=current.locked?text('密码错误已达 10 次。请联系管理员获取重置链接。','10 incorrect passwords. Contact an administrator for a reset link.'):seconds?text(`冷却中，请 ${seconds} 秒后重试。`,`Please wait ${seconds} seconds before trying again.`):current.required?text('请输入图片中的 5 位验证码；点击图片可换一张。','Enter the 5 characters. Click the image for a new challenge.') :'';
  if(button&&!busy){button.disabled=!!(current.locked||seconds);button.textContent=seconds?text(`请等待 ${seconds} 秒`,`Wait ${seconds}s`):text('登录','Sign in')}
 }
 function update(meta){const f=form();if(!f||authMode!=='login')return;if(!current)current={until:0,required:false,locked:false,username:f.elements.username.value.trim().toLowerCase()};
  if(Number.isFinite(meta.retryAfter))current.until=Date.now()+Math.max(0,meta.retryAfter)*1000;
  if(typeof meta.locked==='boolean')current.locked=meta.locked;
  if(typeof meta.required==='boolean'||typeof meta.captchaRequired==='boolean')current.required=!!(meta.required??meta.captchaRequired);
  const group=f.querySelector('[data-login-captcha]');group.hidden=!current.required||current.locked;
  const answer=f.elements.captchaAnswer;answer.required=current.required&&!current.locked;
  if(meta.id&&meta.image?.startsWith('data:image/png;base64,')){f.elements.captchaId.value=meta.id;f.querySelector('[data-captcha-image]').src=meta.image;answer.value=''}status();if(!timer)timer=setInterval(status,500);
 }
 async function challenge(){const f=form();if(!f||authMode!=='login')return;const username=f.elements.username.value.trim().toLowerCase();if(!/^[a-z0-9][a-z0-9_.-]{2,31}$/.test(username))return;
  const serial=++epoch;try{const meta=await priorApi('captcha',{username});if(serial!==epoch||f!==form()||username!==f.elements.username.value.trim().toLowerCase())return;current={username,until:0,required:false,locked:false};update(meta)}catch{if(serial===epoch&&f===form()){const hint=f.querySelector('[data-login-status]');if(hint)hint.textContent=text('验证码暂未读取，请点击图片重试。','Challenge unavailable. Click the image to try again.')}}
 }
 const priorAuth=auth;auth=function(...args){stop();priorAuth(...args);const f=form();if(authMode!=='login'||!f)return;const box=document.createElement('div');box.className='login-security';box.innerHTML=`<div data-login-captcha hidden><label class="field">${text('验证码','Verification code')}<input name="captchaAnswer" maxlength="5" pattern="[A-Za-z2-9]{5}" autocomplete="off" autocapitalize="characters" spellcheck="false" aria-label="${text('验证码','Verification code')}"></label><button type="button" class="captcha-refresh" data-refresh-captcha aria-label="${text('刷新验证码','Refresh verification code')}"><img data-captcha-image alt="${text('图形验证码','Visual verification code')}"><span>${text('换一张','Refresh')}</span></button><input name="captchaId" type="hidden"></div><p class="sub" data-login-status role="status"></p>`;f.querySelector('[type=submit]').before(box);f.elements.username.addEventListener('blur',challenge);f.elements.username.addEventListener('input',()=>{stop();f.elements.captchaId.value='';f.elements.captchaAnswer.value='';f.elements.captchaAnswer.required=false;f.querySelector('[data-login-captcha]').hidden=true;f.querySelector('[data-login-status]').textContent='';const button=f.querySelector('[type=submit]');if(!busy)button.disabled=false});f.querySelector('[data-refresh-captcha]').addEventListener('click',challenge)};
 const priorApi=api;api=async function(path,data){try{return await priorApi(path,data)}catch(e){if(path==='login'&&form()&&authMode==='login'){update(e);if(e.captchaRequired&&!e.locked)await challenge();if(uiLanguage()==='en'){e.message=({PASSWORD_LOCKED:'Account locked after 10 incorrect passwords. Contact an administrator.',PASSWORD_COOLDOWN:'Incorrect password. Wait for the cooldown before trying again.',CAPTCHA_REJECTED:'Invalid or expired verification code. Refresh the image.',LOGIN_REJECTED:'Incorrect username or password.',LOGIN_CHANGED:'Login state changed. Please try again.'})[e.code]||e.message}}throw e}};
 document.addEventListener('submit',e=>{if(e.target.id!=='auth-form'||authMode!=='login'||!current)return;if(current.locked||current.until>Date.now()){e.preventDefault();e.stopImmediatePropagation();status()}},true);
 window.addEventListener('pagehide',stop);
})();

// Browser-managed passwords stay outside the site's ordinary storage.
(()=>{
 const KEY='fr.loginMemory';let pending=null,serial=0,switchingAccount=false,reviewMode=false;
 const t=(zh,en)=>uiLanguage()==='en'?en:zh;
 function choice(){try{const value=JSON.parse(localStorage.getItem(KEY)||'null');return value?.remember===true&&typeof value.username==='string'&&/^[A-Za-z0-9][A-Za-z0-9_.-]{2,31}$/.test(value.username)?{remember:true,username:value.username,owner:value.owner===true}:{remember:false,username:''}}catch{return {remember:false,username:''}}}
 function save(username,remember,owner=false){try{if(remember)localStorage.setItem(KEY,JSON.stringify({remember:true,username,...(owner===true?{owner:true}:{})}));else localStorage.removeItem(KEY)}catch{}}
 function noSilentSignIn(){try{navigator.credentials?.preventSilentAccess?.().catch(()=>{})}catch{}}
 function clear(){serial++;pending=null;if(!reviewMode)save('',false);noSilentSignIn()}
 function store(username,password){if(!window.isSecureContext||!window.PasswordCredential||!navigator.credentials?.store)return;try{navigator.credentials.store(new PasswordCredential({id:username,password})).catch(()=>{})}catch{}}
 const priorAuth=auth;auth=function(...args){pending=null;serial++;if(reviewMode&&args[0]==='register')args[0]='login';priorAuth(...args);const f=document.querySelector('#auth-form');if(authMode!=='login'||!f)return;const remembered=reviewMode||switchingAccount?{remember:false,username:''}:choice();switchingAccount=false;const box=document.createElement('div');box.className='login-memory';if(reviewMode){document.querySelector('.auth-card [data-auth=register]')?.remove();const hint=document.createElement('p');hint.className='hint login-review';hint.textContent=t('账号审核封存中，仅初始管理员可登录。','Accounts are temporarily sealed for review. Only the initial administrator can sign in.');f.before(hint)}box.innerHTML=`<label class="remember-label"><input type="checkbox" name="remember" value="true" ${remembered.remember?'checked':''}><span>${reviewMode?t('保持登录','Keep me signed in'):t('记住账号密码','Remember account & password')}</span></label><p class="remember-note">${reviewMode?t('审核模式仅保持登录 30 天，不记住账号密码。','Review mode keeps your session for 30 days without remembering your account or password.'):t('密码由浏览器密码管理器保存；勾选后在此设备保持登录 30 天。','Your browser manages password saving. Remembered sign-in lasts 30 days on this device.')}</p>`;f.querySelector('[type=submit]').before(box);if(remembered.username)f.elements.username.value=remembered.username;f.autocomplete=reviewMode?'off':'on';f.elements.username.autocomplete=reviewMode?'off':'username';f.elements.password.autocomplete=reviewMode?'new-password':'current-password';f.elements.username.setAttribute('autocapitalize','none');f.elements.username.setAttribute('spellcheck','false');let restored=remembered.username;f.elements.username.addEventListener('input',()=>{if(restored&&f.elements.username.value!==restored){f.elements.password.value='';restored=''}});f.elements.remember.addEventListener('change',()=>{if(!f.elements.remember.checked)clear()})};
 const priorApi=api;api=async function(path,data){
  let request=data,candidate=null;if(path==='login'&&data){const f=document.querySelector('#auth-form'),remember=typeof data.remember==='boolean'?data.remember:!!f?.elements.remember?.checked;request={...data,remember};candidate={serial,username:String(data.username||'').trim(),password:String(data.password||''),remember}}
  if(path==='logout'){serial++;pending=null;noSilentSignIn()}
  try{const result=await priorApi(path,request);if(path==='info')reviewMode=result?.reviewMode===true;if(path==='login'&&candidate&&candidate.serial===serial)pending=candidate;if(path==='info'&&pending){const saved=pending;pending=null;if(!reviewMode&&saved.serial===serial&&result?.user?.status==='active'&&result.user.username?.toLowerCase()===saved.username.toLowerCase()){save(saved.username,saved.remember,result.user.owner===true);if(saved.remember)store(saved.username,saved.password)}}if(!reviewMode&&path==='password'&&data&&choice().remember&&user?.username)store(user.username,String(data.password||''));if(path==='recover'){pending=null;noSilentSignIn()}return result}catch(error){if(path==='login'||path==='info')pending=null;throw error}
 };
 document.addEventListener('click',e=>{if(e.target.closest('[data-switch-account]')){switchingAccount=true;noSilentSignIn();pending=null;serial++}},true);
 window.addEventListener('pagehide',()=>{pending=null;serial++});
})();
