// v1.0.2: visible ambient motion, neutral themes and bilingual interface.
const uiLanguage=()=>prefs().language||localStorage.getItem('fr.language')||'zh-CN';
const uiText=s=>Localization.translate(s,uiLanguage());
const fxTextSource=new WeakMap(),fxAttributeSource=new WeakMap();
function localizeInterface(root=document.body){
 const lang=uiLanguage();document.documentElement.lang=lang;document.title=lang==='en'?'Fengru Media · Workspace':'冯如学媒 · 协作工作台';
 const content=new Set([user?.name,user?.username,...state.people.map(p=>p.name),...state.events.flatMap(e=>[e.name,e.description,e.location]),...state.tasks.flatMap(t=>[t.name,t.requirements,t.submission,t.feedback]),...(state.templates||[]).filter(t=>t.createdBy).flatMap(t=>[t.name,t.description,...t.steps.flatMap(s=>[s.name,s.requirements])])].filter(Boolean));
 const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);let node;
 while(node=walker.nextNode()){
  if(node.parentElement?.closest('script,style,textarea,.sop-reader,.sop-document small,.detail-copy,.person-home,[data-original-content]'))continue;
  const prior=fxTextSource.get(node),source=prior&&node.textContent===prior.output?prior.source:node.textContent;
  if(content.has(source.trim())&&!node.parentElement.closest('option'))continue;
  const output=Localization.translate(source,lang);fxTextSource.set(node,{source,output});if(node.textContent!==output)node.textContent=output;
 }
 for(const el of root.querySelectorAll('[placeholder],[aria-label],[title]')){const old=fxAttributeSource.get(el)||{};for(const k of ['placeholder','aria-label','title'])if(el.hasAttribute(k)){const value=el.getAttribute(k),source=old[k]?.output===value?old[k].source:value,output=Localization.translate(source,lang);old[k]={source,output};if(value!==output)el.setAttribute(k,output)}fxAttributeSource.set(el,old)}
}
let fxLocalizationQueued=false;
new MutationObserver(()=>{if(fxLocalizationQueued)return;fxLocalizationQueued=true;queueMicrotask(()=>{fxLocalizationQueued=false;localizeInterface()})}).observe(document.body,{childList:true,subtree:true});
const fxToast=toast;toast=s=>fxToast(uiText(s));
const fxModal=modal;modal=(...args)=>{fxModal(...args);localizeInterface($('#dialog-body'))};
function accountDock(){return `<aside class="account-dock ${accountPinned?'pinned':''}"><button class="account-trigger" data-account aria-expanded="${accountPinned}" aria-label="个人中心">${avatarMarkup(user)}<span><b>${esc(user.name)}</b><small>${esc(user.dept)} · ${roleNames[user.role]}</small></span>⌃</button><div class="account-menu"><div class="account-heading">${avatarMarkup(user)}<div><b>${esc(user.name)}</b><small>@${esc(user.username)} · ${roleNames[user.role]}</small></div></div><p>${esc(user.dept)} · ${esc(scope()||'全体协作')}</p><button data-profile>我的主页 / 姓名与头像</button><button data-settings>⚙ 设置</button><button data-switch-account>更换账号</button><button data-logout>退出登录</button><small>v1.0.2 · 点击或右键固定，点击空白处关闭</small></div></aside>`}
function settingsForm(tab='general'){
 const p=prefs();if(tab==='particles')tab='appearance';
 const tabs=`<div class="settings-tabs">${[['general','通用'],['appearance','外观'],['account','账号与安全']].map(([id,label])=>`<button class="${tab===id?'primary':'secondary'}" data-settings-tab="${id}">${label}</button>`).join('')}</div>`;
 let body;
 if(tab==='account')body=`<button class="secondary" data-profile>更改姓名 / 头像</button> <button class="secondary" data-password>修改密码</button><p class="hint">姓名与头像提交后经管理员审核，同步到各设备。</p><button class="secondary" data-switch-account>更换账号</button> <button class="secondary" data-logout>退出登录</button><hr><h3>注销账号申请</h3>${state.accountRequest?.status==='pending'?'<p>申请已提交，等待管理员审核与工作交接。</p><button class="secondary" data-cancel-account>撤回申请</button>':`<form id="closure-form"><label class="field">申请原因<textarea name="reason" required maxlength="500"></textarea></label><label class="field">当前密码<input type="password" name="password" required autocomplete="current-password"></label><button class="secondary" type="submit">提交注销申请</button></form>`}`;
 else body=`<form id="preferences-form">${tab==='general'?`<label class="field">界面语言<select name="language"><option value="zh-CN" ${p.language!=='en'?'selected':''}>中文</option><option value="en" ${p.language==='en'?'selected':''}>English</option></select></label><p class="sub">语言切换只影响界面，任务内容保留原文。</p><label class="check-line"><input type="checkbox" name="compact" ${p.compact?'checked':''}> 紧凑布局</label><button type="button" class="secondary" data-clear-cache>清除本机缓存并重新加载</button><p class="sub">保留账号登录与服务器任务。</p>`:`<div class="form-grid"><label class="field">主题颜色<input type="color" name="themeColor" value="${p.themeColor||'#e77b24'}"></label><label class="field">显示模式<select name="appearance">${[['light','纯白'],['dark','中性黑'],['auto','跟随系统']].map(([v,label])=>`<option value="${v}" ${v===(p.appearance||'light')?'selected':''}>${label}</option>`).join('')}</select></label></div><h3>动态背景</h3><label class="field">粒子样式<select name="particles">${Object.entries(particleNames).map(([v,label])=>`<option value="${v}" ${v===(p.particles||'constellation')?'selected':''}>${label}</option>`).join('')}</select></label><div class="particle-options" ${p.particles==='off'?'hidden':''}><label class="field">粒子数量<input name="particleDensity" type="range" min="10" max="80" value="${p.particleDensity||48}"></label><label class="field" data-rotation-setting ${p.particles==='rotate'?'':'hidden'}>轮换间隔（分钟）<input type="number" name="rotationMinutes" min="1" max="60" value="${p.rotationMinutes||5}"></label><p class="sub">粒子在内容上层显示，不影响点击。</p></div><label class="check-line"><input type="checkbox" name="motion" ${p.motion!==false?'checked':''}> 开启动画</label><label class="check-line"><input type="checkbox" name="respectSystemMotion" ${p.respectSystemMotion?'checked':''}> 跟随系统减少动态效果</label>`}<button class="primary" type="submit">保存并同步各设备</button></form>`;
 modal('设置',tabs+body);
}
document.addEventListener('change',e=>{if(e.target.name==='particles'&&e.target.form?.id==='preferences-form'){const rotation=$('[data-rotation-setting]');rotation.hidden=e.target.value!=='rotate';rotation.querySelector('input').disabled=rotation.hidden;$('.particle-options').hidden=e.target.value==='off'}});
// Add the new boolean before the existing capture-phase save handler reads FormData.
document.addEventListener('formdata',e=>{const f=e.target;if(f.id==='preferences-form'&&f.elements.respectSystemMotion)e.formData.set('respectSystemMotion',String(f.elements.respectSystemMotion.checked))});
const fxApi=api;api=async(path,data)=>{if(path==='settings/save'&&data){if(typeof data.respectSystemMotion==='string')data.respectSystemMotion=data.respectSystemMotion==='true';if(data.language)localStorage.setItem('fr.language',data.language)}return fxApi(path,data)};
function closeContextPanels(){accountPinned=false;personPinned='';document.querySelectorAll('.account-dock.pinned,.person-bubble.pinned').forEach(el=>el.classList.remove('pinned'));const dock=$('.account-dock');dock?.classList.add('dismissed');dock?.querySelector('[data-account]')?.setAttribute('aria-expanded','false');$('.member-profile-portal')?.remove()}
document.addEventListener('pointerdown',e=>{if(!e.target.closest('.account-dock,.person-bubble,.member-profile-portal'))closeContextPanels()});
document.addEventListener('pointerover',e=>{if(e.target.closest('.account-dock'))$('.account-dock')?.classList.remove('dismissed')});
document.addEventListener('focusin',e=>{if(e.target.closest('.account-dock'))$('.account-dock')?.classList.remove('dismissed')});
document.addEventListener('contextmenu',e=>{const b=e.target.closest('[data-person]');if(b){e.preventDefault();personPinned=b.dataset.person;memberPreview(personPinned);b.closest('.person-bubble').classList.add('pinned')}});
document.addEventListener('click',e=>{if(e.target.closest('[data-person]')){if(personPinned)memberPreview(personPinned);else $('.member-profile-portal')?.remove()}});
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeContextPanels()});
const fxOrg=organizationGraph;organizationGraph=()=>fxOrg().replace('学媒协作星图','组织架构图').replace('<div class="aero-map">','<div class="aero-map"><canvas class="org-particles" aria-hidden="true"></canvas>');
let fxPreviousView='',fxPreviousMotion;
const fxRender=render;render=()=>{fxRender();const side=$('.side-bottom'),dock=$('.account-dock');if(side&&dock){side.replaceChildren(dock)}const main=$('main');if(main){main.dataset.enter=String(fxPreviousView!==view);main.querySelectorAll('.panel,.stat,.activity-card').forEach((el,i)=>el.style.setProperty('--reveal-order',Math.min(i,6)));fxPreviousView=view}localizeInterface();if(personPinned&&view==='members')memberPreview(personPinned)};
function applyTheme(){const p=prefs(),r=document.documentElement,c=p.themeColor||'#e77b24';r.style.setProperty('--accent',c);r.style.setProperty('--green',c);r.style.setProperty('--light',`color-mix(in srgb, ${c} 10%, var(--surface))`);r.dataset.dark=String(p.appearance==='dark'||p.appearance==='auto'&&matchMedia('(prefers-color-scheme: dark)').matches);r.dataset.compact=String(!!p.compact);r.dataset.motion=String(p.motion!==false&&!(p.respectSystemMotion&&matchMedia('(prefers-reduced-motion: reduce)').matches));}
let fxOrgFrame=0,fxPointer={x:-1000,y:-1000},fxLastParticleTime=0;
document.addEventListener('pointermove',e=>fxPointer={x:e.clientX,y:e.clientY});
function stopParticles(){cancelAnimationFrame(particleFrame);cancelAnimationFrame(fxOrgFrame);particleCanvas?.remove();particleCanvas=null;particleSignature=''}
function startParticles(){
 const p=prefs(),sig=JSON.stringify(p)+document.documentElement.dataset.motion;
 if(sig===particleSignature&&particleCanvas){startOrganizationMotion();return}stopParticles();particleSignature=sig;
 if(document.documentElement.dataset.motion==='false'){document.querySelector('.org-particles')?.getContext('2d')?.clearRect(0,0,2000,2000);return}
 if(p.particles!=='off'){
  const canvas=document.createElement('canvas');canvas.className='particle-canvas';canvas.setAttribute('aria-hidden','true');document.body.prepend(canvas);particleCanvas=canvas;
  const ctx=canvas.getContext('2d'),styles=Object.keys(particleNames).filter(k=>!['off','random','rotate'].includes(k)),randomMode=styles[Math.floor(Math.random()*styles.length)],dots=Array.from({length:p.particleDensity||48},()=>({x:Math.random(),y:Math.random(),r:Math.random()*2.5+1.8,v:Math.random()*.7+.4,phase:Math.random()*Math.PI*2}));let last=0;
  function frame(time){if(!canvas.isConnected)return;particleFrame=requestAnimationFrame(frame);if(document.hidden||time-last<30)return;const dt=Math.min(2,(time-last)/33||1);last=time;fxLastParticleTime=time;const w=innerWidth,h=innerHeight,dpr=Math.min(devicePixelRatio||1,2);if(canvas.width!==Math.round(w*dpr)||canvas.height!==Math.round(h*dpr)){canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);ctx.setTransform(dpr,0,0,dpr,0,0)}ctx.clearRect(0,0,w,h);const mode=p.particles||'constellation',current=mode==='random'?randomMode:mode==='rotate'?styles[Math.floor(time/((p.rotationMinutes||5)*60000))%styles.length]:mode;
   ctx.strokeStyle=ctx.fillStyle=p.themeColor||'#e77b24';ctx.lineWidth=1.2;
   for(const d of dots){d.y=(d.y+(current==='rain'?.009:current==='snow'||current==='petals'?.0016:.0009)*d.v*dt)%1;d.x=(d.x+Math.sin(time/1700+d.phase)*.00065*dt+1)%1;let x=d.x*w,y=d.y*h,dist=Math.hypot(x-fxPointer.x,y-fxPointer.y);if(dist<120&&dist>1){x+=(x-fxPointer.x)/dist*(120-dist)*.12;y+=(y-fxPointer.y)/dist*(120-dist)*.12}ctx.globalAlpha=current==='stars'||current==='fireflies'?.25+Math.abs(Math.sin(time/900+d.phase))*.45:.48;ctx.beginPath();if(current==='rain'){ctx.moveTo(x,y);ctx.lineTo(x-14,y-35);ctx.stroke()}else if(current==='petals'){ctx.ellipse(x,y,d.r*2,d.r,time/1600+d.phase,0,Math.PI*2);ctx.fill()}else{ctx.arc(x,y,['bubbles','orbits'].includes(current)?d.r*3:d.r,0,Math.PI*2);if(['bubbles','orbits'].includes(current))ctx.stroke();else ctx.fill()}}
   if(current==='constellation')for(let i=0;i<dots.length;i++)for(let j=i+1;j<dots.length;j++){const a=dots[i],b=dots[j],dist=Math.hypot((a.x-b.x)*w,(a.y-b.y)*h);if(dist<160){ctx.globalAlpha=(1-dist/160)*.24;ctx.beginPath();ctx.moveTo(a.x*w,a.y*h);ctx.lineTo(b.x*w,b.y*h);ctx.stroke()}}canvas.dataset.frame=String(Math.floor(time));canvas.dataset.style=current;
  }particleFrame=requestAnimationFrame(frame);
 }
 startOrganizationMotion();
}
function startOrganizationMotion(){cancelAnimationFrame(fxOrgFrame);const map=$('.aero-map');if(!map||document.documentElement.dataset.motion==='false')return;const canvas=map.querySelector('.org-particles'),ctx=canvas.getContext('2d'),dots=Array.from({length:Math.min(48,prefs().particleDensity||48)},()=>({x:Math.random(),y:Math.random(),r:Math.random()*2+1}));let last=0;
 function frame(time){if(!map.isConnected)return;fxOrgFrame=requestAnimationFrame(frame);if(document.hidden||time-last<33)return;last=time;const w=map.clientWidth,h=map.clientHeight;if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h}ctx.clearRect(0,0,w,h);if(prefs().particles!=='off'){ctx.fillStyle=prefs().themeColor||'#e77b24';ctx.globalAlpha=.4;for(const d of dots){d.y=(d.y+.0007)%1;ctx.beginPath();ctx.arc(d.x*w,d.y*h,d.r,0,Math.PI*2);ctx.fill()}}
  map.querySelectorAll('.aero-cluster').forEach((el,i)=>{const b=el.querySelector('[data-bubble-drag]'),dept=b.dataset.bubbleDrag;if(el.matches(':hover,:focus-within')||bubbleDrag?.b===b&&bubbleDrag.moved)return;const base=bubblePositions.get(dept)||[[23,24],[77,24],[23,75],[77,75]][i],x=base[0]+Math.sin(time/2400+i*1.7)*.8,y=base[1]+Math.cos(time/2800+i*1.4)*1.1;el.style.left=x+'%';el.style.top=y+'%';const line=[...map.querySelectorAll('[data-line]')].find(l=>l.dataset.line===dept);line?.setAttribute('x2',x);line?.setAttribute('y2',y)});canvas.dataset.frame=String(Math.floor(time));
 }fxOrgFrame=requestAnimationFrame(frame);
}
matchMedia('(prefers-reduced-motion: reduce)').addEventListener('change',()=>{applyTheme();particleSignature='';startParticles()});
document.addEventListener('pointerdown',e=>{const target=e.target.closest('button,.task-row,.flow-step,nav a');if(!target||document.documentElement.dataset.motion==='false')return;target.animate([{filter:'brightness(1)',transform:'scale(1)'},{filter:'brightness(1.1)',transform:'scale(.97)'},{filter:'brightness(1)',transform:'scale(1)'}],{duration:260,easing:'ease-out'})});
