// Shared physical organization chart. Profiles are pinned; chart nodes remain alive.
let orgScene=null,orgController=null,orgClickUntil=0;
const orgWords=(zh,en)=>uiLanguage()==='en'?en:zh;
function presenceMarkup(p,{compact=false}={}){const online=p.status==='active'&&p.online===true;return `<span class="presence-status ${online?'is-online':'is-offline'}${compact?' presence-compact':''}" data-presence-id="${esc(p.id)}" data-online="${online}"><i aria-hidden="true"></i><span>${orgWords(online?'在线':'离线',online?'Online':'Offline')}</span></span>`}
const orgMotion=()=>prefs().motion!==false&&document.documentElement.dataset.motion!=='false'&&document.documentElement.dataset.localSafe!=='true';
function orgCanvasContext(canvas){try{return canvas.getContext('2d')}catch{return null}}
function orgSceneFor(width=800,height=620){
 const account=user?.id;if(orgScene&&orgScene.account!==account){orgController?.stop();orgController=null;orgScene=null}
 if(!orgScene){orgScene=OrganizationModel.create({width,height,fontScale:prefs().fontScale||1,people:members,expanded:[...openDepartments]});orgScene.account=account}else{OrganizationModel.reconcile(orgScene,members,[...openDepartments])}return orgScene;
}
function orgNodeMarkup(n){
 const attrs=`data-org-node="${esc(n.id)}"`,style=`left:${n.x}px;top:${n.y}px;width:${n.r*2}px;height:${n.r*2}px;--dept-color:${OrganizationModel.color(n.dept)};`;
 if(n.kind==='root')return `<div class="org105-node org105-root aero-center" data-node-id="root" style="${style}"><b>冯如学媒</b><small>MEDIA CENTER</small></div>`;
 if(n.kind==='department'){const people=members.filter(p=>!p.owner&&p.dept===n.dept&&p.status==='active'),expanded=openDepartments.has(n.dept);return `<div class="org105-node aero-cluster" data-node-id="${esc(n.id)}" data-kind="department" style="${style}"><button class="dept-bubble" ${attrs} data-org-dept="${esc(n.dept)}" data-bubble-drag="${esc(n.dept)}" aria-expanded="${expanded}"><b>${esc(uiText(n.dept))}</b><small>${esc(uiText(OrganizationModel.descriptions[n.dept]))}</small><small>${people.length} ${orgWords('名成员','members')} · ${orgWords(expanded?'收起':'展开',expanded?'Collapse':'Expand')}</small></button></div>`}
 const p=n.person;return `<div class="org105-node person-bubble" data-node-id="${esc(n.id)}" data-kind="person" style="${style}"><button ${attrs} data-person="${esc(p.id)}" aria-label="${esc(p.name)}">${avatarMarkup(p)}<b>${esc(p.name)}</b><small>${esc(uiText(roleNames[p.role]||'成员'))}</small>${presenceMarkup(p,{compact:true})}</button></div>`;
}
organizationGraph=()=>{
 const s=orgSceneFor(),nodes=s.nodes,lines=OrganizationModel.links(s);
 return `<section class="panel organization org105"><div class="panel-head"><h2>${orgWords('组织架构图','Organization chart')}</h2><div class="org105-actions"><button class="text-btn" data-org-dept="">${orgWords('显示全部','Show all')}</button><button class="text-btn" data-collapse-org>${orgWords('收起全部','Collapse all')}</button></div></div><div class="org105-toolbar"><button type="button" data-org-zoom="out" aria-label="${orgWords('缩小','Zoom out')}">−</button><output data-org-zoom-label>${Math.round(s.view.zoom*100)}%</output><button type="button" data-org-zoom="in" aria-label="${orgWords('放大','Zoom in')}">＋</button><button type="button" data-org-reset>${orgWords('居中','Center')}</button></div><div class="aero-map org105-viewport" tabindex="0" role="group" aria-label="${orgWords('可缩放组织架构图','Zoomable organization chart')}"><canvas class="org-particles" aria-hidden="true"></canvas><div class="org105-world" style="width:${s.width}px;height:${s.height}px"><svg class="org-lines org105-lines" width="${s.width}" height="${s.height}" viewBox="0 0 ${s.width} ${s.height}">${lines.map(l=>`<line data-org-link="${esc(l.id)}" data-line="${esc(l.dept)}" x1="${l.x1}" y1="${l.y1}" x2="${l.x2}" y2="${l.y2}" stroke="${OrganizationModel.color(l.dept)}"/>`).join('')}</svg>${nodes.filter(n=>n.kind!=='person').map(orgNodeMarkup).join('')}${[...openDepartments].map(d=>`<div class="member-orbit" data-department-children="${esc(d)}">${nodes.filter(n=>n.kind==='person'&&n.dept===d).map(orgNodeMarkup).join('')}</div>`).join('')}</div></div></section>`;
};
expandOrganization=function(dept){if(!dept)openDepartments=new Set(depts);else openDepartments.has(dept)?openDepartments.delete(dept):openDepartments.add(dept);organizationDept='';render()};
function mountOrganization(){
 orgController?.stop();orgController=null;const map=$('.org105-viewport');if(!map)return;const s=orgSceneFor(map.clientWidth,map.clientHeight);OrganizationModel.resize(s,map.clientWidth,map.clientHeight,prefs().fontScale||1);if(!s.mounted){OrganizationModel.resetView(s);s.mounted=true}
 const world=map.querySelector('.org105-world'),canvas=map.querySelector('.org-particles'),particles=ParticleEngine.create({width:map.clientWidth,height:map.clientHeight,count:Math.min(48,prefs().particleDensity||48),settings:prefs().particleSystem}),elements=new Map([...world.querySelectorAll('[data-node-id]')].map(el=>[el.dataset.nodeId,el])),lineElements=new Map([...world.querySelectorAll('[data-org-link]')].map(el=>[el.dataset.orgLink,el])),points=new Map();let ctx=orgCanvasContext(canvas),frame=0,last=0,lastParticles=0,gesture=null,stopped=false,canvasFault=false;
 function local(e){const r=map.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}}
 function draw(){world.style.width=s.width+'px';world.style.height=s.height+'px';world.style.transform=`translate(${s.view.x}px,${s.view.y}px) scale(${s.view.zoom})`;map.style.setProperty('--org-zoom',s.view.zoom);for(const n of s.nodes){const el=elements.get(n.id);if(el){el.style.left=n.x.toFixed(3)+'px';el.style.top=n.y.toFixed(3)+'px';el.style.width=el.style.height=n.r*2+'px';el.dataset.held=String(n.held);el.dataset.radius=n.r}}for(const l of OrganizationModel.links(s)){const el=lineElements.get(l.id);if(el)for(const k of ['x1','y1','x2','y2'])el.setAttribute(k,l[k].toFixed(3))}world.querySelector('.org105-lines')?.setAttribute('viewBox',`0 0 ${s.width} ${s.height}`);$('[data-org-zoom-label]').textContent=Math.round(s.view.zoom*100)+'%';map.dataset.zoom=s.view.zoom;map.dataset.compact=String(s.view.zoom<.9);map.dataset.frame=String(Math.floor(performance.now()))}
 function failCanvas(){if(canvasFault)return;canvasFault=true;cancelAnimationFrame(frame);frame=0;ctx=null;window.WorkbenchRecovery?.capture('CANVAS_UNAVAILABLE','canvas');if(window.WorkbenchRecovery?.repair)window.WorkbenchRecovery.repair();else{document.documentElement.dataset.localSafe='true';document.documentElement.dataset.motion='false';stopParticles()}draw()}
 function tick(time){frame=0;if(stopped||!map.isConnected||document.hidden)return;if(!orgMotion()){ctx?.clearRect(0,0,map.clientWidth,map.clientHeight);draw();return}try{frame=requestAnimationFrame(tick);const dt=last?Math.min(.04,(time-last)/1000):1/60;last=time;OrganizationModel.step(s,dt,orgMotion());draw();if(time-lastParticles>=33){const pd=lastParticles?Math.min(.065,(time-lastParticles)/1000):1/30;lastParticles=time;const w=map.clientWidth,h=map.clientHeight,dpr=Math.min(devicePixelRatio||1,2);if(canvas.width!==Math.round(w*dpr)||canvas.height!==Math.round(h*dpr)){canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);ParticleEngine.resize(particles,w,h)}if(orgMotion()&&prefs().particles!=='off'){const rect=map.getBoundingClientRect(),contacts=(particleController?.pointers||[]).map(p=>({x:p.x-rect.left,y:p.y-rect.top}));ParticleEngine.step(particles,pd,contacts,prefs().themeColor);ParticleEngine.draw(ctx,particles,particleCanvas?.dataset.style||'constellation')}else ctx.clearRect(0,0,w,h);canvas.dataset.engine='physics';canvas.dataset.frame=String(Math.floor(time))}}catch{failCanvas()}}
 function midpoint(){const p=[...points.values()];return{x:(p[0].x+p[1].x)/2,y:(p[0].y+p[1].y)/2,d:Math.hypot(p[0].x-p[1].x,p[0].y-p[1].y)}}
 function down(e){if(e.button!==undefined&&e.button!==0)return;const point=local(e);points.set(e.pointerId,point);map.setPointerCapture?.(e.pointerId);e.preventDefault();if(points.size>1){OrganizationModel.endDrag(s,performance.now(),true);gesture={mode:'pinch',...midpoint(),moved:true};orgClickUntil=performance.now()+500;return}const id=e.target.closest('[data-org-node]')?.dataset.orgNode,position=OrganizationModel.unproject(s,point.x,point.y);if(id)OrganizationModel.beginDrag(s,id,position.x,position.y,performance.now());gesture={mode:id?'node':'pan',id,start:{...point},last:{...point},moved:false}}
 function move(e){if(!points.has(e.pointerId)||!gesture)return;const point=local(e);points.set(e.pointerId,point);if(points.size>1){const m=midpoint();if(gesture.mode!=='pinch'){OrganizationModel.endDrag(s,performance.now(),true);gesture={mode:'pinch',...m,moved:true};return}OrganizationModel.pan(s,m.x-gesture.x,m.y-gesture.y);OrganizationModel.setZoom(s,s.view.zoom*m.d/Math.max(1,gesture.d),m.x,m.y);gesture={mode:'pinch',...m,moved:true};draw();return}if(Math.hypot(point.x-gesture.start.x,point.y-gesture.start.y)>7)gesture.moved=true;if(gesture.moved){if(gesture.mode==='node'){const p=OrganizationModel.unproject(s,point.x,point.y);OrganizationModel.drag(s,p.x,p.y,performance.now())}else OrganizationModel.pan(s,point.x-gesture.last.x,point.y-gesture.last.y);gesture.last={...point};draw()}}
 function up(e){if(!points.has(e.pointerId))return;points.delete(e.pointerId);if(points.size){OrganizationModel.endDrag(s,performance.now(),true);if(points.size>1)gesture={mode:'pinch',...midpoint(),moved:true};else{const p=[...points.values()][0];gesture={mode:'pan',start:{...p},last:{...p},moved:true}}return}const completed=gesture;OrganizationModel.endDrag(s,performance.now(),e.type==='pointercancel');gesture=null;orgClickUntil=performance.now()+350;if(completed&&!completed.moved&&completed.id&&e.type!=='pointercancel'){const n=OrganizationModel.node(s,completed.id);if(n?.kind==='department')expandOrganization(n.dept);else if(n?.kind==='person'){personPinned=personPinned===n.person.id?'':n.person.id;if(personPinned)memberPreview(personPinned);else $('.member-profile-portal')?.remove()}}draw()}
 function click(e){if(e.target.closest('.org105-viewport')&&performance.now()<orgClickUntil&&e.detail!==0){e.preventDefault();e.stopImmediatePropagation();return}const b=e.target.closest('[data-org-zoom],[data-org-reset],.org105 [data-org-dept],.org105 [data-collapse-org],.org105 [data-person]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();if(b.dataset.person){personPinned=personPinned===b.dataset.person?'':b.dataset.person;if(personPinned)memberPreview(personPinned);else $('.member-profile-portal')?.remove()}else if(b.dataset.orgZoom)OrganizationModel.setZoom(s,s.view.zoom*(b.dataset.orgZoom==='in'?1.18:1/1.18));else if(b.dataset.orgReset!==undefined)OrganizationModel.resetView(s);else if(b.dataset.collapseOrg!==undefined){openDepartments.clear();render();return}else{expandOrganization(b.dataset.orgDept);return}draw()}
 function wheel(e){e.preventDefault();const p=local(e);OrganizationModel.setZoom(s,s.view.zoom*Math.exp(-e.deltaY*.0015),p.x,p.y);draw()}
 function visibility(){last=0;if(document.hidden){cancelAnimationFrame(frame);frame=0}else if(!frame&&!stopped)frame=requestAnimationFrame(tick)}
 const observer=new ResizeObserver(()=>{if(!map.isConnected)return;OrganizationModel.resize(s,map.clientWidth,map.clientHeight,prefs().fontScale||1);draw()});observer.observe(map);
 for(const[type,handler]of [['pointerdown',down],['pointermove',move],['pointerup',up],['pointercancel',up]])map.addEventListener(type,handler);map.addEventListener('wheel',wheel,{passive:false});document.addEventListener('click',click,true);document.addEventListener('visibilitychange',visibility);draw();if(!ctx)failCanvas();else frame=requestAnimationFrame(tick);
 orgController={scene:s,get active(){return !!gesture},stop(){stopped=true;cancelAnimationFrame(frame);observer.disconnect();OrganizationModel.endDrag(s,performance.now(),true);for(const[type,handler]of [['pointerdown',down],['pointermove',move],['pointerup',up],['pointercancel',up]])map.removeEventListener(type,handler);map.removeEventListener('wheel',wheel);document.removeEventListener('click',click,true);document.removeEventListener('visibilitychange',visibility);points.clear()}};
}
const org105Render=render;render=function(){org105Render();mountOrganization()};
const org105Auth=auth;auth=function(...args){orgController?.stop();orgController=null;orgScene=null;org105Auth(...args)};
document.addEventListener('contextmenu',e=>{const b=e.target.closest('.org105 [data-person]');if(!b)return;e.preventDefault();personPinned=b.dataset.person;memberPreview(personPinned)});
document.addEventListener('focusin',e=>{const b=e.target.closest('.org105 [data-person]');if(b)memberPreview(b.dataset.person)});
document.addEventListener('focusout',e=>{if(e.target.closest('.org105 [data-person]')&&!personPinned&&!e.relatedTarget?.closest('.member-profile-portal'))$('.member-profile-portal')?.remove()});
