// Canvas adapter for the shared physics engine; no interaction interception.
let particleController;
function createParticleController(canvas,preferences){
 const ctx=canvas.getContext('2d'),contacts=new Map(),settings=preferences.particleSystem,styles=Object.keys(particleNames).filter(k=>!['off','random','rotate'].includes(k)),randomStyle=styles[Math.floor(Math.random()*styles.length)],system=ParticleEngine.create({width:innerWidth,height:innerHeight,count:preferences.particleDensity||48,settings});
 let frameId=0,last=0,epoch=performance.now(),disposed=false;
 const pointer=e=>{if(e.pointerType!=='touch')contacts.set(e.pointerId||0,{x:e.clientX,y:e.clientY})},leave=e=>{if(!e.relatedTarget)contacts.delete(e.pointerId||0)},touch=e=>{for(const[key]of contacts)if(String(key).startsWith('touch:'))contacts.delete(key);for(const point of e.touches||[])contacts.set('touch:'+point.identifier,{x:point.clientX,y:point.clientY})};
 document.addEventListener('pointermove',pointer,{passive:true});document.addEventListener('pointerdown',pointer,{passive:true});document.addEventListener('pointerout',leave,{passive:true});document.addEventListener('touchstart',touch,{passive:true});document.addEventListener('touchmove',touch,{passive:true});document.addEventListener('touchend',touch,{passive:true});document.addEventListener('touchcancel',touch,{passive:true});
 const visibility=()=>{last=0;if(document.hidden){cancelAnimationFrame(frameId);frameId=0;contacts.clear()}else if(!frameId&&!disposed)frameId=requestAnimationFrame(frame)};document.addEventListener('visibilitychange',visibility);
 canvas.style.zIndex='24';canvas.style.pointerEvents='none';canvas.dataset.engine='physics';canvas.dataset.edgeCount=String(system.particles.filter(p=>p.edge).length);canvas.dataset.centerCount=String(system.particles.filter(p=>!p.edge).length);
 function frame(time){frameId=0;if(disposed||!canvas.isConnected||document.hidden)return;frameId=requestAnimationFrame(frame);if(last&&time-last<33)return;const dt=last?Math.min(.065,(time-last)/1000):1/30;last=time;const w=innerWidth,h=innerHeight,dpr=Math.min(devicePixelRatio||1,2);if(canvas.width!==Math.round(w*dpr)||canvas.height!==Math.round(h*dpr)){canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);ParticleEngine.resize(system,w,h)}
  const mode=preferences.particles||'constellation',style=mode==='random'?randomStyle:mode==='rotate'?styles[Math.floor((time-epoch)/((preferences.rotationMinutes||5)*60000))%styles.length]:mode;ParticleEngine.step(system,dt,[...contacts.values()],preferences.themeColor);ParticleEngine.draw(ctx,system,style);canvas.dataset.frame=String(Math.floor(time));canvas.dataset.style=style;canvas.dataset.respawns=String(system.respawns);canvas.dataset.contacts=String(contacts.size);
 }
 frameId=requestAnimationFrame(frame);
 return {system,get pointers(){return [...contacts.values()]},stop(){disposed=true;cancelAnimationFrame(frameId);document.removeEventListener('pointermove',pointer);document.removeEventListener('pointerdown',pointer);document.removeEventListener('pointerout',leave);for(const type of ['touchstart','touchmove','touchend','touchcancel'])document.removeEventListener(type,touch);document.removeEventListener('visibilitychange',visibility);contacts.clear()}};
}
