const initialized=new WeakMap(),TTL=90000;
function rawDB(db){return db.rawDB||db}
export async function ensurePresence(input){const db=rawDB(input);if(!initialized.has(db))initialized.set(db,db.prepare('CREATE TABLE IF NOT EXISTS member_presence (session TEXT NOT NULL,client TEXT NOT NULL,user TEXT NOT NULL,seen INTEGER NOT NULL,active INTEGER NOT NULL,seq INTEGER NOT NULL,PRIMARY KEY(session,client))').run().catch(error=>{initialized.delete(db);throw error}));return initialized.get(db)}
export async function onlineUsers(input,now=Date.now()){const db=rawDB(input);await ensurePresence(db);const rows=await db.prepare("SELECT DISTINCT member_presence.user FROM member_presence JOIN sessions ON sessions.hash=member_presence.session JOIN users ON users.id=member_presence.user WHERE member_presence.active=1 AND member_presence.seen>? AND sessions.expires>? AND users.status='active'").bind(now-TTL,now).all();return new Set(rows.results.map(x=>x.user))}
export async function heartbeat(input,user,session,data,fail){const db=rawDB(input);await ensurePresence(db);if(typeof data.active!=='boolean'||typeof data.client!=='string'||!/^[a-zA-Z0-9_-]{8,80}$/.test(data.client)||!Number.isSafeInteger(data.seq)||data.seq<1)fail(400,'在线状态请求无效');const now=Date.now();
 const result=await db.prepare("INSERT INTO member_presence (session,client,user,seen,active,seq) SELECT ?,?,?,?,?,? WHERE EXISTS (SELECT 1 FROM sessions JOIN users ON users.id=sessions.user WHERE sessions.hash=? AND users.id=? AND sessions.expires>? AND users.status='active') AND (NOT EXISTS (SELECT 1 FROM review_configuration WHERE id=1 AND enabled=1) OR EXISTS (SELECT 1 FROM users WHERE id=? AND owner=1)) ON CONFLICT(session,client) DO UPDATE SET seen=excluded.seen,active=excluded.active,seq=excluded.seq WHERE excluded.seq>member_presence.seq").bind(session,data.client,user.id,now,data.active?1:0,data.seq,session,user.id,now,user.id).run();
 await db.prepare('DELETE FROM member_presence WHERE seen<? OR NOT EXISTS (SELECT 1 FROM sessions WHERE sessions.hash=member_presence.session AND sessions.expires>?)').bind(now-600000,now).run();
 await db.prepare('DELETE FROM member_presence WHERE user=? AND (session,client) NOT IN (SELECT session,client FROM member_presence WHERE user=? ORDER BY seen DESC LIMIT 32)').bind(user.id,user.id).run();
 return {ok:true,accepted:!!result.meta.changes,online:(await onlineUsers(db,now)).has(user.id)};
}
export async function clearPresence(db,session){await ensurePresence(db);await rawDB(db).prepare('DELETE FROM member_presence WHERE session=?').bind(session).run()}
