// Local-only recovery. Never serialize request details, content, identities, cookies, URLs or errors.
(()=>{
 const version='v1.0.5',modules=new Set(['ui','network','storage','canvas','startup']),codes=new Set(['NETWORK_FAILURE','STATE_INVALID','AUTH_REQUIRED','ACCESS_REVOKED','STATE_RECOVERED','STORAGE_UNAVAILABLE','CACHE_REPAIRED','VIEW_RENDER','CANVAS_UNAVAILABLE','SAFE_MODE','LOCAL_REPAIRED','MUTATION_BLOCKED','UNKNOWN']);
 const records=[],counts={},displayCache=['fr.display','fr.layout','fr.ui.cache'];
 let readonly=false,trusted=false,safeMode=false,localAppearanceReset=false,accountEpoch=0,automaticRepairs=0,retryCount=0,retryTimer=0,allowProbe=false,retryBusy=false,lastStateAt=0,storageOK=true,renderOK=true,canvasOK=true,securityOpen=false;
 const label=(zh,en)=>state?.settings?.language==='en'?en:zh;
 function capture(value,category='ui'){
  const module=modules.has(category)?category:'ui',code=typeof value==='string'&&codes.has(value)?value:({network:'NETWORK_FAILURE',storage:'STORAGE_UNAVAILABLE',canvas:'CANVAS_UNAVAILABLE'}[module]||'UNKNOWN');
  if(code==='CANVAS_UNAVAILABLE')canvasOK=false;if(code==='VIEW_RENDER')renderOK=false;if(code==='STORAGE_UNAVAILABLE')storageOK=false;
  counts[code]=(counts[code]||0)+1;records.push({code,module,at:new Date().toISOString()});if(records.length>40)records.shift();return code;
 }
 function language(){try{const lang=localStorage.getItem('fr.language');return lang==='en'?'en':'zh-CN'}catch{storageOK=false;return 'zh-CN'}}
 function normalizeSettings(raw){const p=raw&&typeof raw==='object'&&!Array.isArray(raw)?raw:{},number=(v,a,b,d)=>Number.isFinite(v)?Math.max(a,Math.min(b,v)):d;return {workspace:depts.includes(p.workspace)?p.workspace:'',themeColor:typeof p.themeColor==='string'&&/^#[0-9a-f]{6}$/i.test(p.themeColor)?p.themeColor:'#e77b24',fontScale:number(p.fontScale,.85,1.35,1),particleDensity:Math.round(number(p.particleDensity,10,80,48)),rotationMinutes:Math.round(number(p.rotationMinutes,1,60,5)),motion:p.motion!==false,appearance:['light','dark','auto'].includes(p.appearance)?p.appearance:'light',particles:Object.hasOwn(particleNames,p.particles)?p.particles:'constellation',particleSystem:ParticleEngine.normalize(p.particleSystem),language:['zh-CN','en'].includes(p.language)?p.language:language()}}
 state.settings=normalizeSettings(state.settings);
 function inspectStorage(){try{localStorage.getItem('fr.language');if(typeof localStorage.setItem==='function'){const old=localStorage.getItem('fr.localProbe');localStorage.setItem('fr.localProbe','1');if(old===null)localStorage.removeItem('fr.localProbe');else localStorage.setItem('fr.localProbe',old)}storageOK=true;for(const key of displayCache){const value=localStorage.getItem(key);if(value!==null)try{JSON.parse(value)}catch{localStorage.removeItem(key);capture('CACHE_REPAIRED','storage')}}}catch{storageOK=false;capture('STORAGE_UNAVAILABLE','storage')}return storageOK}
 function health(){return {version,local:true,readOnly:readonly,safeAppearance:safeMode,storage:storageOK,dom:!!document.querySelector('#app'),render:renderOK,canvas:canvasOK,lastStateAt:lastStateAt?new Date(lastStateAt).toISOString():null,retryAttempts:retryCount,automaticRepairs,configurationValid:!!prefs().particleSystem}}
 function diagnostic(){const browser=/(Edg|Chrome|Firefox|Version)\/(\d+)/.exec(navigator.userAgent||'');return {schema:1,version,modules:{recovery:'1',particles:'1'},health:health(),browser:browser?{family:{Edg:'Edge',Chrome:'Chromium',Firefox:'Firefox',Version:'Safari'}[browser[1]],major:Number(browser[2])}:{family:'Other',major:0},counts:{...counts},recent:records.map(x=>({...x}))}}
 function banner(){let el=document.querySelector('.recovery-banner');if(!readonly&&!safeMode){el?.remove();return}if(!el){el=document.createElement('section');el.className='recovery-banner';el.setAttribute('role','status');document.querySelector('main')?.prepend(el)}if(!el.isConnected)return;el.innerHTML=`<div><b>${readonly?label('连接中断 · 当前内容只读','Connection interrupted · Read-only content'):label('本机安全外观已启用','Local safe appearance is enabled')}</b><p>${readonly?label('保留本次会话已读取的内容；重新同步前暂不能提交修改。','Previously read session content is retained. Sync again before making changes.'):label('粒子与漂浮已在本机暂停，账号设置保持原值。','Particles and floating motion are paused locally. Account settings are unchanged.')}</p></div><button class="secondary" data-local-retry>${label('重新检查','Check again')}</button><button class="text-btn" data-local-security>${label('本机安全中心','Local safety center')}</button>`}
 function cancelRetries(){clearTimeout(retryTimer);retryTimer=0}
 function scheduleRetry(){if(retryTimer||retryBusy||retryCount>=3||!readonly)return;retryTimer=setTimeout(async()=>{retryTimer=0;retryCount++;retryBusy=true;allowProbe=true;try{await refresh()}catch{}finally{allowProbe=false;retryBusy=false;scheduleRetry()}},[2000,5000,10000][retryCount])}
 function failure(code){capture(code,'network');if(trusted&&user){readonly=true;banner();scheduleRetry()}}
 function denyMessage(){return label('当前内容只读，请先重新同步。','This content is read-only. Sync again first.')}
 const priorApi=api;
 api=async function(path,data){
  if(data&&['login','logout','register','recover','setup'].includes(path)){accountEpoch++;if(typeof refreshSerial!=='undefined')refreshSerial++;trusted=false;cancelRetries()}
  const requestEpoch=accountEpoch,identity=user?.id,stale=()=>requestEpoch!==accountEpoch;
  if(data&&readonly&&!['login','captcha','logout','register','recover','setup'].includes(path)){capture('MUTATION_BLOCKED','network');throw Error(denyMessage())}
  if(path!=='state'||data){try{const result=await priorApi(path,data);if(stale())throw Error(label('会话已更新，请重新进入页面。','Session changed. Reopen the page.'));if(path==='settings/save'){localAppearanceReset=false;applyTheme()}return result}catch(e){if(!stale()&&data&&e.transient&&!['login','captcha','logout','register','recover','setup'].includes(path))failure('NETWORK_FAILURE');throw e}}
  if(readonly&&!allowProbe)throw Error(denyMessage());
  const controller=new AbortController(),deadline=setTimeout(()=>controller.abort(),8000);
  try{
  let response,b;
  try{response=await fetch('/api/state',{credentials:'same-origin',signal:controller.signal})}catch{if(!stale())failure('NETWORK_FAILURE');throw Error(label('暂时无法同步，请稍后重试。','Cannot sync right now. Try again shortly.'))}
  if(stale())throw Error(label('会话已更新，请重新进入页面。','Session changed. Reopen the page.'));
  if(response.status===401||response.status===403){capture(response.status===401?'AUTH_REQUIRED':'ACCESS_REVOKED','network');readonly=trusted=false;cancelRetries();members=[];state={tasks:[],events:[],people:[],logs:[],notices:[],settings:normalizeSettings()};user=null;auth('login',label('会话需要重新验证，请登录。','Please sign in to verify your session again.'));throw Error(label('请重新登录。','Please sign in again.'))}
  try{b=await response.json()}catch{if(!stale())failure('STATE_INVALID');throw Error(label('同步响应无效，请重试。','Invalid sync response. Try again.'))}
  if(stale())throw Error(label('会话已更新，请重新进入页面。','Session changed. Reopen the page.'));
  if(!response.ok){failure('NETWORK_FAILURE');throw Error(label('暂时无法同步，请稍后重试。','Cannot sync right now. Try again shortly.'))}
  if(!b||!b.user||!Array.isArray(b.tasks)||!Array.isArray(b.events)||!Array.isArray(b.people)||!Array.isArray(b.notices)){failure('STATE_INVALID');throw Error(label('同步响应无效，请重试。','Invalid sync response. Try again.'))}
  if(identity&&b.user.id!==identity){user=null;auth('login',label('账号已变更，请重新登录。','Account changed. Please sign in again.'));throw Error(label('账号已变更。','Account changed.'))}
  if(readonly)capture('STATE_RECOVERED','network');readonly=false;trusted=true;lastStateAt=Date.now();retryCount=0;cancelRetries();members=[];b.settings=normalizeSettings(b.settings);return b;
  }finally{clearTimeout(deadline)}
 };
 const priorRefresh=refresh;refresh=async function(...args){try{return await priorRefresh(...args)}catch(e){if(readonly&&trusted&&user){render();banner()}throw e}};
 const priorAuth=auth;auth=function(...args){accountEpoch++;if(typeof refreshSerial!=='undefined')refreshSerial++;readonly=trusted=false;members=[];knownTaskIds=null;state={tasks:[],events:[],people:[],logs:[],notices:[],settings:normalizeSettings()};cancelRetries();priorAuth(...args);const card=document.querySelector('.auth-card,.empty');if(card&&!card.querySelector('[data-local-security]')){const b=document.createElement('button');b.className='text-btn';b.dataset.localSecurity='';b.textContent=label('本机安全中心','Local safety center');card.append(b)}};
 const priorTheme=applyTheme;applyTheme=function(...args){priorTheme(...args);const root=document.documentElement;root.dataset.localSafe=String(safeMode);if(safeMode)root.dataset.motion='false';if(localAppearanceReset){root.style?.setProperty('--font-scale','1');root.style?.setProperty('--accent','#e77b24');root.style?.setProperty('--green','#e77b24');root.style?.setProperty('--light','color-mix(in srgb, #e77b24 10%, var(--surface))');root.dataset.dark='false'}};
 const priorParticles=startParticles;startParticles=function(...args){if(safeMode){stopParticles();return}try{return priorParticles(...args)}catch{canvasOK=false;capture('CANVAS_UNAVAILABLE','canvas');enterSafeMode()}};
 function enterSafeMode(){if(safeMode)return;safeMode=true;capture('SAFE_MODE','ui');try{stopParticles()}catch{}applyTheme();banner()}
 const priorRender=render;render=function(...args){try{priorRender(...args);renderOK=true;banner()}catch{renderOK=false;capture('VIEW_RENDER','ui');enterSafeMode();const app=document.querySelector('#app');if(app)app.innerHTML=`<main class="recovery-fallback"><h1>冯如学媒</h1><p>${label('界面遇到问题，账号与服务器数据保持不变。','The interface encountered a problem. Your account and server data are unchanged.')}</p><button class="primary" data-local-retry>${label('重新检查','Check again')}</button><button class="secondary" data-local-security>${label('本机安全中心','Local safety center')}</button></main>`;automaticRepair()}};
 function automaticRepair(){if(automaticRepairs>=2)return;automaticRepairs++;queueMicrotask(()=>{inspectStorage();enterSafeMode()})}
 function repair(){inspectStorage();for(const key of displayCache)try{localStorage.removeItem(key)}catch{storageOK=false};capture('LOCAL_REPAIRED','storage');enterSafeMode();banner();return health()}
 async function retry(){if(retryBusy)return health();retryBusy=true;cancelRetries();retryCount=0;allowProbe=true;const wasSafe=safeMode;safeMode=false;canvasOK=true;inspectStorage();try{if(user)await refresh();else await boot();applyTheme();if(user&&!readonly){startParticles();if(typeof mountOrganization==='function')mountOrganization()}if(readonly)safeMode=wasSafe}catch{safeMode=wasSafe;applyTheme()}finally{allowProbe=false;retryBusy=false;scheduleRetry();banner();if(securityOpen&&document.querySelector('[data-local-center]'))open()}return health()}
 async function resetAppearance(){localAppearanceReset=true;capture('LOCAL_REPAIRED','ui');applyTheme();return health()}
 function centerTabs(){return `<div class="settings-tabs recovery-tabs">${[['general','通用','General'],['appearance','外观','Appearance'],['account','账号与安全','Account & security'],['security','安全中心','Safety center']].map(([id,zh,en])=>`<button class="${id==='security'?'primary':'secondary'}" data-settings-tab="${id}">${label(zh,en)}</button>`).join('')}</div>`}
 function localLog(){return `<section class="recovery-local-log"><h3>${label('近期本机错误摘要','Recent local error codes')}</h3>${records.slice(-8).reverse().map(r=>`<p><time>${esc(new Date(r.at).toLocaleTimeString(uiLanguage()))}</time><code>${esc(r.code)}</code><small>${esc(r.module)}</small></p>`).join('')||`<p class="sub">${label('尚无近期错误','No recent errors')}</p>`}<small>${label('仅保存固定错误码与时间。遇到显示问题可先修复缓存或重置本机外观，再重新检查。','Only fixed codes and timestamps are retained. Repair display cache or reset local appearance, then check again.')}</small></section>`}
 function open(){securityOpen=true;const h=health(),items=[[label('本次会话的本机快照','Local session snapshot'),readonly?label('只读 · 等待重新同步','Read-only · Waiting for sync'):user?label('可编辑','Editable'):label('尚未登录','Not signed in')],[label('本机缓存','Local cache'),h.storage?label('可访问','Available'):label('不可访问 · 使用内存','Unavailable · Memory only')],[label('界面与画布','Interface & canvas'),h.render&&h.canvas?label('可用','Available'):label('已降级','Degraded')],[label('本机外观','Local appearance'),safeMode?label('安全外观 · 暂停动态','Safe appearance · Motion paused'):label('使用账号设置','Using account settings')]];modal(label('本机安全中心','Local safety center'),centerTabs()+`<div data-local-center><p class="sub">${label('检查和诊断仅在本机进行，不上传任务、成员资料或触控位置。','Checks and diagnostics stay on this device. Tasks, member details and touch positions are not uploaded.')}</p><div class="recovery-health">${items.map(([name,value])=>`<article><h3>${name}</h3><p>${value}</p></article>`).join('')}</div><div class="recovery-actions"><button class="primary" data-local-retry>${label('重新检查并恢复','Check again & restore')}</button><button class="secondary" data-local-repair>${label('修复本机显示缓存','Repair local display cache')}</button><button class="secondary" data-local-copy>${label('复制安全诊断','Copy safe diagnostics')}</button>${user?`<button class="text-btn" data-local-reset>${label('重置本机颜色与字号','Reset local color & text size')}</button>`:''}</div><p class="sub">${label('修复只清理显示缓存，保留登录、语言、账号偏好和连接设置。安全外观仅在本机生效；复制诊断不包含错误原文、账号或页面地址。','Repair clears display cache only. Sign-in, language, account preferences and connection settings are retained. Safe appearance is local only; diagnostics contain no error text, accounts or page addresses.')}</p>${localLog()}<p class="recovery-summary">${label('版本','Version')} ${version} · ${label('有限自动重试','Bounded retries')} ${h.retryAttempts}/3</p></div>`)}
 const priorSettings=settingsForm;settingsForm=function(tab='general'){if(tab==='security')return open();securityOpen=false;priorSettings(tab);const tabs=document.querySelector('.settings-tabs');if(tabs&&!tabs.querySelector('[data-settings-tab="security"]')){const b=document.createElement('button');b.className='secondary';b.dataset.settingsTab='security';b.textContent=label('安全中心','Safety center');tabs.append(b)}};
 document.addEventListener('click',async e=>{const b=e.target.closest('[data-local-security],[data-local-repair],[data-local-copy],[data-local-retry],[data-local-reset],[data-refresh]');if(!b)return;try{if(b.hasAttribute('data-refresh'))allowProbe=true;if(b.hasAttribute('data-local-security'))open();if(b.hasAttribute('data-local-repair')){repair();open()}if(b.hasAttribute('data-local-retry'))await retry();if(b.hasAttribute('data-local-copy')){await navigator.clipboard.writeText(JSON.stringify(diagnostic(),null,2));toast(label('安全诊断已复制','Safe diagnostics copied'))}if(b.hasAttribute('data-local-reset')){await resetAppearance();open()}}catch{toast(label('本机操作未完成，请重试。','Local action did not finish. Try again.'))}finally{if(b.hasAttribute('data-refresh'))allowProbe=false}},true);
 document.addEventListener('visibilitychange',()=>{if(document.hidden)cancelRetries();else scheduleRetry()});window.addEventListener('online',()=>{if(readonly)retry()});window.addEventListener('pagehide',cancelRetries);
 window.addEventListener('error',e=>{if(typeof ErrorEvent!=='undefined'&&e instanceof ErrorEvent){capture('VIEW_RENDER','ui');automaticRepair()}});window.addEventListener('unhandledrejection',()=>{capture('UNKNOWN','ui');automaticRepair()});
 inspectStorage();window.WorkbenchRecovery=Object.freeze({health,diagnostic,repair,capture,isReadOnly:()=>readonly,resetAppearance,open,retry,normalizeSettings});
})();
