import TaskModel from '../../miniprogram/utils/task-model.js';
import ScheduleModel from '../../miniprogram/utils/schedule-model.js';
export const standardChecks=['核对活动信息与交付要求','整理成果与交接说明'];
export async function activeTaskPeople(db){return (await db.prepare("SELECT id,name,dept,role,status,owner FROM users WHERE status='active'").all()).results}
export function readIds(input,scalar,old,fail){const list=input===undefined?(scalar===undefined?old:[scalar]):input;if(!Array.isArray(list)||!list.length||list.length>12||list.some(id=>typeof id!=='string'||!id)||new Set(list).size!==list.length)fail(400,'请选择 1—12 位不重复的成员');return list}
export function validateTaskParties(b,old,people,event,fail){const os=readIds(b.owners,b.owner??b.owner_id,TaskModel.owners(old||{}),fail),rs=readIds(b.receivers??b.reviewers,b.receiver??b.reviewer_id,TaskModel.receivers(old||{}),fail),owners=os.map(id=>people.find(p=>p.id===id)),receivers=rs.map(id=>people.find(p=>p.id===id));if(owners.some(p=>!p||p.owner)||receivers.some(p=>!p))fail(400,'请选择已开通成员；初始管理员不能被派为执行人');if(event?.department&&(owners.some(p=>p.dept!==event.department)||receivers.some(p=>!p.owner&&p.dept!==event.department)))fail(400,'部门内部任务只能分配给本部门成员');return {owners:os,receivers:rs,owner:os[0],receiver:rs[0],owner_id:os[0],reviewer_id:rs[0],dept:owners[0].dept,depts:[...new Set(owners.map(p=>p.dept))]}}
export function taskChecks(value,text,fail){const checks=value===undefined?standardChecks:value;if(!Array.isArray(checks)||!checks.length||checks.length>20)fail(400,'检查清单须包含 1—20 项');return checks.map(x=>text(x,200))}
export function taskDependencies(value,eventId,taskId,s,fail){const list=value||[];if(!Array.isArray(list)||list.length>50||new Set(list).size!==list.length||list.some(id=>typeof id!=='string'||id===taskId||!s.tasks.some(t=>t.id===id&&t.event===eventId)))fail(400,'前序任务无效');for(const id of list){const stack=[id],seen=new Set();while(stack.length){const next=stack.pop();if(next===taskId)fail(400,'前序依赖不能构成循环');if(seen.has(next))continue;seen.add(next);if(seen.size>5000)fail(400,'前序关系过多，请简化流程');stack.push(...(s.tasks.find(t=>t.id===next)?.depends||[]))}}return list}
export function taskReward(value,fail){if(value==null||value==='')return 0;if(!['number','string'].includes(typeof value)||typeof value==='string'&&!/^\d+$/.test(value))fail(400,'积分须为 0—10000 的整数');const n=Number(value);if(!Number.isSafeInteger(n)||n<0||n>10000)fail(400,'积分须为 0—10000 的整数');return n}
function complete(s,t,ev,u,people,log){t.status='done';t.feedback='';t.archivedAt=new Date().toISOString();t.archivedBy=u.id;if(!t.rewardPosted&&!s.ledger.some(x=>x.task===t.id)){const recipients=TaskModel.owners(t).filter(id=>!people.find(p=>p.id===id)?.owner),units=(t.rewardPoints||0)*100,base=Math.floor(units/Math.max(1,recipients.length)),remainder=units-base*recipients.length;recipients.forEach((id,i)=>s.ledger.push({id:crypto.randomUUID(),task:t.id,event:t.event,user:id,dept:people.find(p=>p.id===id)?.dept||t.dept,points:(base+(i<remainder?1:0))/100,note:t.rewardNote||'',taskName:t.name,eventName:ev.name,time:t.archivedAt,approvedBy:u.id}));t.rewardPosted=true}log(s,`「${t.name}」已通过验收并归档`,TaskModel.owners(t),ev.department||'');for(const next of s.tasks)if(next.status==='blocked'&&next.depends.every(id=>s.tasks.find(x=>x.id===id)?.status==='done')){next.status='pending';log(s,`「${next.name}」已解锁，请确认`,TaskModel.owners(next),ev.department||'')}}
function submission(b,t,ev,u,h){const {fail,text}=h,checked=b.checked??t.checked;if(!Array.isArray(checked)||checked.length!==t.checks.length||checked.some(x=>x!==true))fail(400,'请完成全部检查项');const link=typeof(b.link??t.link)==='string'?(b.link??t.link??'').trim():'';if(link){let parsed;try{parsed=new URL(link)}catch{fail(400,'链接无效')}if(!['https:','http:'].includes(parsed.protocol)||parsed.username||parsed.password||link.length>2000)fail(400,'请填写有效的 http 或 https 成果链接');if((b.linkConfirmed??t.linkConfirmed)!==true)fail(400,'请确认成果链接可供验收人访问')}if(ev.cloudUrl){const confirmed=b.uploadConfirmed===true&&b.uploadUrl===ev.cloudUrl||b.uploadConfirmed===undefined&&t.uploadReceipt?.url===ev.cloudUrl;if(!confirmed)fail(400,'请打开当前活动素材库并确认已上传')}t.uploadReceipt=ev.cloudUrl?{url:ev.cloudUrl,confirmedAt:new Date().toISOString(),user:u.id}:null;t.linkConfirmed=!!link;t.checked=checked;t.submission=text(b.submission??t.submission,3000);t.link=link;t.submittedBy=u.id;t.submittedAt=new Date().toISOString()}
export async function taskAction(b,u,db,h){const {fail,text,date,shared,log}=h;return shared(db,async s=>{const people=(await db.prepare('SELECT id,name,dept,role,status,owner FROM users').all()).results,active=people.filter(p=>p.status==='active');const t=s.tasks.find(x=>x.id===b.id);if(!t)fail(404,'任务不存在');const ev=s.events.find(e=>e.id===t.event);if(!ev)fail(404,'所属活动不存在');if(!ScheduleModel.enabled(ev)&&!['edit','assign','reassign'].includes(b.action))fail(409,'日程尚未启用，可由负责人提前启用后执行');const perms=TaskModel.permissions(t,u,people,ev),os=TaskModel.owners(t),rs=TaskModel.receivers(t);switch(b.action){
 case 'accept':if(!perms.isOwner||t.status!=='pending')fail(403,'当前不能接受此任务');t.status='active';log(s,`${u.name} 接受了「${t.name}」`,rs,ev.department||'');break;
 case 'resume':if(!perms.isOwner||t.status!=='conflict')fail(403,'当前不能恢复接活');if(t.depends.some(id=>s.tasks.find(x=>x.id===id)?.status!=='done'))fail(409,'前序任务尚未完成');t.status=t.beforeConflict==='revise'?'revise':'active';t.feedback=t.revisionFeedback||'';delete t.beforeConflict;delete t.revisionFeedback;log(s,`${u.name} 恢复接活「${t.name}」`,rs,ev.department||'');break;
 case 'conflict':if(!perms.isOwner||!['pending','active','revise'].includes(t.status))fail(403,'当前不能反馈冲突');t.beforeConflict=t.status;t.revisionFeedback=t.status==='revise'?t.feedback:'';t.feedback=text(b.feedback,1000);t.status='conflict';log(s,`「${t.name}」有时间冲突`,ev.createdBy,ev.department||'');break;
 case 'submit':if(!(perms.isOwner&&['active','revise'].includes(t.status)||perms.canProxySubmit&&['pending','active','revise','conflict'].includes(t.status)))fail(403,'当前不能提交此任务');if(t.depends.some(id=>s.tasks.find(x=>x.id===id)?.status!=='done'))fail(409,'前序任务尚未完成');submission(b,t,ev,u,h);t.status='review';log(s,`「${t.name}」已提交，请验收`,rs,ev.department||'');break;
 case 'approve':if(!perms.isReviewer||t.status!=='review')fail(403,'无权验收或任务状态已更新');complete(s,t,ev,u,people,log);break;
 case 'archive':if(!perms.canArchive||t.status==='done')fail(403,'无权代交付归档或任务已完成');if(t.depends.some(id=>s.tasks.find(x=>x.id===id)?.status!=='done'))fail(409,'前序任务尚未完成，不能归档');submission(b,t,ev,u,h);complete(s,t,ev,u,people,log);break;
 case 'reject':if(!perms.isReviewer||t.status!=='review')fail(403,'无权退回此任务');t.status='revise';t.feedback=text(b.feedback,1000);log(s,`「${t.name}」需要修改`,os,ev.department||'');break;
 case 'reassign':{if(!perms.canReassign)fail(403,'只能将自己负责的未完成任务转派给本部门下属');const replacements=readIds(b.owners,b.owner,[],fail);if(replacements.some(id=>{const p=active.find(p=>p.id===id);return !p||p.owner||p.dept!==u.dept||p.role!=='member'}))fail(403,'转派只能选择本部门普通成员');const next=[...new Set([...os.filter(id=>id!==u.id),...replacements])];Object.assign(t,validateTaskParties({owners:next,receivers:rs},t,active,ev,fail));t.status=t.depends.some(id=>s.tasks.find(x=>x.id===id)?.status!=='done')?'blocked':'pending';t.checked=t.checks.map(()=>false);t.submission='';t.link='';t.uploadReceipt=null;t.linkConfirmed=false;t.feedback='';log(s,`「${t.name}」已转派，积分随最终执行人归档`,next,ev.department||'');break}
 case 'edit':case 'assign':{if(!perms.canEdit)fail(403,'不能编辑此任务');const party=validateTaskParties(b,t,active,ev,fail),depends=taskDependencies(b.depends??t.depends,t.event,t.id,s,fail),checks=taskChecks(b.checks??t.checks,text,fail),priority=b.priority??t.priority??'normal';if(!['low','normal','high','urgent'].includes(priority))fail(400,'任务优先级无效');Object.assign(t,party,{name:text(b.name??t.name,100),due:date(b.due??t.due,true),requirements:text(b.requirements??t.requirements,3000),depends,checks,priority,rewardPoints:taskReward(b.rewardPoints??t.rewardPoints,fail),rewardNote:b.rewardNote===undefined?t.rewardNote||'':b.rewardNote===''?'':text(b.rewardNote,500),status:depends.some(id=>s.tasks.find(x=>x.id===id)?.status!=='done')?'blocked':'pending',checked:checks.map(()=>false),feedback:'',submission:'',link:'',uploadReceipt:null,linkConfirmed:false});log(s,`「${t.name}」任务参数与分工已更新`,t.owners,ev.department||'');break}
 default:fail(400,'操作无效')}const now=new Date().toISOString();Object.assign(t,{updatedBy:u.id,updatedByName:u.name||'',updatedAt:now});Object.assign(ev,{updatedBy:u.id,updatedByName:u.name||'',updatedAt:now});return {ok:true}},u)}
