import {visibleWorkspace} from './visibility.js';
import TaskModel from '../../miniprogram/utils/task-model.js';
import {taskAction} from './task-actions.js';
import {guard,issueChallenge,consumeChallenge,failedPassword,succeedPassword,clearPasswordGuard} from './login-security.js';
import {recordRequest,readStatistics,maintainStatistics} from './observability.js';
import bcrypt from 'bcryptjs';
import {ensurePreferences,readPreferences,preferenceRoutes} from './preferences.js';
import {ensureProfiles,profileRoutes} from './profiles.js';
import assets from './assets.generated.js';
import {workflows,normalizeWorkspace,extendState} from './workflows.js';
const DEPTS=['办公室','新媒体运营部','视觉传达部','创意设计部'];
const DAY=86400000, blank=()=>({events:[],tasks:[],logs:[],notices:[]});
const json=(data,status=200,headers={})=>new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store',...headers}});
function fail(status,message){throw Object.assign(new Error(message),{status})}
function text(v,max=100){if(typeof v!=='string'||!v.trim()||v.length>max)fail(400,'请检查输入内容');return v.trim()}
const random=()=>Array.from(crypto.getRandomValues(new Uint8Array(32)),b=>b.toString(16).padStart(2,'0')).join('');
const digest=async s=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s))),b=>b.toString(16).padStart(2,'0')).join('');
const safeUser=u=>({id:u.id,username:u.username,name:u.name,dept:u.owner?'':u.dept,role:u.role,status:u.status,owner:!!u.owner,avatar:u.avatar||''});
const admin=u=>u?.role==='admin';
const manager=u=>['admin','manager'].includes(u?.role);
function pass(p){if(typeof p!=='string'||p.length<10||bcrypt.truncates(p))fail(400,'密码至少 10 个字符，UTF-8 编码不超过 72 字节');return p}
function userFields(b){const username=text(b.username,32).toLowerCase();if(!/^[a-z0-9][a-z0-9_.-]{2,31}$/.test(username))fail(400,'用户名请用 3—32 位英文字母、数字或 . _ -');const name=text(b.name,30);if(!DEPTS.includes(b.dept))fail(400,'请选择部门');return {username,name,dept:b.dept}}
const cookie=token=>`fr_session_v2=${token}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=${7*86400}`;
const clearCookie='fr_session_v2=; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=0';
async function session(req,db){const raw=(req.headers.get('cookie')||'').match(/(?:^|;\s*)fr_session_v2=([a-f0-9]{64})(?:;|$)/)?.[1];if(!raw)return null;return db.prepare('SELECT users.* FROM sessions JOIN users ON users.id=sessions.user WHERE sessions.hash=? AND sessions.expires>?').bind(await digest(raw),Date.now()).first()}
async function startSession(db,u){const token=random();await db.batch([db.prepare('DELETE FROM sessions WHERE expires<?').bind(Date.now()),db.prepare('INSERT INTO sessions (hash,user,expires) VALUES (?,?,?)').bind(await digest(token),u.id,Date.now()+7*DAY)]);return cookie(token)}
async function limit(db,key,max){const now=Date.now(),bucket=Math.floor(now/(15*60*1000));const k=await digest(key+':'+bucket);const row=await db.prepare('INSERT INTO limits (key,hits,expires) VALUES (?,1,?) ON CONFLICT(key) DO UPDATE SET hits=hits+1 RETURNING hits').bind(k,now+30*60*1000).first();if(row.hits>max)fail(429,'操作过于频繁，请 15 分钟后再试')}
async function body(req){if(!req.headers.get('content-type')?.includes('application/json'))fail(415,'请使用 JSON 请求');const data=await req.text();if(data.length>24000)fail(413,'提交内容过大');try{const b=JSON.parse(data);if(!b||Array.isArray(b)||typeof b!=='object')throw Error();return b}catch{fail(400,'请求格式不正确')}}
function date(v,hasTime=false){if(typeof v!=='string'||!(hasTime?/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}$/:/^\d{4}-\d{2}-\d{2}$/).test(v)||!Number.isFinite(Date.parse(v)))fail(400,'日期格式不正确');return v}
function shift(v,days){const d=new Date(v.slice(0,10)+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+days);return d.toISOString().slice(0,10)+v.slice(10)}
function log(s,message,target='all',department=''){if(!department){const e=s.events.find(e=>e.department&&message.includes('「'+e.name+'」'))||s.events.find(e=>e.department&&s.tasks.some(t=>t.event===e.id&&message.includes('「'+t.name+'」')));department=e?.department||''}s.logs.unshift({text:message,time:new Date().toISOString()});s.logs=s.logs.slice(0,200);s.notices.unshift({text:message,target,department});s.notices=s.notices.slice(0,200)}
function canManageEvent(u,e){return !!e&&(admin(u)||manager(u)&&e.createdBy===u.id)}
async function shared(db,mutate,u){for(let attempt=0;attempt<3;attempt++){await db.prepare('INSERT OR IGNORE INTO workspace (id,version,data) VALUES (1,0,?)').bind(JSON.stringify(blank())).run();const row=await db.prepare('SELECT version,data FROM workspace WHERE id=1').first();if(u){const current=await db.prepare('SELECT * FROM users WHERE id=?').bind(u.id).first();if(!current||current.status!=='active')fail(403,'账号已停用或权限已更新');Object.assign(u,current)}const s=normalizeWorkspace(JSON.parse(row.data));const result=await mutate(s);const r=await db.prepare('UPDATE workspace SET data=?,version=version+1 WHERE id=1 AND version=?').bind(JSON.stringify(s),row.version).run();if(r.meta.changes)return result||{ok:true}}fail(409,'其他成员刚刚更新了数据，请刷新后重试')}
async function route(req,env){const url=new URL(req.url),path=url.pathname,db=env.DB;if(!path.startsWith('/api/')){if(path==='/sop-docs.json'){if(!db)fail(503,'数据库暂不可用');const sopUser=await session(req,db);if(!sopUser||sopUser.status!=='active')fail(401,'请先登录')}const file=path==='/'?'/index.html':path;const asset=assets[file];if(!asset)return new Response('Not found',{status:404});return new Response(asset.base64?Uint8Array.from(atob(asset.body),c=>c.charCodeAt(0)):asset.body,{headers:{'Content-Type':asset.type,'Cache-Control':'no-store, max-age=0','CDN-Cache-Control':'no-store','Cloudflare-CDN-Cache-Control':'no-store'}})}if(!db)fail(503,'数据库暂不可用');const post=req.method==='POST';if(req.method!=='GET'&&!post)fail(405,'不支持的请求方式');if(post){if(req.headers.get('origin')!==url.origin)fail(403,'请求来源不正确');if(req.headers.get('x-fr-request')!=='1')fail(403,'请求校验失败')}
const b=post?await body(req):{},ip=req.headers.get('cf-connecting-ip')||'unknown';
if(path==='/api/info'&&!post){const owner=await db.prepare('SELECT id FROM users WHERE owner=1').first();const u=await session(req,db);return json({version:'v1.0.5',initialized:!!owner,user:u?safeUser(u):null,departments:DEPTS})}
if(path==='/api/setup'&&post){await limit(db,'setup:'+ip,10);if(!env.BOOTSTRAP_HASH||typeof b.token!=='string'||await digest(b.token)!==env.BOOTSTRAP_HASH)fail(403,'初始化链接无效');const f=userFields(b),pw=await bcrypt.hash(pass(b.password),12),id=crypto.randomUUID();const r=await db.prepare("INSERT INTO users (id,username,name,dept,role,status,password,owner,created) SELECT ?,?,?,?,'admin','active',?,1,? WHERE NOT EXISTS (SELECT 1 FROM users WHERE owner=1)").bind(id,f.username,f.name,'',pw,Date.now()).run();if(!r.meta.changes)fail(409,'负责人账号已初始化，请直接登录');return json({ok:true},200,{'Set-Cookie':await startSession(db,{id})})}
if(path==='/api/register'&&post){await limit(db,'register:'+ip,8);if(!await db.prepare('SELECT id FROM users WHERE owner=1').first())fail(409,'负责人尚未完成初始化');const f=userFields(b),id=crypto.randomUUID(),pw=await bcrypt.hash(pass(b.password),12);if(b.invite){const hash=await digest(text(b.invite,128));const results=await db.batch([db.prepare("INSERT INTO users (id,username,name,dept,role,status,password,created) SELECT ?,?,?,dept,role,'active',?,? FROM invitations WHERE hash=? AND used_by IS NULL AND expires>?").bind(id,f.username,f.name,pw,Date.now(),hash,Date.now()),db.prepare('UPDATE invitations SET used_by=? WHERE hash=? AND used_by IS NULL AND EXISTS (SELECT 1 FROM users WHERE id=?)').bind(id,hash,id)]);if(!results[0].meta.changes)fail(400,'邀请码无效、已使用或已过期')}else await db.prepare("INSERT INTO users (id,username,name,dept,role,status,password,created) VALUES (?,?,?,?,'member','pending',?,?)").bind(id,f.username,f.name,f.dept,pw,Date.now()).run();return json({ok:true},200,{'Set-Cookie':await startSession(db,{id})})}
if(['/api/captcha','/api/login'].includes(path)&&post){
 const username=typeof b.username==='string'?b.username.trim().toLowerCase():'';
 if(!/^[a-z0-9][a-z0-9_.-]{2,31}$/.test(username))fail(400,'请检查用户名格式');
 // Trust edge context supplied by the local gateway, never a client-supplied IP header.
 const peer=env.TELEMETRY_CONTEXT?.ip||(req.cf?req.headers.get('cf-connecting-ip'):'')||'unknown';
 await limit(db,(path==='/api/captcha'?'captcha:':'login-ip:')+peer,path==='/api/captcha'?60:35);
 if(path==='/api/captcha')return json(await issueChallenge(db,username,peer));
 const g=await guard(db,username),security=(status,code,error,meta)=>json({error,code,...meta},status,{'X-FR-Security':code,...(meta.retryAfter?{'Retry-After':String(meta.retryAfter)}:{})});
 if(g.locked)return security(423,'PASSWORD_LOCKED','密码错误已达 10 次，请联系管理员重置密码。',{locked:true,failures:10,captchaRequired:true,retryAfter:0});
 if(g.retryAfter)return security(429,'PASSWORD_COOLDOWN','密码错误达到冷却限制，请等待后重试。',{failures:g.failures,captchaRequired:true,retryAfter:g.retryAfter});
 if(g.failures>=3&&!await consumeChallenge(db,username,peer,b.captchaId,b.captchaAnswer))return security(400,'CAPTCHA_REJECTED','验证码无效或已过期，请刷新验证码。',{failures:g.failures,captchaRequired:true,retryAfter:0});
 const u=await db.prepare('SELECT * FROM users WHERE username=?').bind(username).first(),dummy='$2b$12$C6UzMDM.H6dfI/f/IKcEe.5VYVv2.UaOsRB3J3GV.gKEelSJ8ZpuK';
 if(typeof b.password!=='string'||b.password.length>100||!await bcrypt.compare(b.password,u?.password||dummy)||!u){
  const failed=await failedPassword(db,g);if(!failed)return security(409,'LOGIN_CHANGED','登录状态已更新，请重新输入。',{});
  return security(failed.locked?423:failed.retryAfter?429:401,failed.locked?'PASSWORD_LOCKED':failed.retryAfter?'PASSWORD_COOLDOWN':'LOGIN_REJECTED',failed.locked?'密码错误已达 10 次，请联系管理员重置密码。':failed.retryAfter?'密码不正确，请等待冷却后重试。':'用户名或密码不正确',failed);
 }
 if(u.status==='disabled')fail(403,'账号已停用，请联系负责人');
 if(!await succeedPassword(db,g))return security(409,'LOGIN_CHANGED','登录状态已更新，请重新输入。',{});
 return json({ok:true},200,{'Set-Cookie':await startSession(db,u)});
}
if(path==='/api/recover'&&post){await limit(db,'recover:'+ip,10);const hash=await digest(text(b.token,128)),target=await db.prepare('SELECT users.username FROM users JOIN resets ON users.id=resets.user WHERE resets.hash=? AND resets.used=0 AND resets.expires>?').bind(hash,Date.now()).first(),pw=await bcrypt.hash(pass(b.password),12);const r=await db.batch([db.prepare('UPDATE users SET password=? WHERE id=(SELECT user FROM resets WHERE hash=? AND used=0 AND expires>?)').bind(pw,hash,Date.now()),db.prepare('DELETE FROM sessions WHERE user=(SELECT user FROM resets WHERE hash=? AND used=0 AND expires>?)').bind(hash,Date.now()),db.prepare('UPDATE resets SET used=1 WHERE hash=? AND used=0 AND expires>?').bind(hash,Date.now())]);if(!r[0].meta.changes)fail(400,'重置链接无效或已过期');if(target)await clearPasswordGuard(db,target.username);return json({ok:true})}
const u=await session(req,db);if(!u)fail(401,'请先登录');if(path==='/api/logout'&&post){const raw=(req.headers.get('cookie')||'').match(/fr_session_v2=([a-f0-9]{64})/)?.[1];if(raw)await db.prepare('DELETE FROM sessions WHERE hash=?').bind(await digest(raw)).run();return json({ok:true},200,{'Set-Cookie':clearCookie})}if(u.status!=='active')fail(403,u.status==='pending'?'账号等待负责人审核':'账号已停用');
await ensureProfiles(db);await ensurePreferences(db);
if(post&&['/api/settings/save','/api/account/request','/api/account/cancel','/api/account/review'].includes(path)){if(path==='/api/account/request')await limit(db,'account-password-check:'+u.id,8);return json(await preferenceRoutes(path,b,u,db,{fail,text,departments:DEPTS}))}
const ownProfile=await db.prepare('SELECT * FROM member_profiles WHERE user=?').bind(u.id).first();u.avatar=ownProfile?.avatar||'';
if(post&&['/api/profile/request','/api/profile/review'].includes(path))return json(await profileRoutes(path,b,u,db,{fail,text}));
if(path==='/api/stats'&&!post){if(!admin(u))fail(403,'需要管理员权限');return json(await readStatistics(db,Number(url.searchParams.get('days')||14)))}
if(path==='/api/stats/maintenance'&&post){if(!admin(u))fail(403,'需要管理员权限');await limit(db,'statistics-maintenance:'+u.id,8);if(!['repair','clear'].includes(b.action))fail(400,'请选择有效的统计维护操作');return json(await maintainStatistics(db,b.action))}
if(path==='/api/password'&&post){await limit(db,'password:'+u.id,8);if((await guard(db,u.username)).locked)fail(423,'请联系管理员获取重置链接');if(typeof b.oldPassword!=='string'||!await bcrypt.compare(b.oldPassword,u.password))fail(400,'当前密码不正确');const pw=await bcrypt.hash(pass(b.password),12);await db.batch([db.prepare('UPDATE users SET password=? WHERE id=?').bind(pw,u.id),db.prepare('DELETE FROM sessions WHERE user=?').bind(u.id)]);await clearPasswordGuard(db,u.username);return json({ok:true},200,{'Set-Cookie':await startSession(db,u)})}
if(path==='/api/state'&&!post){const row=await db.prepare('SELECT data FROM workspace WHERE id=1').first();const s=normalizeWorkspace(row?JSON.parse(row.data):blank());const people=(await db.prepare("SELECT users.id,username,name,dept,role,status,owner,COALESCE(member_profiles.avatar,'') AS avatar FROM users LEFT JOIN member_profiles ON users.id=member_profiles.user WHERE status='active'").all()).results.map(p=>({...p,dept:p.owner?'':p.dept}));const permissionPeople=(await db.prepare('SELECT id,dept,role,owner FROM users').all()).results;const settings=await readPreferences(db,u),visible=visibleWorkspace(s,u,settings.workspace);const accountRequest=await db.prepare('SELECT status,reason,review_note FROM account_requests WHERE user=?').bind(u.id).first();return json({version:'v1.0.5',settings,accountRequest,...extendState(s,u),profile:ownProfile,ranking:people.map(p=>({id:p.id,name:p.name,dept:p.dept,avatar:p.avatar,points:(s.ledger||[]).filter(x=>x.user===p.id).reduce((n,x)=>n+Math.round(x.points*100),0)/100})).sort((a,b)=>b.points-a.points||a.name.localeCompare(b.name)),user:safeUser(u),people,...visible,tasks:visible.tasks.map(t=>({...t,...TaskModel.permissions(t,u,permissionPeople,s.events.find(e=>e.id===t.event))})),logs:admin(u)?s.logs:[]})}
if(path==='/api/events/delete'&&post){return json(await shared(db,s=>{const ev=s.events.find(x=>x.id===b.id);if(!ev||!canManageEvent(u,ev))fail(403,'无权删除此活动');s.events=s.events.filter(x=>x.id!==ev.id);s.tasks=s.tasks.filter(t=>t.event!==ev.id);s.ledger=s.ledger.filter(x=>x.event!==ev.id);log(s,`已删除活动「${ev.name}」`,'all',ev.department);return {ok:true}},u))}
if(path==='/api/members'&&!post){const rows=await db.prepare("SELECT users.id,username,name,dept,role,status,owner,COALESCE(member_profiles.avatar,'') AS avatar FROM users LEFT JOIN member_profiles ON users.id=member_profiles.user ORDER BY dept,name").all();const visible=rows.results.map(p=>({...p,dept:p.owner?'':p.dept})).filter(p=>p.status==='active'||admin(u)||manager(u)&&p.dept===u.dept);const reviews=admin(u)?(await db.prepare("SELECT member_profiles.*,users.name,users.dept FROM member_profiles JOIN users ON users.id=member_profiles.user WHERE review_status='pending' ORDER BY requested").all()).results:[];const closures=admin(u)?(await db.prepare("SELECT account_requests.*,users.name,users.dept FROM account_requests JOIN users ON users.id=account_requests.user WHERE account_requests.status='pending'").all()).results:[];return json({members:visible,reviews,closures})}
if(path==='/api/members/update'&&post){if(!manager(u))fail(403,'需要负责人权限');const id=text(b.id);if(!['member','manager','admin'].includes(b.role)||!['active','disabled'].includes(b.status)||!DEPTS.includes(b.dept))fail(400,'权限设置无效');for(let attempt=0;attempt<3;attempt++){
 await db.prepare('INSERT OR IGNORE INTO workspace (id,version,data) VALUES (1,0,?)').bind(JSON.stringify(blank())).run();const row=await db.prepare('SELECT version,data FROM workspace WHERE id=1').first();const actor=await db.prepare('SELECT * FROM users WHERE id=?').bind(u.id).first(),other=await db.prepare('SELECT * FROM users WHERE id=?').bind(id).first();if(!actor||actor.status!=='active'||!manager(actor))fail(403,'需要负责人权限');if(!other||other.owner||other.id===actor.id||other.username.startsWith('closed-'))fail(403,'不能修改此账号');if(!admin(actor)&&(other.dept!==actor.dept||other.role!=='member'||b.role!=='member'||b.dept!==actor.dept))fail(403,'部门负责人只能管理本部门普通成员');
 // Keep every statement conditional until the final version bump. A manager's allowed update preserves this predicate.
 const condition="EXISTS (SELECT 1 FROM workspace WHERE id=1 AND version=?) AND EXISTS (SELECT 1 FROM users actor JOIN users target ON target.id=? WHERE actor.id=? AND actor.status='active' AND COALESCE(target.owner,0)=0 AND target.id<>actor.id AND target.username NOT LIKE 'closed-%' AND (actor.role='admin' OR (actor.role='manager' AND target.role='member' AND target.dept=actor.dept AND ?='member' AND ?=actor.dept)))",args=[row.version,id,actor.id,b.role,b.dept];
 const results=await db.batch([db.prepare('UPDATE users SET role=?,dept=?,status=? WHERE id=? AND '+condition).bind(b.role,b.dept,b.status,id,...args),db.prepare('DELETE FROM sessions WHERE user=? AND '+condition).bind(id,...args),db.prepare('UPDATE workspace SET version=version+1 WHERE id=1 AND '+condition).bind(...args)]);if(results[0].meta.changes&&results[2].meta.changes)return json({ok:true});
 }fail(409,'其他成员刚刚更新了权限，请刷新后重试')}
if(path==='/api/invite'&&post){if(!manager(u))fail(403,'需要负责人权限');if(!DEPTS.includes(b.dept)||!['member','manager'].includes(b.role))fail(400,'邀请设置无效');if(!admin(u)&&(b.dept!==u.dept||b.role!=='member'))fail(403,'只能邀请本部门普通成员');const token=random();await db.prepare('INSERT INTO invitations (hash,dept,role,expires,created_by) VALUES (?,?,?,?,?)').bind(await digest(token),b.dept,b.role,Date.now()+7*DAY,u.id).run();return json({token,expires:Date.now()+7*DAY})}
if(path==='/api/reset-link'&&post){if(!manager(u))fail(403,'需要负责人权限');const other=await db.prepare('SELECT * FROM users WHERE id=?').bind(text(b.id)).first();if(!other||other.id===u.id||!admin(u)&&(other.owner||other.dept!==u.dept||other.role!=='member'))fail(403,'不能重置此账号');if((await guard(db,other.username)).locked&&!admin(u))fail(403,'密码锁定后必须由管理员提供重置链接');const token=random();await db.batch([db.prepare('UPDATE resets SET used=1 WHERE user=?').bind(other.id),db.prepare('INSERT INTO resets (hash,user,expires,used) VALUES (?,?,?,0)').bind(await digest(token),other.id,Date.now()+DAY)]);return json({token})}
if(post&&['/api/events/create','/api/events/update','/api/tasks/create','/api/templates/save'].includes(path))return json(await workflows(path,b,u,db,{fail,text,date,shift,shared,log,canManageEvent,manager}));
if(path==='/api/events/reschedule'&&post){const d=date(b.date);return json(await shared(db,s=>{const ev=s.events.find(x=>x.id===b.id);if(!ev||!canManageEvent(u,ev))fail(403,'无权调整此活动');const days=Math.round((Date.parse(d)-Date.parse(ev.date))/DAY);s.tasks.filter(t=>t.event===ev.id&&t.status!=='done').forEach(t=>{t.due=shift(t.due,days);log(s,`「${t.name}」时间调整为 ${t.due.replace('T',' ')}`,TaskModel.owners(t))});if(ev.endDate)ev.endDate=shift(ev.endDate,days);ev.date=d;log(s,`「${ev.name}」日期已调整`);return {ok:true}},u))}
if(path==='/api/tasks/action'&&post)return json(await taskAction(b,u,db,{fail,text,date,shared,log}));
fail(404,'接口不存在')}
export default {async fetch(req,env){const started=Date.now();let res;try{res=await route(req,env)}catch(e){const conflict=String(e.message).includes('UNIQUE constraint');res=json({error:conflict?'用户名已被使用，或该操作已完成':e.status?e.message:'服务暂时不可用，请稍后重试'},conflict?409:e.status||500);if(!e.status&&!conflict)console.error('WORKBENCH_REQUEST_FAILED')}await recordRequest(req,res,env,started);const headers=new Headers(res.headers);headers.set('X-Content-Type-Options','nosniff');headers.set('Referrer-Policy','no-referrer');headers.set('Permissions-Policy','camera=(), microphone=(), geolocation=()');headers.set('Content-Security-Policy',"default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'self'; object-src 'none'; base-uri 'none'; form-action 'self'; frame-ancestors 'self'");return new Response(res.body,{status:res.status,headers})}};
