// Shared workspace settings and interactive organization.
const prefs=()=>state.settings||{},scope=()=>prefs().workspace||'';
let accountPinned=false,openDepartments=new Set(),personPinned='',bubblePositions=new Map();
const priorityBadge=t=>`<span class="priority ${t.priority||'normal'}">${WorkspaceModel.priorities[t.priority||'normal']?.label||'普通'}优先级</span>`;
const priorityField=(t={})=>`<label class="field">优先级<select name="priority">${Object.entries(WorkspaceModel.priorities).map(([v,p])=>`<option value="${v}" ${v===(t.priority||'normal')?'selected':''}>${p.label}</option>`).join('')}</select></label>`;
const originalTaskRow=taskRow;taskRow=t=>originalTaskRow(t).replace('<div class="row-tail">',`<div class="row-tail">${priorityBadge(t)}`);
function groupedTasks(tasks){return WorkspaceModel.groups(state.events,tasks).filter(g=>g.tasks.length).map(g=>`<details class="panel task-group" data-expand="${g.id}" open><summary><span>${esc(g.name)}</span><small>${g.tasks.filter(t=>t.status==='done').length}/${g.tasks.length} 已完成</small></summary>${g.tasks.map(taskRow).join('')}</details>`).join('')||'<div class="panel empty">暂无任务</div>'}
function urgentPanel(tasks){const urgent=tasks.filter(t=>t.status!=='done'&&['high','urgent'].includes(t.priority));return urgent.length?`<section class="urgent-panel"><h2>急急急 <small>${urgent.length} 项高优先级待办</small></h2>${groupedTasks(urgent)}</section>`:''}
tasksView=()=>{const ts=state.tasks.filter(t=>t.owner===user.id||t.receiver===user.id);return head('我的任务','未完成优先；截止日期优先，同一时间按优先级排列。')+urgentPanel(ts)+groupedTasks(ts)};
const previousActivities=activitiesView;activitiesView=()=>{const old=state.events;state.tasks.sort(WorkspaceModel.compare);state.events=WorkspaceModel.groups(old,state.tasks);try{return urgentPanel(state.tasks)+previousActivities()}finally{state.events=old}};
const previousOverview=overview;overview=()=>{state.tasks.sort(WorkspaceModel.compare);return urgentPanel(state.tasks)+previousOverview()};
const previousFields=eventFields;eventFields=(e={})=>`<label class="field">工作模式<select name="department">${options(['',...(admin()?depts:[user.dept])],e.department??scope())}</select><small>空白为全体协作；部门内部日程只允许本部门派单。</small></label>${priorityField(e)}${previousFields(e)}`;
document.addEventListener('change',e=>{if(e.target.name==='department'&&e.target.form?.id==='create-form')renderAssignments()});
const previousPeopleOptions=peopleOptions;peopleOptions=value=>{const dept=$('#dialog form [name=department]')?.value||state.events.find(e=>e.id===$('#dialog form')?.dataset.event)?.department||scope();return dept?`<optgroup label="${esc(dept)}">${state.people.filter(p=>p.dept===dept).map(p=>`<option value="${p.id}" ${p.id===value?'selected':''}>${esc(p.name)}</option>`).join('')}</optgroup>`:previousPeopleOptions(value)};
const previousShowTask=showTask;showTask=id=>{previousShowTask(id);const t=state.tasks.find(t=>t.id===id);if(t)$('#dialog .modal-content').insertAdjacentHTML('afterbegin',priorityBadge(t))};
new MutationObserver(()=>{for(const f of document.querySelectorAll('#task-new-form,#assign-form'))if(!f.elements.priority)f.insertAdjacentHTML('afterbegin',priorityField(state.tasks.find(t=>t.id===f.dataset.id)||state.events.find(e=>e.id===f.dataset.event)||{}))}).observe($('#dialog-body'),{childList:true,subtree:true});
function dayHierarchy(key){const tasks=visibleTasks().filter(t=>t.due.startsWith(key));return visibleEvents().filter(e=>tasks.some(t=>t.event===e.id)||e.date<=key&&(e.endDate||e.date)>=key).map(e=>`<div class="day-group"><button class="cal-event activity" data-event="${e.id}">${esc(e.name)}</button>${tasks.filter(t=>t.event===e.id).sort(WorkspaceModel.compare).map(t=>`<button class="cal-child" data-task="${t.id}">${priorityBadge(t)} ${esc(t.name)}<small>${t.due.slice(11)}</small></button>`).join('')}</div>`).join('')}
const previousCalendar=calendarView;calendarView=()=>{const html=previousCalendar();return html.replace(/(<div class="day[^>]*>)([\s\S]*?)(<\/div>)/g,(all,start,body,end)=>{const key=body.match(/data-select-day="([^"]+)"/);return key?start+body.slice(0,body.indexOf('</button>')+9)+dayHierarchy(key[1])+end:all})};
const previousTimeline=timelineView;timelineView=()=>previousTimeline().replace(/<div class="selected-day">[\s\S]*?<\/div>(?=<\/section>)/,`<div class="selected-day"><h3>${esc(selectedDay)}</h3>${groupedTasks(visibleTasks().filter(t=>t.due.startsWith(selectedDay)))}</div>`).replace(/(<button class="time-event" data-event="([^"]+)">)([^<]*)(<\/button>)/g,(all,start,id,title,end)=>start+title+end+`<div class="lane-children">${state.tasks.filter(t=>t.event===id).sort(WorkspaceModel.compare).map(t=>`<button data-task="${t.id}">${priorityBadge(t)} ${esc(t.name)}</button>`).join('')}</div>`);
function accountDock(){return `<aside class="account-dock ${accountPinned?'pinned':''}"><button class="account-trigger" data-account aria-expanded="${accountPinned}">${avatarMarkup(user)}<span>${esc(user.name)}</span>⌃</button><div class="account-menu"><div class="account-heading">${avatarMarkup(user)}<div><b>${esc(user.name)}</b><small>@${esc(user.username)} · ${roleNames[user.role]}</small></div></div><p>${esc(user.dept)} · ${esc(scope()||'全体协作')}</p><button data-profile>我的主页 / 姓名与头像</button><button data-settings>⚙ 设置</button><button data-switch-account>更换账号</button><button data-logout>退出登录</button><small>v1.0.1 · ${accountPinned?'已固定，点击头像取消':'点击或右键头像固定'}</small></div></aside>`}
function workspacePicker(){modal('选择工作空间',`<p class="sub">每个模式都有自己的排期、分工与主题色。权限仍按账号角色执行。</p><div class="workspace-options">${['',...depts].map(d=>`<button data-workspace="${esc(d)}" style="--dept-color:${d?deptColor(d):'#e77b24'}"><b>${esc(d||'全体协作')}</b><small>${d?departmentDescriptions[d]:'跨部门协作与共享日程'}</small></button>`).join('')}</div>`)}
const departmentDescriptions={'办公室':'统筹需求 · 日程与交接','新媒体运营部':'内容策划 · 推送与发布','视觉传达部':'摄影摄像 · 素材与影像','创意设计部':'视觉创作 · 海报与文创'};
function aeroOrganizationActive(){return true}
function memberPreview(id){const p=members.find(p=>p.id===id);if(!p)return;let panel=$('.member-profile-portal');if(!panel){panel=document.createElement('aside');panel.className='member-profile-portal';panel.setAttribute('role','region');document.body.append(panel)}panel.innerHTML=`${avatarMarkup(p)}<h3>${esc(p.name)}</h3><p>@${esc(p.username)}</p><p>${esc(p.dept)} · ${roleNames[p.role]}</p><small>${Number(state.ranking?.find(x=>x.id===p.id)?.points||0)} 贡献积分</small><button class="text-btn" data-close-person>关闭主页</button>`}
document.addEventListener('pointerover',e=>{const b=e.target.closest('[data-person]');if(b&&!personPinned)memberPreview(b.dataset.person)});
document.addEventListener('pointerout',e=>{if(e.target.closest('.person-bubble')&&!e.target.closest('.person-bubble').contains(e.relatedTarget)&&!personPinned&&!e.relatedTarget?.closest?.('.member-profile-portal'))$('.member-profile-portal')?.remove()});
document.addEventListener('click',e=>{const b=e.target.closest('[data-person]');if(b)queueMicrotask(()=>{if(personPinned)memberPreview(personPinned);else $('.member-profile-portal')?.remove()});if(e.target.closest('[data-close-person]')){personPinned='';$('.member-profile-portal')?.remove();document.querySelectorAll('.person-bubble.pinned').forEach(el=>el.classList.remove('pinned'))}});
document.addEventListener('keydown',e=>{if(e.key==='Escape')$('.member-profile-portal')?.remove()});
function expandOrganization(dept){if(!dept){openDepartments=new Set(depts);organizationDept=''}else{openDepartments.has(dept)?openDepartments.delete(dept):openDepartments.add(dept)}render()}
organizationGraph=()=>`<section class="panel organization"><div class="panel-head"><h2>学媒协作星图</h2><div><button class="text-btn" data-org-dept="">显示全部</button><button class="text-btn" data-collapse-org>收起全部</button></div></div><div class="aero-map"><svg class="org-lines" viewBox="0 0 100 100" preserveAspectRatio="none">${depts.map((d,i)=>{const pos=bubblePositions.get(d)||[[23,24],[77,24],[23,75],[77,75]][i];return `<line data-line="${esc(d)}" x1="50" y1="50" x2="${pos[0]}" y2="${pos[1]}" stroke="${deptColor(d)}"/>`}).join('')}</svg><div class="aero-center">冯如学媒<small>MEDIA CENTER</small></div>${depts.map((d,i)=>{const pos=bubblePositions.get(d)||[[23,24],[77,24],[23,75],[77,75]][i],ps=members.filter(p=>p.dept===d&&p.status==='active').sort((a,b)=>({admin:0,manager:1,member:2}[a.role])-({admin:0,manager:1,member:2}[b.role]));return `<div class="aero-cluster" style="left:${pos[0]}%;top:${pos[1]}%;--dept-color:${deptColor(d)}"><button class="dept-bubble" data-org-dept="${esc(d)}" data-bubble-drag="${esc(d)}"><b>${esc(d)}</b><small>${departmentDescriptions[d]}</small><small>${ps.length} 位伙伴 · ${openDepartments.has(d)?'收起':'展开'}</small></button>${openDepartments.has(d)?`<div class="member-orbit">${ps.map(p=>`<div class="person-bubble ${personPinned===p.id?'pinned':''}"><button data-person="${p.id}">${avatarMarkup(p)}<b>${esc(p.name)}</b><small>${roleNames[p.role]}</small></button><div class="person-home">${avatarMarkup(p)}<h3>${esc(p.name)}</h3><p>@${esc(p.username)}</p><p>${esc(p.dept)} · ${roleNames[p.role]}</p><small>已开通 · ${Number(state.ranking?.find(x=>x.id===p.id)?.points||0)} 贡献积分</small></div></div>`).join('')||'<small>期待伙伴加入</small>'}</div>`:''}</div>`}).join('')}</div></section>`;
let accountClosures=[];const previousRefresh=refresh;refresh=async()=>{if(view==='members'&&admin())accountClosures=(await baseApi('members')).closures||[];return previousRefresh()};
const previousMembers=membersView;membersView=()=>previousMembers()+(admin()&&accountClosures.length?`<section class="panel"><h2>注销申请审核</h2>${accountClosures.map(r=>`<div class="asset-row"><div class="task-copy"><b>${esc(r.name)}</b><p>${esc(r.reason)}</p></div><button data-closure-review="${r.user}" data-revision="${r.revision}" data-decision="reject">退回</button><button data-closure-review="${r.user}" data-revision="${r.revision}" data-decision="approve">批准</button></div>`).join('')}</section>`:'');
const previousRender=render;render=()=>{previousRender();applyTheme();const term=$('.term');if(term)term.outerHTML=`<button class="term workspace-switch" data-workspace-picker><b>${esc(scope()||'学媒工作空间')}</b><span>${scope()?'部门':'协作'} ▾</span></button>`;$('.breadcrumb')?.setAttribute('title',scope()||'全体协作');document.querySelectorAll('.account-dock').forEach(e=>e.remove());document.body.insertAdjacentHTML('beforeend',accountDock());startParticles()};
const previousAuth=auth;auth=(...a)=>{document.querySelector('.account-dock')?.remove();stopParticles();previousAuth(...a)};
function applyTheme(){const p=prefs(),r=document.documentElement,c=p.themeColor||'#e77b24';r.style.setProperty('--accent',c);r.style.setProperty('--green',c);r.style.setProperty('--light',`color-mix(in srgb, ${c} 10%, var(--surface))`);r.dataset.dark=String(p.appearance==='dark'||p.appearance==='auto'&&matchMedia('(prefers-color-scheme: dark)').matches)}
async function savePreferences(next){await api('settings/save',{...prefs(),...next});await refresh()}
document.addEventListener('click',async e=>{const b=e.target.closest('button'),d=b?.dataset;if(!d)return;try{if(d.workspacePicker!==undefined)workspacePicker();if(d.workspace!==undefined){calendarDept='';await savePreferences({workspace:d.workspace,themeColor:d.workspace?deptColor(d.workspace):'#e77b24'});$('#dialog').close()}if(d.account!==undefined){accountPinned=!accountPinned;b.closest('.account-dock').classList.toggle('pinned',accountPinned);b.setAttribute('aria-expanded',accountPinned)}if(d.settings!==undefined)settingsForm();if(d.settingsTab)settingsForm(d.settingsTab);if(d.switchAccount!==undefined){await api('logout',{});user=null;auth('login','登录另一个账号即可切换。');$('#dialog').close()}if(d.clearCache!==undefined){for(const k of Object.keys(localStorage))if(k.startsWith('fr.')||k.startsWith('fengru'))localStorage.removeItem(k);if('caches' in window)for(const k of await caches.keys())await caches.delete(k);if('serviceWorker' in navigator)for(const r of await navigator.serviceWorker.getRegistrations())await r.unregister();location.reload()}if(d.cancelAccount!==undefined){await api('account/cancel',{});await refresh();settingsForm('account')}if(d.collapseOrg!==undefined){openDepartments.clear();render()}if(d.person){personPinned=personPinned===d.person?'':d.person;document.querySelectorAll('.person-bubble').forEach(el=>el.classList.toggle('pinned',el.querySelector('[data-person]').dataset.person===personPinned))}if(d.closureReview){await api('account/review',{id:d.closureReview,revision:Number(d.revision),action:d.decision});await refresh()}}catch(err){toast(err.message)}});
document.addEventListener('contextmenu',e=>{if(e.target.closest('.account-trigger')){e.preventDefault();accountPinned=true;$('.account-dock').classList.add('pinned')}});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){accountPinned=false;personPinned='';document.querySelectorAll('.pinned').forEach(el=>el.classList.remove('pinned'))}});
document.addEventListener('submit',async e=>{const f=e.target;if(!['preferences-form','closure-form'].includes(f.id))return;e.preventDefault();e.stopImmediatePropagation();if(f.dataset.saving)return;f.dataset.saving='1';const d=Object.fromEntries(new FormData(f));try{if(f.id==='preferences-form'){if(f.elements.motion)d.motion=f.elements.motion.checked;for(const k of ['particleDensity','rotationMinutes'])if(d[k])d[k]=Number(d[k]);await savePreferences(d);$('#dialog').close();toast('设置已同步')}else{await api('account/request',d);await refresh();settingsForm('account')}}catch(err){$('#form-error').textContent=err.message}finally{delete f.dataset.saving}},true);
let bubbleDrag;document.addEventListener('pointerdown',e=>{const b=e.target.closest('[data-bubble-drag]');if(!b)return;const rect=b.closest('.aero-map').getBoundingClientRect();bubbleDrag={b,rect,x:e.clientX,y:e.clientY,moved:false};b.setPointerCapture(e.pointerId)});
document.addEventListener('pointermove',e=>{if(!bubbleDrag)return;const {b,rect}=bubbleDrag;if(Math.hypot(e.clientX-bubbleDrag.x,e.clientY-bubbleDrag.y)>6)bubbleDrag.moved=true;if(!bubbleDrag.moved)return;const x=Math.max(15,Math.min(85,(e.clientX-rect.left)/rect.width*100)),y=Math.max(15,Math.min(85,(e.clientY-rect.top)/rect.height*100));bubblePositions.set(b.dataset.bubbleDrag,[x,y]);b.parentElement.style.left=x+'%';b.parentElement.style.top=y+'%';const line=[...document.querySelectorAll('[data-line]')].find(l=>l.dataset.line===b.dataset.bubbleDrag);line.setAttribute('x2',x);line.setAttribute('y2',y)});
document.addEventListener('click',e=>{if(bubbleDrag?.moved){e.stopImmediatePropagation();bubbleDrag=null}},true);document.addEventListener('pointerup',()=>{if(!bubbleDrag?.moved)bubbleDrag=null});document.addEventListener('pointercancel',()=>bubbleDrag=null);
const particleNames={off:'关闭',constellation:'星座连线',fireflies:'萤火微光',snow:'轻雪',petals:'花瓣',rain:'流星雨',orbits:'轨道光环',stars:'闪烁星空',bubbles:'漂浮气泡',random:'每次随机',rotate:'定时轮换'};
let particleFrame=0,particleSignature='',particleCanvas;
function stopParticles(){cancelAnimationFrame(particleFrame);particleCanvas?.remove();particleCanvas=null;particleSignature=''}
function startParticles(){const p=prefs(),sig=JSON.stringify(p);if(sig===particleSignature&&particleCanvas)return;stopParticles();particleSignature=sig;if(p.particles==='off'||p.motion===false||matchMedia('(prefers-reduced-motion: reduce)').matches)return;const canvas=document.createElement('canvas');canvas.className='particle-canvas';canvas.setAttribute('aria-hidden','true');document.body.prepend(canvas);particleCanvas=canvas;const ctx=canvas.getContext('2d'),styles=Object.keys(particleNames).filter(k=>!['off','random','rotate'].includes(k));let mode=p.particles||'constellation',epoch=performance.now(),randomMode=styles[Math.floor(Math.random()*styles.length)],dots=Array.from({length:p.particleDensity||32},()=>({x:Math.random(),y:Math.random(),r:Math.random()*2+1,v:Math.random()*.7+.3})),last=0;function frame(time){if(!canvas.isConnected)return;particleFrame=requestAnimationFrame(frame);if(document.hidden||time-last<33)return;const dt=Math.min(2,(time-last)/33||1);last=time;const w=innerWidth,h=innerHeight;if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h}ctx.clearRect(0,0,w,h);const current=mode==='random'?randomMode:mode==='rotate'?styles[Math.floor((time-epoch)/((p.rotationMinutes||5)*60000))%styles.length]:mode;ctx.strokeStyle=ctx.fillStyle=p.themeColor||'#e77b24';ctx.globalAlpha=.25;for(const d of dots){d.y=(d.y+(current==='rain'?.002:.00025)*d.v*dt)%1;d.x=(d.x+Math.sin(time/3000+d.r)*.00015*dt+1)%1;const x=d.x*w,y=d.y*h;ctx.beginPath();if(current==='rain'){ctx.moveTo(x,y);ctx.lineTo(x-8,y-18);ctx.stroke()}else if(current==='petals'){ctx.ellipse(x,y,d.r*2,d.r,time/4000,0,Math.PI*2);ctx.fill()}else{ctx.arc(x,y,current==='bubbles'||current==='orbits'?d.r*5:d.r,0,Math.PI*2);if(['bubbles','orbits'].includes(current))ctx.stroke();else{ctx.globalAlpha=current==='stars'||current==='fireflies'?.12+Math.abs(Math.sin(time/1500+d.r))*.25:.2;ctx.fill()}}}if(current==='constellation')for(let i=0;i<dots.length;i++)for(let j=i+1;j<dots.length;j++){const a=dots[i],b=dots[j],dist=Math.hypot((a.x-b.x)*w,(a.y-b.y)*h);if(dist<120){ctx.globalAlpha=(1-dist/120)*.12;ctx.beginPath();ctx.moveTo(a.x*w,a.y*h);ctx.lineTo(b.x*w,b.y*h);ctx.stroke()}}}particleFrame=requestAnimationFrame(frame)}
matchMedia('(prefers-reduced-motion: reduce)').addEventListener('change',()=>{particleSignature='';startParticles()});matchMedia('(prefers-color-scheme: dark)').addEventListener('change',applyTheme);
