// Only explicitly remembered credentials enter WeChat's platform-encrypted store.
// The ordinary cache contains the account name, choice and a non-secret record ID.
const OPTION='fr.loginMemory',SECRET='fr.loginCredential';
let revision=0,suppressNext=false;
const validName=x=>typeof x==='string'&&/^[A-Za-z0-9][A-Za-z0-9_.-]{2,31}$/.test(x);
function realm(config={}){return config.transport==='cloud'?'cloud:'+String(config.cloudEnv||'')+':'+String(config.cloudFunction||''):'direct:'+String(config.directBaseUrl||'').replace(/\/+$/,'')}
function supported(){try{return typeof wx.setStorage==='function'&&typeof wx.getStorage==='function'&&wx.canIUse('setStorage.object.encrypt')===true&&wx.canIUse('getStorage.object.encrypt')===true}catch{return false}}
function remove(key){try{wx.removeStorageSync(key)}catch{try{wx.removeStorage({key})}catch{}}}
function option(config,ownerOnly=false){try{const x=wx.getStorageSync(OPTION);return x&&x.remember===true&&validName(x.username)&&x.realm===realm(config)&&(!ownerOnly||x.owner===true)?{remember:true,username:x.username,realm:x.realm,record:typeof x.record==='string'?x.record:'',...(x.owner===true?{owner:true}:{})}:{remember:false,username:''}}catch{return {remember:false,username:''}}}
function encrypted(method,data){return new Promise(resolve=>{let finished=false;const timer=setTimeout(()=>{finished=true;resolve(null)},2000);try{wx[method]({key:SECRET,encrypt:true,...(data===undefined?{}:{data}),success:r=>{if(finished)return;finished=true;clearTimeout(timer);resolve(method==='getStorage'?r.data:true)},fail:()=>{if(finished)return;finished=true;clearTimeout(timer);resolve(null)}})}catch{clearTimeout(timer);finished=true;resolve(null)}})}
async function load(config,ownerOnly=false){const secure=supported();if(suppressNext){suppressNext=false;return {remember:false,username:'',password:'',secure}}const choice=option(config,ownerOnly);if(!choice.remember||!secure)return {...choice,password:'',secure};const secret=await encrypted('getStorage');if(!secret||secret.realm!==choice.realm||secret.username!==choice.username||secret.record!==choice.record||typeof secret.password!=='string'||!secret.password||secret.password.length>72)return {...choice,password:'',secure};return {...choice,password:secret.password,secure}}
function forget(){revision++;remove(OPTION);remove(SECRET)}
function forgetPassword(){revision++;remove(SECRET);try{const x=wx.getStorageSync(OPTION);if(x&&x.remember===true&&validName(x.username))wx.setStorageSync(OPTION,{remember:true,username:x.username,realm:x.realm,record:'',...(x.owner===true?{owner:true}:{})})}catch{}}
async function success(config,username,password,remember,owner=false){const current=++revision;if(!remember){forget();return false}if(!validName(username))return false;const choice={remember:true,username,realm:realm(config),record:'',...(owner===true?{owner:true}:{})};remove(SECRET);try{wx.setStorageSync(OPTION,choice)}catch{return false}if(!supported()||typeof password!=='string'||!password||password.length>72)return false;const record=String(Date.now())+'-'+String(current)+'-'+Math.random().toString(36).slice(2);const saved=await encrypted('setStorage',{...choice,record,password});if(!saved||current!==revision)return false;try{wx.setStorageSync(OPTION,{...choice,record});return true}catch{remove(SECRET);return false}}
function switchAccount(){revision++;suppressNext=true}
module.exports={supported,option,load,success,forget,forgetPassword,switchAccount,realm};
