// Shared organization scene: circle constraints, damped springs and anchored camera gestures.
module.exports=(()=>{
 const depts=['办公室','新媒体运营部','视觉传达部','创意设计部'],colors=['#168875','#d47918','#3478c5','#8b5bc7'];
 const color=dept=>colors[depts.indexOf(dept)]||'#777777',groups=people=>depts.map(dept=>({dept,color:color(dept),people:people.filter(p=>!p.owner&&p.dept===dept)}));
 const descriptions={'办公室':'统筹需求 · 日程与交接','新媒体运营部':'内容策划 · 推送与发布','视觉传达部':'摄影摄像 · 素材与影像','创意设计部':'视觉创作 · 海报与文创'};
 const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),rank={admin:0,manager:1,member:2};
 function node(s,id){return s.nodes.find(n=>n.id===id)}
 function create({width=800,height=620,fontScale=1,people=[],expanded=[]}={}){const scene={viewport:{width:Math.max(200,width),height:Math.max(280,height)},fontScale:clamp(fontScale,.85,1.35),width:800,height:620,nodes:[],expanded:[...expanded],time:0,view:{zoom:1,x:0,y:0},drag:null};reconcile(scene,people,expanded);resetView(scene);return scene}
 function layout(scene,people,expanded){
  const f=Math.sqrt(scene.fontScale),rootR=62*f,deptR=78*f,memberR=58*f,orbit=(2*memberR+16*f)/(2*Math.sin(Math.PI/9)),out=[{id:'root',kind:'root',dept:'',r:rootR,dx:0,dy:0,mass:Infinity}];
  depts.forEach((dept,i)=>{const angle=[-Math.PI*.75,-Math.PI*.25,Math.PI*.75,Math.PI*.25][i],distance=204*f,dx=Math.cos(angle)*distance,dy=Math.sin(angle)*distance;out.push({id:'dept:'+dept,kind:'department',dept,r:deptR,dx,dy,phase:i*1.53,mass:2.4});if(!expanded.includes(dept))return;const members=people.filter(p=>!p.owner&&p.dept===dept&&p.status!=='disabled'&&p.status!=='pending').sort((a,b)=>(rank[a.role]??2)-(rank[b.role]??2)||String(a.id).localeCompare(String(b.id)));members.forEach((person,j)=>{const level=Math.floor(j/3),slots=Math.min(3,members.length-level*3),slot=j%3,delta=slots===1?0:(slot/(slots-1)-.5)*Math.PI*4/9,a=angle+delta,d=orbit+level*(memberR*2+20*f),ox=Math.cos(a)*d,oy=Math.sin(a)*d;out.push({id:'person:'+person.id,kind:'person',parent:'dept:'+dept,dept,person,r:memberR,dx:dx+ox,dy:dy+oy,ox,oy,phase:j*1.71+i,mass:1})})});return out;
 }
 function reconcile(s,people=[],expanded=s.expanded){
  s.expanded=depts.filter(d=>expanded.includes(d));const specs=layout(s,people,s.expanded),padding=38*s.fontScale,halfWidth=Math.max(...specs.map(n=>Math.abs(n.dx)+n.r+padding)),halfHeight=Math.max(...specs.map(n=>Math.abs(n.dy)+n.r+padding)),width=Math.max(s.viewport.width,halfWidth*2),height=Math.max(s.viewport.height,halfHeight*2),dx=(width-s.width)/2,dy=(height-s.height)/2,old=new Map(s.nodes.map(n=>[n.id,n]));
  s.view.x-=dx*s.view.zoom;s.view.y-=dy*s.view.zoom;s.width=width;s.height=height;s.nodes=specs.map(spec=>{const existing=old.get(spec.id);if(existing){const anchorX=existing.anchorX+dx,anchorY=existing.anchorY+dy,ox=existing.ox,oy=existing.oy;existing.x+=dx;existing.y+=dy;Object.assign(existing,spec,{anchorX,anchorY});if(spec.kind==='person'){existing.ox=ox;existing.oy=oy}return existing}return {...spec,x:width/2+spec.dx,y:height/2+spec.dy,anchorX:width/2+spec.dx,anchorY:height/2+spec.dy,vx:0,vy:0,held:false}});if(s.drag&&!node(s,s.drag.id))s.drag=null;solve(s,28);return s;
 }
 function resize(s,width,height,fontScale=s.fontScale){const w=Math.max(200,width),h=Math.max(280,height),cx=w-s.viewport.width,cy=h-s.viewport.height,newScale=clamp(fontScale,.85,1.35),ratio=Math.sqrt(newScale/s.fontScale);if(ratio!==1)for(const n of s.nodes){n.x=s.width/2+(n.x-s.width/2)*ratio;n.y=s.height/2+(n.y-s.height/2)*ratio;n.anchorX=s.width/2+(n.anchorX-s.width/2)*ratio;n.anchorY=s.height/2+(n.anchorY-s.height/2)*ratio;if(n.kind==='person'){n.ox*=ratio;n.oy*=ratio}}s.viewport={width:w,height:h};s.fontScale=newScale;s.view.x+=cx/2;s.view.y+=cy/2;return reconcile(s,s.nodes.filter(n=>n.kind==='person').map(n=>n.person),s.expanded)}
 function boundary(s,n){n.x=clamp(n.x,n.r+2,s.width-n.r-2);n.y=clamp(n.y,n.r+2,s.height-n.r-2)}
 function solve(s,passes=12){const gap=12*s.fontScale;for(let k=0;k<passes;k++){let maximum=0;for(let i=0;i<s.nodes.length;i++)for(let j=i+1;j<s.nodes.length;j++){const a=s.nodes[i],b=s.nodes[j];let dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy),minimum=a.r+b.r+gap;if(d>=minimum)continue;if(d<.0001){dx=Math.cos(i*1.9+j);dy=Math.sin(i*1.9+j);d=.0001}else{dx/=d;dy/=d}const overlap=minimum-d+.001;maximum=Math.max(maximum,overlap);let ia=a.kind==='root'||a.held?0:1/a.mass,ib=b.kind==='root'||b.held?0:1/b.mass;if(!ia&&!ib){if(a.held)ia=1;else if(b.held)ib=1;else continue}const total=ia+ib;a.x-=dx*overlap*ia/total;a.y-=dy*overlap*ia/total;b.x+=dx*overlap*ib/total;b.y+=dy*overlap*ib/total;const closing=(b.vx-a.vx)*dx+(b.vy-a.vy)*dy;if(closing<0){const impulse=-closing*1.35/total;if(!a.held&&a.kind!=='root'){a.vx-=dx*impulse*ia;a.vy-=dy*impulse*ia}if(!b.held&&b.kind!=='root'){b.vx+=dx*impulse*ib;b.vy+=dy*impulse*ib}}}for(const n of s.nodes)boundary(s,n);if(maximum<.02)break}}
 function step(s,dt,motion=true){if(!motion||!Number.isFinite(dt)||dt<=0)return s;dt=Math.min(.065,dt);const count=Math.ceil(dt/(1/120)),h=dt/count;for(let i=0;i<count;i++){s.time+=h;for(const n of s.nodes){if(n.kind==='root'||n.held)continue;let tx,ty,k,damping;if(n.kind==='department'){const a=34*s.fontScale,phase=s.time*.72+n.phase;tx=n.anchorX+Math.sin(phase)*a+Math.sin(phase*1.53)*a*.25;ty=n.anchorY+Math.cos(phase*.87)*a+Math.sin(phase*1.27)*a*.18;k=24;damping=7.2}else{const p=node(s,n.parent);if(!p)continue;const a=16*s.fontScale;tx=p.x+n.ox+Math.sin(s.time*.95+n.phase)*a;ty=p.y+n.oy+Math.cos(s.time*.84+n.phase)*a;k=31;damping=7.8}n.vx=clamp(n.vx+((tx-n.x)*k-n.vx*damping)*h,-850,850);n.vy=clamp(n.vy+((ty-n.y)*k-n.vy*damping)*h,-850,850);n.x+=n.vx*h;n.y+=n.vy*h;boundary(s,n)}solve(s,10)}return s}
 function beginDrag(s,id,x,y,time=0){const n=node(s,id);if(!n||n.kind==='root')return false;if(s.drag)endDrag(s,time);s.drag={id,offsetX:n.x-x,offsetY:n.y-y,lastX:n.x,lastY:n.y,lastTime:time,lastMoveTime:time,initialVx:n.vx,initialVy:n.vy,moved:false};n.held=true;return true}
 function drag(s,x,y,time=0){const d=s.drag,n=d&&node(s,d.id);if(!n)return;const nx=x+d.offsetX,ny=y+d.offsetY,elapsed=clamp((time-d.lastTime)/1000,.008,.12);n.x=nx;n.y=ny;boundary(s,n);n.vx=clamp((n.x-d.lastX)/elapsed,-800,800);n.vy=clamp((n.y-d.lastY)/elapsed,-800,800);Object.assign(d,{lastX:n.x,lastY:n.y,lastTime:time,lastMoveTime:time,moved:true});solve(s,24)}
 function endDrag(s,time=0,cancel=false){const d=s.drag,n=d&&node(s,d.id);if(n){n.held=false;if(cancel||!d.moved){n.vx=d.initialVx;n.vy=d.initialVy}else{const decay=Math.exp(-Math.max(0,time-d.lastMoveTime-70)/180);n.vx*=decay;n.vy*=decay;if(n.kind==='department'){n.anchorX=n.x;n.anchorY=n.y}else{const p=node(s,n.parent);n.ox=n.x-p.x;n.oy=n.y-p.y}}}s.drag=null}
 const project=(s,x,y)=>({x:x*s.view.zoom+s.view.x,y:y*s.view.zoom+s.view.y}),unproject=(s,x,y)=>({x:(x-s.view.x)/s.view.zoom,y:(y-s.view.y)/s.view.zoom});
 function setZoom(s,zoom,x=s.viewport.width/2,y=s.viewport.height/2){const world=unproject(s,x,y),z=clamp(zoom,.55,1.8);s.view.zoom=z;s.view.x=x-world.x*z;s.view.y=y-world.y*z;return s.view}
 function pan(s,dx,dy){s.view.x=clamp(s.view.x+dx,44-s.width*s.view.zoom,s.viewport.width-44);s.view.y=clamp(s.view.y+dy,44-s.height*s.view.zoom,s.viewport.height-44);return s.view}
 function resetView(s){s.view.zoom=clamp(Math.min(s.viewport.width/s.width,s.viewport.height/s.height)*.94,.55,1);s.view.x=(s.viewport.width-s.width*s.view.zoom)/2;s.view.y=(s.viewport.height-s.height*s.view.zoom)/2;return s.view}
 function links(s){return s.nodes.filter(n=>n.kind!=='root').map(n=>{const parent=n.kind==='department'?node(s,'root'):node(s,n.parent);return {id:n.id,parent:parent.id,dept:n.dept,x1:parent.x,y1:parent.y,x2:n.x,y2:n.y}})}
 return {depts,color,groups,descriptions,create,reconcile,resize,step,node,solve,beginDrag,drag,endDrag,project,unproject,setZoom,pan,resetView,links};
})();
