const api=require('../services/api'),O=require('./organization'),M=require('./task-model'),UI=require('./interface'),Share=require('./sharing'),R=require('./recovery'),T=require('./task-ui');
const depts=['办公室','新媒体运营部','视觉传达部','创意设计部'];
const statuses={pending:'待确认',active:'进行中',review:'待验收',blocked:'等待前序',done:'已完成',conflict:'时间冲突',revise:'待修改'};
const roles={admin:'管理员',manager:'部门负责人',member:'成员'};
const day=(d=new Date())=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const textDate=d=>(d||'').replace('T',' ');
const shift=(s,n)=>{const d=new Date(s.slice(0,10)+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10)};
function decorate(s){if(!s)return null;s={...s,settings:R.applySettings(s.settings)};const readonly=!!s._localReadOnly;const names=Object.fromEntries(s.people.map(p=>[p.id,p.name]));const manager=!readonly&&['admin','manager'].includes(s.user.role);const events=s.events.map(e=>({...e,canEdit:!readonly&&(s.user.role==='admin'||manager&&e.createdBy===s.user.id),dateLabel:textDate(e.date)+(e.allDay===false?' '+e.startTime:' · 全天'),taskCount:s.tasks.filter(t=>t.event===e.id).length}));const tasks=s.tasks.map(t=>({...T.decorate(t,s,names),priorityLabel:M.priorities[t.priority||'normal']?.label||'普通',departmentColor:O.color(t.dept),eventName:s.events.find(e=>e.id===t.event)?.name||'',statusLabel:statuses[t.status],dueLabel:textDate(t.due),}));events.sort((a,b)=>M.compare(M.groups([a],tasks)[0].sortTask,M.groups([b],tasks)[0].sortTask));tasks.sort(M.compare);return {...s,themeStyle:UI.style(s.settings),dark:s.settings?.appearance==='dark'||s.settings?.appearance==='auto'&&wx.getSystemInfoSync?.().theme==='dark',manager,events,tasks,names,roleLabel:roles[s.user.role]}}
function recoveryHint(){return UI.language()==='en'?'The interface entered safe mode. Open Local Safety Center to repair it.':'界面已进入安全模式，可在本机安全中心修复。'}
function readonlyHint(){return UI.language()==='en'?'Using the current sign-in memory snapshot in read-only mode. Refresh before editing.':'正在使用本次登录的内存快照（只读），请刷新恢复同步后再编辑。'}
function recoverRender(owner,error){owner.interfaceFailure=true;R.capture(error,'render');try{owner.setData({interfaceFailure:true,readOnly:true,motion:false,particles:'off',syncError:recoveryHint()})}catch{}}
function renderSnapshot(owner,s){try{owner.renderState?.(decorate(s))}catch(error){recoverRender(owner,error)}}
function page(spec){const renderer=spec.renderState;spec.renderState=function(s){try{UI.navigation(this,s);this.setData({currentUser:s.user,readOnly:!!s._localReadOnly,readonlyLabel:readonlyHint(),syncError:s._localReadOnly?readonlyHint():'',motion:s.settings?.motion!==false,particleTheme:s.settings?.themeColor||'#e77b24',fontScale:UI.fontScale(s.settings),themeStyle:s.themeStyle,dark:s.dark,particles:s.settings?.particles||'constellation',particleStyle:s.settings?.particles||'constellation',particleDensity:s.settings?.particleDensity||48,particleSystem:s.settings?.particleSystem||{},rotationMinutes:s.settings?.rotationMinutes||5});renderer?.call(this,s);if(!this.interfaceFailure)R.markSuccess('render')}catch(error){recoverRender(this,error)}};const onLoad=spec.onLoad,onUnload=spec.onUnload,onShow=spec.onShow,onResize=spec.onResize;return Share.page(Object.assign({},spec,{
 onLoad(options){UI.install(this);this.options=options;this.unsubscribe=api.subscribe(s=>{if(s)renderSnapshot(this,s);else{this.setData({ready:false,user:null,currentUser:null,task:null,event:null,events:[],tasks:[],people:[],members:[],groups:[],network:[],allGroups:[],reviews:[],ranking:[],notices:[],ledger:[],selectedPerson:null,submission:'',password:'',reason:''});if(this.route!=='pages/auth/index')try{wx.reLaunch({url:'/pages/auth/index'})}catch(error){R.capture(error,'render')}}});try{const result=onLoad?.call(this,options);result?.catch?.(error=>recoverRender(this,error))}catch(error){recoverRender(this,error)}},
 async onShow(){if(!api.token()){wx.reLaunch({url:'/pages/auth/index'});return}const s=api.getState();if(s)renderSnapshot(this,s);try{await api.refresh();this.setData({readOnly:api.isReadOnly(),syncError:api.isReadOnly()?readonlyHint():''});await onShow?.call(this)}catch(e){this.setData({syncError:e.status?e.message:UI.t('暂时无法同步，请稍后刷新。')});if(e.status===403)wx.reLaunch({url:'/pages/auth/index'})}},
 onUnload(){this.unsubscribe?.();try{onUnload?.call(this)}catch(error){R.capture(error,'runtime')}},
 onResize(e){try{this.selectComponent?.('#particle-field')?.refresh?.();onResize?.call(this,e)}catch(error){R.capture(error,'canvas')}},
 navigationChange(e){this.setData({navigationOpen:!!e.detail?.open})},
 particleTouchStart(e){UI.pointer(this,e)},particleTouchMove(e){UI.pointer(this,e)},particleTouchEnd(e){UI.pointer(this,e)},
 async onPullDownRefresh(){try{await api.refresh(true);this.setData({readOnly:api.isReadOnly(),syncError:api.isReadOnly()?readonlyHint():''})}catch(e){error(e)}finally{wx.stopPullDownRefresh()}},
 accountToggle(){wx.switchTab({url:'/pages/profile/index'})},accountPin(){wx.switchTab({url:'/pages/profile/index'})},closeContext(){this.setData({accountOpen:false,selectedPerson:null})},async accountLogout(){await action(this,async()=>{try{await api.call('logout',{})}finally{api.clear();wx.reLaunch({url:'/pages/auth/index'})}})},go(e){this.setData({accountOpen:false});const url=e.currentTarget.dataset.url;if(typeof url!=='string'||!/^\/pages\/[a-z0-9/_-]+(?:\?.*)?$/i.test(url))return;if(['/pages/home/index','/pages/tasks/index','/pages/calendar/index','/pages/profile/index'].includes(url))wx.switchTab({url});else wx.navigateTo({url})},
 openTask(e){wx.navigateTo({url:'/pages/task/index?id='+encodeURIComponent(e.currentTarget.dataset.id||'')})},openEvent(e){wx.navigateTo({url:'/pages/event/index?id='+encodeURIComponent(e.currentTarget.dataset.id||'')})}
}))}

function error(e){const runtime=e?.name&&e.name!=='Error';if(runtime)R.capture(e,'runtime');wx.showModal({title:UI.t('暂未完成'),content:runtime?recoveryHint():UI.t(e?.message||'暂未完成操作'),showCancel:false})}
async function action(owner,fn){if(owner.data.busy)return;owner.setData({busy:true});try{return await fn()}catch(e){error(e)}finally{owner.setData({busy:false})}}
function copy(url){if(!url)return;wx.setClipboardData({data:url,success:()=>wx.showModal({title:'链接已复制',content:'可粘贴到云盘客户端或浏览器中访问。小程序不能直接打开任意外部网页。',showCancel:false})})}
module.exports={api,depts,statuses,roles,day,shift,textDate,decorate,page,error,action,copy};
